# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VisiGrid.VisiGrid
PackageVersion: 0.49.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: VisiGrid-windows-x64\visigrid.exe
  PortableCommandAlias: visigrid
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/VisiGrid/VisiGrid/releases/download/v0.49.0/VisiGrid-windows-x64.zip
  InstallerSha256: 96D3C52C60E0FCC68DD94507E509E3F60E1AD9BA9F5A209AF8D6B2882357430B
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-04
