# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: NaeNaeTart.AMLLTTMLTool
PackageVersion: 0.10.3
InstallerType: wix
Installers:
  - Architecture: x64
    InstallerUrl: "https://github.com/NaeNaeTart/NaeNae-AMLL-TTML-TOOL/releases/download/v0.10.3/AMLL.TTML.Tool_0.10.3_x64_en-US.msi"
    InstallerSha256: E77C315E6F43C37446F80D80E2535CC5DD252ABF259935D84F10B98BA5A84A10
ManifestType: installer
ManifestVersion: 1.12.0
