# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.kk
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win32/kk/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: 43D655AB000A6B6E4A8319DE23AADA5B18BA7C7BC2F5FDE434637FA5E18BD102
  ProductCode: Mozilla Thunderbird 153.4.0 (x86 kk)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 kk)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win64/kk/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: 415C0500521A1CAAC21ABC8F7DA09CC922F0A9D11020C500A14D9D43BBF369D3
  ProductCode: Mozilla Thunderbird 153.4.0 (x64 kk)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 kk)
ManifestType: installer
ManifestVersion: 1.12.0
