# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.MSIX
PackageVersion: 157.0.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
PackageFamilyName: Mozilla.MozillaFirefox_jag0gd4e3s9p2
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/multi/Firefox%20Setup%20157.0.1.msix
  InstallerSha256: CB009C01B0A85D084649B062244DC8EAB39B3B0BF8C8B24E99B3F7E598EA260F
  SignatureSha256: 08D291701130B7691EF10366C4C5B8ABA87CAED816EFFA0CDB07681F75592571
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/multi/Firefox%20Setup%20157.0.1.msix
  InstallerSha256: 824C3779725CAD736E6F0B1E3BC3024FF9999992AF33DF50C11F46B33B0396E0
  SignatureSha256: C6271D3D061C1C49DE1627540EA928762DD61DAA63EBE110E0A54391D0EA19B1
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/multi/Firefox%20Setup%20157.0.1.msix
  InstallerSha256: 60BDDF0F9F9E3294569317DB6582C09EC603308567D115CA4086F6C80D3809FA
  SignatureSha256: B9DC511EED74B9E0D3F34046EBC7007EABDF6DF5C59D6039BFBE6872D5D09949
ManifestType: installer
ManifestVersion: 1.12.0
