# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.hsb
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0/win32/hsb/Thunderbird%20Setup%20157.0.exe
  InstallerSha256: 6B4EF291B76EB1A9C8AA7F118665999913B6259084536DD0FEC73C69C9AB2305
  ProductCode: Mozilla Thunderbird 157.0 (x86 hsb)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0/win64/hsb/Thunderbird%20Setup%20157.0.exe
  InstallerSha256: 91F5D5AC164F17B2AC75C32269D1526F0233893C376584EC31E74C5B2E26E436
  ProductCode: Mozilla Thunderbird 157.0 (x64 hsb)
ManifestType: installer
ManifestVersion: 1.12.0
