# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Moises.Moises
PackageVersion: 2.0.16
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 5bd5b589-114e-52ce-b8c8-e099ed1b620a
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://download.todesktop.com/220410vabqjud82/Moises%20Setup%202.0.16%20-%20Build%20261007vkb6u8vx7-x64.exe
  InstallerSha256: F5B98B6FD37FDA51EA88A782FA086CEBDF65382C4BD6CE8B3281BA411A5F379B
- Architecture: arm64
  InstallerUrl: https://download.todesktop.com/220410vabqjud82/Moises%20Setup%202.0.16%20-%20Build%20261007vkb6u8vx7-arm64.exe
  InstallerSha256: 6A045EEA67D1D1962BA41E73B4EFCF6128928D2C9C26C8CEAFD8CD46A94B342D
ManifestType: installer
ManifestVersion: 1.12.0
