# Automatically updated by the winget bot at 2026/Oct/06
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: AxisCommunicationsAB.FilePlayerLauncher
PackageVersion: 3.1.10.0
Installers:
- InstallerUrl: https://ftp.axis.com/pub/axis/software/cam_srv/file_player/latest/AxisFilePlayer.exe
  Architecture: x86
  InstallerType: portable
  InstallerSha256: FF42A4A9F8F6339579C43C397B1C1370C9FBB12226ACD5A830D1167ED3781B2F
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /passive
ManifestType: installer
ManifestVersion: 1.28.0
