# Automatically updated by the winget bot at 2026/Sep/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: East-Tec.ColorVeil
PackageVersion: 4.1.0
Scope: machine
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://download.east-tec.com/colorveil/colorveil-installer.exe
  InstallerSha256: 649E736EEFE32E761FF8CBC01EDEAF838139E8A8B7397E12ED9E53F6D46791E4
  ProductCode: ColorVeil
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://download.east-tec.com/colorveil/colorveil-x64.msi
  InstallerSha256: EC6784E60C4958473957A78E407C1A2BEEF38B6B933EEC36CF0A5BE8CBCFB4E7
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{26046ABE-0131-4C8A-9F45-9EB7BAD5A2EC}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{CF805997-7AE7-4DAC-8BFC-EB1198C424BC}'
ManifestType: installer
ManifestVersion: 1.28.0
