# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: 8x8.QualityManagement
PackageVersion: 6.4.4
PackageLocale: zh-CN
License: 专有软件
ShortDescription: 质量管理屏幕录制
Description: 订阅了质量管理屏幕录制服务的用户，能够捕获客服代表的桌面屏幕。对于已在客服代表电脑上安装屏幕客户端软件的用户，系统管理员可选择同时录制客服代表的桌面操作与电话通话内容。通话结束后，您可在侧滑面板中查看录制的视频。
ManifestType: locale
ManifestVersion: 1.12.0
