# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BuilderIO.BuilderIO
PackageVersion: 0.6.2.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
Protocols:
- builder
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- UpgradeCode: '{4929A0F4-1EF8-436F-8229-3EE18C03036B}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/BuilderIO/native-app-distribution/releases/download/v0.6.2-alpha/Builder.io-0.6.2-x64.msi
  InstallerSha256: F30EA73759C6EB8B6827D68F4CC85D8C08BADED36AEA56954618577B6E96B36C
  ProductCode: '{3A74D31E-051F-4EA9-B1C1-D3435D70322F}'
- Architecture: arm64
  InstallerUrl: https://github.com/BuilderIO/native-app-distribution/releases/download/v0.6.2-alpha/Builder.io-0.6.2-arm64.msi
  InstallerSha256: 1A372E071B3E9E512FB138A8807206102EFE61E288F3EBE17D660A55045F4CB6
  ProductCode: '{20384200-0726-4BAB-BE79-BEA9F53F9D9B}'
ManifestType: installer
ManifestVersion: 1.12.0
