# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Buildkite.CLI
PackageVersion: 3.61.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: bk.exe
  PortableCommandAlias: bk
UpgradeBehavior: install
Commands:
- bk
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/buildkite/cli/releases/download/v3.61.1/bk_3.61.1_windows_amd64.zip
  InstallerSha256: 6C23CDC5CA9396A5E1DED21298FC9C85312E746E4395C0E378B7D4B19EFEF1B9
- Architecture: arm64
  InstallerUrl: https://github.com/buildkite/cli/releases/download/v3.61.1/bk_3.61.1_windows_arm64.zip
  InstallerSha256: 62E37FA7E8392A9AD0831FB45575D7D8DDDB524B66F50E5B13DF1C5DCF2F6910
ManifestType: installer
ManifestVersion: 1.28.0
