# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.568.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.568.0&arch=x86
  InstallerSha256: 887C995BF77E5AD076A7576F397E28C8B8BC10FA49FD0E4A3563337CBE3310EF
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.568.0&arch=amd64
  InstallerSha256: 80F48743A609C4B02454D1C7E4622C5C5C9743EA7070A41882518C1D97D741D9
ManifestType: installer
ManifestVersion: 1.28.0
