# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ka
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win32/ka/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: 94AD2CFE7F40220A0646510EB820C8E01BF1745FAAA106FFB4769C0EF75DF13D
  ProductCode: Mozilla Thunderbird 157.0.1 (x86 ka)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win64/ka/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: 33835CE9135540A8295ABDB4327864708E85E42A796B79959BBA8309FCCA6D91
  ProductCode: Mozilla Thunderbird 157.0.1 (x64 ka)
ManifestType: installer
ManifestVersion: 1.12.0
