# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SparkLabs.Viscosity
PackageVersion: 1.13.2.1888
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Protocols:
- viscosity
- viscosityserial
FileExtensions:
- conf
- ovpn
- visz
ProductCode: '{CC85567E-DC83-4BB5-AD77-D84514C0D059}_is1'
ReleaseDate: 2026-10-01
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://swupdate.sparklabs.com/download/win/release/viscosity/Viscosity%20Installer%201.13.2.exe
  InstallerSha256: 64640C7AD2EF7B945EBDF12F0E79DD81D080492B774E6D47295EA6B1EAAE4895
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
      MinimumVersion: 14.51.36247.0
- Architecture: arm64
  InstallerUrl: https://swupdate.sparklabs.com/download/win/release/viscosity/Viscosity%20Installer%201.13.2.exe
  InstallerSha256: 64640C7AD2EF7B945EBDF12F0E79DD81D080492B774E6D47295EA6B1EAAE4895
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
      MinimumVersion: 14.51.36247.0
ManifestType: installer
ManifestVersion: 1.12.0
