# Automatically updated by the winget bot at 2026/Oct/08
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Floweb.Floweb
PackageVersion: 2.0.9
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Floweb
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://download.once.work/Floweb_latest_x64-setup.exe
  InstallerSha256: 5A5EC717A18B758EAF06C6B620D7D826F1E7330E5EB3B98848EE7616A2EB392A
ManifestType: installer
ManifestVersion: 1.28.0
