# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.116.1
InstallerLocale: en-US
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nu
ReleaseDate: 2026-10-04
InstallationMetadata:
  DefaultInstallLocation: nu
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.116.1/nu-0.116.1-x86_64-pc-windows-msvc.msi
  InstallerSha256: 7DA310B0C49F6CA635C32F9B3A4B48B7C6D31FC8B92DDCB7B8428F5D5FC4EF30
  InstallerSwitches:
    Custom: ALLUSERS=2 MSIINSTALLPERUSER=1
  ProductCode: '{F40786E3-5677-4FA2-95B4-0F9A25A4354E}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{F40786E3-5677-4FA2-95B4-0F9A25A4354E}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.116.1/nu-0.116.1-x86_64-pc-windows-msvc.msi
  InstallerSha256: 7DA310B0C49F6CA635C32F9B3A4B48B7C6D31FC8B92DDCB7B8428F5D5FC4EF30
  InstallerSwitches:
    Custom: ALLUSERS=1
  ProductCode: '{F40786E3-5677-4FA2-95B4-0F9A25A4354E}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{F40786E3-5677-4FA2-95B4-0F9A25A4354E}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.116.1/nu-0.116.1-aarch64-pc-windows-msvc.msi
  InstallerSha256: 7A3D688A0C4574E3BA0CB70EF0AAFD9A014A386BB8268595655A52F0D525A2F4
  InstallerSwitches:
    Custom: ALLUSERS=2 MSIINSTALLPERUSER=1
  ProductCode: '{18853D0E-4A0A-45E4-A18B-489E6E2D799D}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{18853D0E-4A0A-45E4-A18B-489E6E2D799D}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.116.1/nu-0.116.1-aarch64-pc-windows-msvc.msi
  InstallerSha256: 7A3D688A0C4574E3BA0CB70EF0AAFD9A014A386BB8268595655A52F0D525A2F4
  InstallerSwitches:
    Custom: ALLUSERS=1
  ProductCode: '{18853D0E-4A0A-45E4-A18B-489E6E2D799D}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{18853D0E-4A0A-45E4-A18B-489E6E2D799D}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
ManifestType: installer
ManifestVersion: 1.12.0
