# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ggml.llamacpp
PackageVersion: b11490
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: llama-batched-bench.exe
- RelativeFilePath: llama-bench.exe
- RelativeFilePath: llama-cli.exe
- RelativeFilePath: llama-gguf-split.exe
- RelativeFilePath: llama-imatrix.exe
- RelativeFilePath: llama-mtmd-cli.exe
- RelativeFilePath: llama-perplexity.exe
- RelativeFilePath: llama-quantize.exe
- RelativeFilePath: llama-server.exe
- RelativeFilePath: llama-tokenize.exe
- RelativeFilePath: llama-tts.exe
ReleaseDate: 2026-10-08
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ggml-org/llama.cpp/releases/download/b11490/llama-b11490-bin-win-vulkan-x64.zip
  InstallerSha256: 99CD7F7CA3E9DE328026C5330B8FF92941103911B15DF4D721EE9FD61055919D
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/ggml-org/llama.cpp/releases/download/b11490/llama-b11490-bin-win-vulkan-arm64.zip
  InstallerSha256: A7127B79B582978105500C008347B03DE621A2BF2A61B258DAFCFE6B425537B7
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
