# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Kitware.CMake
PackageVersion: 4.4.4
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cmake-4.4.4-windows-i386/bin/cmake-gui.exe
    PortableCommandAlias: cmake-gui
  - RelativeFilePath: cmake-4.4.4-windows-i386/bin/cmake.exe
    PortableCommandAlias: cmake
  - RelativeFilePath: cmake-4.4.4-windows-i386/bin/cpack.exe
    PortableCommandAlias: cpack
  - RelativeFilePath: cmake-4.4.4-windows-i386/bin/ctest.exe
    PortableCommandAlias: ctest
  InstallerUrl: https://github.com/Kitware/CMake/releases/download/v4.4.4/cmake-4.4.4-windows-i386.zip
  InstallerSha256: 1A791472619AE85ABF95E3F52838B746A47542EC731A288ABAC2FEE8154D5664
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cmake-4.4.4-windows-x86_64/bin/cmake-gui.exe
    PortableCommandAlias: cmake-gui
  - RelativeFilePath: cmake-4.4.4-windows-x86_64/bin/cmake.exe
    PortableCommandAlias: cmake
  - RelativeFilePath: cmake-4.4.4-windows-x86_64/bin/cpack.exe
    PortableCommandAlias: cpack
  - RelativeFilePath: cmake-4.4.4-windows-x86_64/bin/ctest.exe
    PortableCommandAlias: ctest
  InstallerUrl: https://github.com/Kitware/CMake/releases/download/v4.4.4/cmake-4.4.4-windows-x86_64.zip
  InstallerSha256: BACE36E94B31C68AB6FA295F26DFA11219E0701CF7C94B0284A7D1CB13DAC536
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cmake-4.4.4-windows-arm64/bin/cmake-gui.exe
    PortableCommandAlias: cmake-gui
  - RelativeFilePath: cmake-4.4.4-windows-arm64/bin/cmake.exe
    PortableCommandAlias: cmake
  - RelativeFilePath: cmake-4.4.4-windows-arm64/bin/cpack.exe
    PortableCommandAlias: cpack
  - RelativeFilePath: cmake-4.4.4-windows-arm64/bin/ctest.exe
    PortableCommandAlias: ctest
  InstallerUrl: https://github.com/Kitware/CMake/releases/download/v4.4.4/cmake-4.4.4-windows-arm64.zip
  InstallerSha256: ED673BBC4EB7C1E59B0407FD52F1680FC0AE3229A46B9B7B3EA9133764F07F67
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/Kitware/CMake/releases/download/v4.4.4/cmake-4.4.4-windows-i386.msi
  InstallerSha256: 024A2AFBC59A145081E3C68FA8C916FC130DE30E8782F5B897E05946182C1199
  InstallerSwitches:
    InstallLocation: INSTALL_ROOT="<INSTALLPATH>"
    Custom: ADD_CMAKE_TO_PATH=System
  ProductCode: '{CB23E09B-5373-47E0-9883-510564DD5603}'
  AppsAndFeaturesEntries:
  - ProductCode: '{CB23E09B-5373-47E0-9883-510564DD5603}'
    UpgradeCode: '{8FFD1D72-B7F1-11E2-8EE5-00238BCA4991}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/./CMake'
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/Kitware/CMake/releases/download/v4.4.4/cmake-4.4.4-windows-x86_64.msi
  InstallerSha256: F7AAC962E8EEA82C0A1C603BB11EE3514806A43A35147D5B1E9D69926FFD7D7E
  InstallerSwitches:
    InstallLocation: INSTALL_ROOT="<INSTALLPATH>"
    Custom: ADD_CMAKE_TO_PATH=System
  ProductCode: '{0DEA00BE-9AC0-4348-839D-8EFDCCBD3205}'
  AppsAndFeaturesEntries:
  - ProductCode: '{0DEA00BE-9AC0-4348-839D-8EFDCCBD3205}'
    UpgradeCode: '{8FFD1D72-B7F1-11E2-8EE5-00238BCA4991}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/./CMake'
- InstallerLocale: en-US
  Architecture: arm64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/Kitware/CMake/releases/download/v4.4.4/cmake-4.4.4-windows-arm64.msi
  InstallerSha256: FA7B42F30E0F941F253A6501D9421ECB7656AC311A74975E0A11CAC73067C487
  InstallerSwitches:
    InstallLocation: INSTALL_ROOT="<INSTALLPATH>"
    Custom: ADD_CMAKE_TO_PATH=System
  ProductCode: '{27A3BDFF-6499-4C43-AC9E-9166AF452743}'
  AppsAndFeaturesEntries:
  - ProductCode: '{27A3BDFF-6499-4C43-AC9E-9166AF452743}'
    UpgradeCode: '{8FFD1D72-B7F1-11E2-8EE5-00238BCA4991}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/./CMake'
ManifestType: installer
ManifestVersion: 1.12.0
