# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.631.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.631.0&arch=x86
  InstallerSha256: 28EC1E0B6D7B8E3F9FE8373D6B16E6363B42888996ED1C2DDB6144896C0D5C84
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.631.0&arch=amd64
  InstallerSha256: 887A52EB1F7B15BE1AFFC9A849271E3065A453B7D5BE83035E1344443D0003E2
ManifestType: installer
ManifestVersion: 1.28.0
