# Automatically updated by the winget bot at 2024/Oct/16
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Jidifudi.GT4T
PackageVersion: 8.47.241015
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://gt4t.net/apps/gt4t_win_32_bit/GT4T_setup.exe
  InstallerSha256: 03DDEA988F133F3F385C666D716E46301F7600055973FBA1AF69662A81DF5D44
  ProductCode: '{8EC2D6A4-7B61-4737-8DA2-B6D4339EE744}_is1'
- Architecture: x64
  InstallerUrl: https://gt4t.net/apps/gt4t_win_64_bit/GT4T_setup.exe
  InstallerSha256: FFCCAEC507426134710E1B42288C07F304F07AE61FBEF8529CEDE09DB96597CC
  ProductCode: '{8EC2D6A4-7B61-4737-8DA2-B6D4339EE744}_is1'
- InstallerLocale: zh-CN
  Architecture: x86
  InstallerUrl: https://dl.gt4t.cn/downloads/apps/gt4t_win_32_bit/GT4T_setup.exe
  InstallerSha256: 03DDEA988F133F3F385C666D716E46301F7600055973FBA1AF69662A81DF5D44
  ProductCode: '{8EC2D6A4-7B61-4737-8DA2-B6D4339EE744}_is1'
- InstallerLocale: zh-CN
  Architecture: x64
  InstallerUrl: https://dl.gt4t.cn/downloads/apps/gt4t_win_64_bit/GT4T_setup.exe
  InstallerSha256: FFCCAEC507426134710E1B42288C07F304F07AE61FBEF8529CEDE09DB96597CC
  ProductCode: '{8EC2D6A4-7B61-4737-8DA2-B6D4339EE744}_is1'
ManifestType: installer
ManifestVersion: 1.5.0
