# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RiverScript.RiverScript
PackageVersion: 1.3.0
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.riverscript.com/releases/v1.3.0/riverscript_1.3.0_x64-setup.exe
  InstallerSha256: 048D69EE76E18C91613EA1B206CB5AE9048EF821774440201C3B241237463EDB
ManifestType: installer
ManifestVersion: 1.12.0
