# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FunRoutine.WorkFlowy
PackageVersion: 4.3.2610061056
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- workflowy
ProductCode: 338bed7b-1324-505d-8cb6-5c266cbaa6b3
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/workflowy/desktop/releases/download/v4.3.2610061056/WorkFlowy-Installer-4.3.2610061056.exe
  InstallerSha256: 06A4E54C4EA91CA9AD1EC6E4CEE8B70A3E18EB13462F6F77BF6541889FFB694D
- Architecture: x64
  InstallerUrl: https://github.com/workflowy/desktop/releases/download/v4.3.2610061056/WorkFlowy-Installer-4.3.2610061056.exe
  InstallerSha256: 06A4E54C4EA91CA9AD1EC6E4CEE8B70A3E18EB13462F6F77BF6541889FFB694D
ManifestType: installer
ManifestVersion: 1.12.0
