# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: osyka-yuri.RenderPilot
PackageVersion: 1.15.0
InstallerType: nullsoft
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/osyka-yuri/renderpilot/releases/download/v1.15.0/RenderPilot_1.15.0_x64-setup.exe
  InstallerSha256: E25CC3EBDBEBDE2B4E2CCA3981C8F1F29E7DDBC41FBF859AA24ABF87EA7B7D92
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/osyka-yuri/renderpilot/releases/download/v1.15.0/RenderPilot_1.15.0_x64-setup.exe
  InstallerSha256: E25CC3EBDBEBDE2B4E2CCA3981C8F1F29E7DDBC41FBF859AA24ABF87EA7B7D92
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-04
