# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: dprint.dprint
PackageVersion: 0.60.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dprint.exe
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dprint/dprint/releases/download/0.60.0/dprint-x86_64-pc-windows-msvc.zip
  InstallerSha256: 9A5D46A93EA87DB2BB7BF9431AFF10B01E83210AD37B574EECAE604199A1071A
- Architecture: arm64
  InstallerUrl: https://github.com/dprint/dprint/releases/download/0.60.0/dprint-aarch64-pc-windows-msvc.zip
  InstallerSha256: ED146E34D2AB6DFF514114195B9C896613AC7C0B8E56F77231B1667620FB6BFD
ManifestType: installer
ManifestVersion: 1.28.0
