# Automatically updated by the winget bot at 2026/Oct/03
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Softplicity.TotalThunderbirdConverter
PackageVersion: 5.1.0.49
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Total Thunderbird Converter_is1
ReleaseDate: 2025-10-21
AppsAndFeaturesEntries:
- ProductCode: Total Thunderbird Converter_is1
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://www.coolutils.com/Downloads/TotalThunderbirdConverter.exe
  InstallerSha256: 685C967EA1755598C1C8199B1D41638DB7F515F02E7CF58432F6B50F6359DD66
ManifestType: installer
ManifestVersion: 1.28.0
