# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GeoGebra.CASCalculator
PackageVersion: 6.0.931
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
FileExtensions:
- ggb
ProductCode: GeoGebra_CAS
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://download.geogebra.org/installers/6.0/cas/GeoGebraCAS-Windows-Installer-6-0-931-2.exe
  InstallerSha256: 312AEBF1DB1E5BB390DA33E33D6D32C16A47F3A46FAD01E1E5CBC57B9984B528
ManifestType: installer
ManifestVersion: 1.12.0
