# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 155.1.99.7
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-10-02
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.7/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 5F1B966B32747DDCCC7D16AF84F1EE177475D84EC1AAD4F8C13D14A8E866FC33
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.7/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 8514F0F92A510ADEE95CFCF221A952D24A98EC5EE790CA98F677FA6762BF165E
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.7/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 18EFDCB6D5EEA4DEA0C45DAC7248A6A49A7ADBFC52FD59C4CD9F31A86BB3E3B6
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.7/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: 37044225EA261798186BA7AA3C27D51A2CDDB03C00A267F8917F5F48D988C295
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.7/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: F75D03E3D75F892509926F362079069054056A70584101F5A2E9F636F6725112
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.7/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: 6F8289AF930517F8173011A1B7578CB03B432C129E4E47E3ED4C1A201FA16B72
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
