# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AwesomeDog.soma
PackageVersion: 0.10.3
InstallerType: portable
Commands:
- soma
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AwesomeDog/soma/releases/download/v0.10.3/soma-windows-x64.exe
  InstallerSha256: 6F1434ED2C36D5CF849ECA4AB324C3A6582DF10B98B91825069CBA9011D2D890
ManifestType: installer
ManifestVersion: 1.12.0
