# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BrowserOS.BrowserClawServer
PackageVersion: 0.0.65
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: resources\bin\browseros-claw-server.exe
Commands:
- browseros-claw-server
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/browseros-ai/BrowserOS/releases/download/claw-server/v0.0.65/browseros-claw-server-rust-resources-windows-x64.zip
  InstallerSha256: F103D61AE8F3F8A51FFBC833F4C86BBF61231144C05B67B8E280847004EBDBC3
ManifestType: installer
ManifestVersion: 1.12.0
