# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Yealink.YealinkUSBConnect
PackageVersion: 4.42.11.0
PackageLocale: en-US
Publisher: Yealink
PublisherUrl: https://www.yealink.com/
PrivacyUrl: https://www.yealink.com/en/onepage/privacy-statement
Author: Yealink Network Technology Co., Ltd.
PackageName: Yealink USB Connect
PackageUrl: https://www.yealink.com/en/product-detail/usb-connect-management
License: Proprietary
LicenseUrl: https://www.yealink.com/en/onepage/yealink-end-user-license-agreement
Copyright: Copyright © 2017-2026 Yealink, Inc. All Rights Reserved.
ShortDescription: Personalize and manage your Yealink headsets, webcams and speakerphones
Moniker: yealinkusb
Tags:
- yealink
ReleaseNotes: |-
  Based on the previous software version, problems that might lead to false alarms in the software have been fixed.
  1. YUC adds support for Windows x64 architecture.
  2. Optimized the upgrade logic for YMCS and YUC.
  3. Added configuration support for low battery notification thresholds for BH70 and BH74 headphones. Also optimized battery display and notification switching functions.
  4. Added support for Bluetooth PIN code pairing for specified models.
  5. Fixed the issue of unclear German text expression, improving overall accuracy and readability.
Documentations:
- DocumentLabel: Resources
  DocumentUrl: https://www.yealink.com/en/product-resource/usb-connect-management
ManifestType: defaultLocale
ManifestVersion: 1.12.0
