# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: doggy8088.Carnac
PackageVersion: 2.5.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{DB5C24A2-1558-4272-8C3C-676D68A1E405}_is1'
AppsAndFeaturesEntries:
- DisplayName: Carnac
  Publisher: doggy8088
  ProductCode: '{DB5C24A2-1558-4272-8C3C-676D68A1E405}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/doggy8088/carnac/releases/download/v2.5.0/Carnac-2.5.0-Setup.exe
  InstallerSha256: 3A6BCA037955F764AE725AC2A8F27ED1B368F20E02D15EE094F0A57E924DD55A
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-10
