# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Canva.Cavalry
PackageVersion: 2.8.0
PackageLocale: en-US
Publisher: Scene Group Ltd.
PublisherUrl: https://cavalry.studio/
PublisherSupportUrl: https://cavalry.studio/support/
Author: Scene Group Ltd.
PackageName: Cavalry
PackageUrl: https://cavalry.studio/
License: Proprietary
Copyright: © 2026 Scene Group Ltd.
ShortDescription: Professional, real-time animation software.
Description: Cavalry is a powerful 2D Animation software for macOS and Windows making waves in the worlds of animation, motion design, creative coding, film, generative art, data visualisation, experiential and advertising.
Tags:
- animation
ReleaseNotes: |-
  New Features
  General
  - MCP - Automate repetitive tasks in Cavalry by giving natural language instructions to an AI assistant.
  - Canva Sheets support for the Spreadsheet Utility.
  - AI Studio Window - Harness the power of AI to assist in video Background Removal, Vector Generation and splitting images into Layers.
  - Affinity (.af) file asset support.
  Shapes
  - Metaballs Shape - Combine multiple Shapes into an organic blob.
  Utilities
  - Custom Dropdown - Create custom dropdowns which can be used to set properties including color, alignment and text from a fixed selection of custom, defined options.
  Effects
  - Lighting Filter - Add contact shadows and point lights to Shapes to create long shadows.
  - Twist Filter - Rotate a Shape's materials around a centre point.
  - Ripple Filter - Distort a Shape's materials using linear, concentric or spiral wave patterns.
  - Curves Filter - Color correct the RGB, alpha and hue/saturation components of a Layer with editable curves.
  Scripting
  API
  - getMagicEasing
  - loadCanvaSheet
  - replaceCanvaSheet
  - getCanvaSheetAssetURL
  - isCanvaSheetAsset
  - controlCentreSetLayout
  Cavalry
  - getMaterialAtIndex
  Script UIs
  - SegmentedControl
  Enhancements
  - A new Posterize Time attribute for Shapes (Advanced tab).
  - The Sound Behaviour has been rewritten along with some bug fixes and improvements. Note that legacy scenes will continue to use the legacy Sound Behaviour.
  - SVG import now supports:
    - Gradients (Linear, Radial and Sweep).
    - Opacity.
    - Text.
    - Clipping Masks.
  - Reordering and grouping in the Control Centre.
  - Favourites can now be set for Font inputs.
  - Performance improvements for video playback.
  - Performance improvements for audio playback.
  - New Output Channels option for Audio Settings Viewport options.
  - Several updates to the Graph Editor including:
    - When the Graph Editor is in an empty state, instructions are added to the window on how to load keyframes/animation curves.
    - New Snap to Keyframes and to Snap to Whole Numbers options have been added to the Snapping settings.
    - It's now possible to use a lasso to select keyframes. Hold Option/Alt and click + drag in an empty part of the window.
    - A new Continue mode for the Looping > Loop Before/After menu items.
    - New Loop Settings... including Limit Loops and Filter Last Keyframes.
    - Option/Alt + double click an animation curve opens the new Loop Settings... popover window.
    - New Auto-Bézier, Stepped Next, Plateau, Spline and Clamped modes for the Interpolation options.
    - The footer has been updated to include more Interpolation options.
    - Hovering a keyframe will now reveal a tooltip containing its respective values.
    - New Buffer options added to the footer.
    - It's now possible to select a bézier handle and hit the Delete key to set its length to 0 (remove it). Note this is in addition to clicking a handle while holding the X key.
    - The Reverse Animation command has been added to the right click menu.
  - Several updates to the Time Editor including:
    - The Timeline now pans to follow the playhead if it moves beyond the bounds of the view.
    - The Reverse Animation command has been added to right click menu.
    - Animation Curves and Keyframes can now be aligned to the playhead. Select one or more animation curves and use the align tools, holding Option/Alt for keyframes, to align the animation to the current time.
    - Any part of a child layer's visibility clip that exceeds the duration of its parent is now dimmed. This is to reflect the fact that it inherits its parent's visibility and so will be hidden when the parent is not visible.
  - It's now possible to drag the vertical line part of the Playhead UI. Click within 5px of the line and drag to move it. If a keyframe or Layer is within that same threshold, that keyframe or Layer will take selection precedence.
  - Morph has been rewritten. Legacy Scene files will continue to use the previous version so can/should be manually upgraded.
  - Tapered Strokes can now be defined by a graph and the Stroke Width tool.
  - The Text Shape now includes a Justify All Lines option to support manual line breaks.
  - Render Manager improvements:
    - Render Queue Items can now be reordered via drag and drop.
    - New options to Delete, Expand and Collapse all Render Queue Items.
    - New per-Render Queue Item progress bars.
    - Actions such as Expand/Collapse/Delete now affect all selected Render Queue Items.
  - The connection popover rows have a new 'pill' style UI.
  - When running scripts from the Scripts menu for the first time, a malicious code check is now run.
  - The Isolines Shape has been extended to support Shaders and improve smoothing.
  - Multisample anti-aliasing (MSAA) is now supported on Windows. This has introduced some changes to the way this is handled via the Viewport settings.
  - Updates to .gif export including improved color table generation and dithering options.
  - Editing the Velocity Curve of a Motion Path in the Viewport has been improved.
  - The Text Shape's String input now supports alignment and can be resized.
  Notable Bug Fixes
  - Very quickly deleting consecutive Deformers/Filters via a connection popover no longer triggers a crash.
  - The SkSL Filter supports Mattes.
  - The Project palette in the Color Window is now disabled if a Project is not set.
  - Fixed an issue meaning open paths with bounding boxes below an area of 65536 px^2 (e.g. 256x256 px) were automatically switched to Multi-Sample Anti-Aliasing (MSAA) if Viewport Quality was set to High.
  - Inverted rotations for the Rubber Hose Limb have been corrected. Note that if this issue was being worked around via Attribute Expressions (*-1), they should be removed.
  - An array written in JavaScript containing 3 entries now correctly passes values to a Value3.
  - Duplicating a Composition which contains a muted Attribute no longer causes a crash.
  - The Time Editor's zoom is no longer reset when changing the Frame Range of a Composition.
  - Setting a Shader's Scale to 0 no longer hides all other Shaders.
  - A Gradient's color stop's alpha value is now retained when closing and reopening its popover window.
  - An over-optimisation meaning updates to a Shape with a connected Flatten Shape Layers were not instant has been resolved.
  - An animating Lattice Deformer is now supported in a Pre-Comp.
  - When double clicking the Default layer in the Keyframe Layers window, the layer highlights green as expected.
  - The Composition Boundary Viewport settings window now has the correct title.
  - The Graph Editor now correctly represents integer attributes along bézier curves.
  - A colour space bug affecting .mp4 exports has been resolved. This was a very specific case where RGB→YUV was being converted with the BT.601 matrix but tagging the stream BT.709. There have been various reports of colour shifts via .mp4 so we're hopeful this may resolve some/many of those cases.
  - When a Kinematic Hybrid body's animation ends, it now transitions into the Forge Dynamics simulation in a more natural way.
  - A significant colour shift when enabling Color Management for certain colours has been resolved.
  - An issue meaning very long Layer names could result in blocking the disconnect UI in a connection popover has been resolved.
  - An imported font Asset is now correctly marked as 'in use' in the Assets Window.
  - An issue resulting in 'ghost' layers in a Shape's Fill tab when using the Option/Alt key to create multiple connections has been resolved.
  - Where a Shape has been connected to a Group as a Clipping Mask, Feather now works as expected.
  - Non period (fullstop) characters (e.g. U+2019 RIGHT SINGLE QUOTATION MARK) are now correctly respected by the Change String Case String Manipulator.
  - Style Behaviours now correctly respect the 'last' token when hard line breaks are introduced via a Formatted String String Generator.
  - An issue resulting in changes to rich text styling when Avoid Orphans was checked has been resolved.
  - A crash in ui.Draw has been fixed.
  - ui.List items no longer 'stretch' to fill their container.
  - An issue meaning very long (30mins +) ProRes renders were failing on Windows has been resolved.
  - An issue meaning a ProRes 4444 file which includes an alpha channel but where there is no alpha on the first frame would not import to After Effects has been resolved.
  Notes
  - The CLI is not available in Cavalry 2.8.0 so if you are using this feature, please remain on your current version. We are working towards reinstating this for future versions.
  Known Issues
  If an AI Pass is purchased, a restart of Cavalry is required for it to be detected.
ReleaseNotesUrl: https://cavalry.studio/docs/tech-info/release-notes/2.8/2-8-0-release-notes/
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://cavalry.studio/docs/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
