# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anthropic.Claude
PackageVersion: 2.9939.4
Protocols:
- claude
ReleaseDate: 2026-09-28
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.9939.4/Claude-a166d8a7c640e65ad825ebfb99d74ccbb9c8940d.msix
  InstallerSha256: AF79B61510F69C125750C3AF5F38D7101F79B4785CDA1462ADC3F45AC584D2FA
  SignatureSha256: 56E27A582BF350674EC1FDB3BE3C499649272BED5D3188DF74D0A5878795EE7A
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.9939.4/Claude-a166d8a7c640e65ad825ebfb99d74ccbb9c8940d.msix
  InstallerSha256: 069EEBE9FF84D8494C9B6DF62A4ACA569FB3BA21C3D7748871CFFA3FCD659EE2
  SignatureSha256: C13F0B9C4986D5083A53543FE9256B314B2D31F34873FD6B268B0A4F3D093455
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.9939.4/Claude-a166d8a7c640e65ad825ebfb99d74ccbb9c8940d.exe
  InstallerSha256: B233F34379ED8E9CED2C765D29AECFD35ED4D773BCF12CF5A7BB588825170590
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.9939.4/Claude-a166d8a7c640e65ad825ebfb99d74ccbb9c8940d.exe
  InstallerSha256: 0BC513C6DA9B22A8D6655F443C15A45DA1CF5D7DEE6F1BE2014DC4069B2FFF8B
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
ManifestType: installer
ManifestVersion: 1.12.0
