# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sakana-yuyu.cursor-byok
PackageVersion: 1.0.12
InstallerType: nullsoft
Scope: machine
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Sakana-yuyu/cursor-byok/releases/download/v1.0.12/cursor-byok-1.0.12-windows-x32-installer.exe
  InstallerSha256: A0384AEBAB28F1A28BDEB1378FD60E848B54EC7FBBDD0AE71053B613B1E48720
  ProductCode: SakanaCursoråŠ©æ‰‹
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Sakana\CursoråŠ©æ‰‹'
- Architecture: x64
  InstallerUrl: https://github.com/Sakana-yuyu/cursor-byok/releases/download/v1.0.12/cursor-byok-1.0.12-windows-x64-installer.exe
  InstallerSha256: B9C117627C069AC2F3E251FD5A1AC8E183157A688AFA6DDE9CAD33225A3A3857
  ProductCode: SakanaCursor助手
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Sakana\Cursor助手'
- Architecture: arm64
  InstallerUrl: https://github.com/Sakana-yuyu/cursor-byok/releases/download/v1.0.12/cursor-byok-1.0.12-windows-arm64-installer.exe
  InstallerSha256: 89F1678CBA303E76A20FF7F48AC514F272687D73CD9D40B2934253EDE11614EE
  ProductCode: SakanaCursor助手
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Sakana\Cursor助手'
ManifestType: installer
ManifestVersion: 1.12.0
