# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: IcyHotY2K.QuickImageViewer
PackageVersion: 3.2.0.451
InstallerType: portable
Commands:
- qiv
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/icyhoty2k/QuickImageViewer/releases/download/v3.2.0.451/QuickImageViewer.exe
  InstallerSha256: 6F34ECA858FC0AA3A225C6FE3BB24FE869829809CBAE1AD4165396F07E48028B
ManifestType: installer
ManifestVersion: 1.12.0
