# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: EnineApps.GreenDotter
PackageVersion: 2.9.1
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://green-dotter.com/download/windows/2.9.1
    InstallerSha256: 07D5100FFB5A253B4DA1E269882B43340039158B71459768632AEA0325F8D52A
ManifestType: installer
ManifestVersion: 1.6.0
