# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: yt-dlp.FFmpeg.Shared
PackageVersion: N-127014-g18ee27e67b-20260930
InstallerType: zip
NestedInstallerType: portable
Commands:
- ffmpeg
- ffplay
- ffprobe
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win32-gpl-shared/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win32-gpl-shared/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win32-gpl-shared/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2026-09-30-00-16/ffmpeg-N-127014-g18ee27e67b-win32-gpl-shared.zip
  InstallerSha256: A74F3C668EC865C0376E97ABB9892422ACB848012116461B5381AC9381F5B13B
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win64-gpl-shared/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win64-gpl-shared/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-win64-gpl-shared/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2026-09-30-00-16/ffmpeg-N-127014-g18ee27e67b-win64-gpl-shared.zip
  InstallerSha256: 2EDE31FB01A3D19D065E497052A94A7454209F6F0228FB979C51EC136E4F79D0
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-winarm64-gpl-shared/bin/ffmpeg.exe
    PortableCommandAlias: ffmpeg
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-winarm64-gpl-shared/bin/ffplay.exe
    PortableCommandAlias: ffplay
  - RelativeFilePath: ffmpeg-N-127014-g18ee27e67b-winarm64-gpl-shared/bin/ffprobe.exe
    PortableCommandAlias: ffprobe
  InstallerUrl: https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2026-09-30-00-16/ffmpeg-N-127014-g18ee27e67b-winarm64-gpl-shared.zip
  InstallerSha256: E56C00B2858CF573BF888D8C5DEC74F83814A252C0927F8AA37AA5FF226BC279
ManifestType: installer
ManifestVersion: 1.28.0
