# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: dotenvx.dotenvx
PackageVersion: 2.32.3
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dotenvx.exe
  PortableCommandAlias: dotenvx
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/dotenvx/dotenvx/releases/download/v2.32.3/dotenvx-2.32.3-windows-x86_64.zip
  InstallerSha256: CFCCBBC01B10C183FA84E5F3F41FB5ACD5758B28323E444C294C8DB37C10199F
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
