# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: Zen-Team.Zen-Browser
PackageVersion: 1.23.2b
PackageLocale: en-US
Publisher: Zen OSS Team
PublisherUrl: https://zen-browser.app/
PublisherSupportUrl: https://github.com/zen-browser/desktop/issues
PrivacyUrl: https://zen-browser.app/privacy-policy/
PackageName: Zen Browser
PackageUrl: https://zen-browser.app/
License: MPL-2.0
LicenseUrl: https://github.com/zen-browser/desktop/blob/HEAD/LICENSE
Copyright: Zen OSS Team
ShortDescription: Zen is the best way to browse the web. Beautifully designed, privacy-focused, and packed with features. We care about your experience, not your data.
Moniker: zen-browser
Tags:
- arc
- arc-browser
- firefox
- firefox-based
- firefox-browser
- gecko
- internet
- web
- web-browser
- zen
ReleaseNotes: |-
  Zen Stable Release

  New Features
  - Added an 'open library' command to the command palette.
  - You can now right-click the media tab in the Library to disable it.

  Fixes
  - Changed session backup file names to use local dates (#15806)
  - Fixed the library getting stuck after opening and closing it quickly (#15833)
  - Fixed blocked/unsafe downloads not having the choice to be opened or saved. (#15809)
  - Fixed moving multiple tabs to new window irrecoverably loses unloaded tabs. (#15810)
  - Fixed the sidebar having too much minimum width when they are aligned to the right. (#15794)
  - Fixed HEIC media being listed in the media tab but do not render correctly. (#15778)
  - Fixed space-assigned bookmarks not being saved anymore. (#12721)
  - Fixed a memory leak issue on startup.
  - Other bug fixes and improvements.
ReleaseNotesUrl: https://zen-browser.app/release-notes/#1.23.2b
Documentations:
- DocumentLabel: About
  DocumentUrl: https://zen-browser.app/about/
- DocumentLabel: Documentation
  DocumentUrl: https://docs.zen-browser.app/
ManifestType: defaultLocale
ManifestVersion: 1.28.0
