# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: UnslothAI.Unsloth
PackageVersion: 0.1.903-beta
InstallerType: nullsoft
Scope: user
Protocols:
- unsloth
ProductCode: Unsloth Studio (Desktop)
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/unslothai/unsloth/releases/download/v0.1.903-beta/Unsloth-Desktop-Windows.exe
  InstallerSha256: 8EE9D4FAE715372D7F336F2F4B39F66D3D11D79393D57D156A1B95C1A8DA5A4C
- Architecture: arm64
  InstallerUrl: https://github.com/unslothai/unsloth/releases/download/v0.1.903-beta/Unsloth-Desktop-Windows-ARM64.exe
  InstallerSha256: 4F97849F76CADFF7A0CC2C096412A5DCEA625A88C5FA1A8F96563E78ABBFB462
ManifestType: installer
ManifestVersion: 1.12.0
