# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tenable.Nessus
PackageVersion: 10.12.5.20057
InstallerType: msi
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{4ADB8B5A-D3F4-49F5-AA66-E56A53B8A9B5}'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- UpgradeCode: '{84AA79F7-42E3-4728-9637-04E73579B0CE}'
Installers:
- Architecture: x64
  InstallerUrl: https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.12.5-x64.msi
  InstallerSha256: A5D52DCF9DFD00EE9A5F164AD77D97E5D4D78E2BCD5D62E6DE0D57AF0F0B9745
ManifestType: installer
ManifestVersion: 1.12.0
