# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AurelioAvila.Redaxa
PackageVersion: 0.4.9
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
ProductCode: Redaxa
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- ProductCode: Redaxa
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Redaxa'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AurelioAvila/redaxa/releases/download/v0.4.9/Redaxa_0.4.9_x64-setup.exe
  InstallerSha256: 347C50B59C5534DB2A685C0B4F3001F7B3607045D83B0C65482AA7520BC728A2
ManifestType: installer
ManifestVersion: 1.12.0
