# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CoralCreek.SQLiteExpert.Professional
PackageVersion: 6.2.5.739
InstallerType: inno
Scope: machine
ReleaseDate: 2026-10-03
Installers:
- Architecture: x86
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertProSetup32.exe
  InstallerSha256: AA894D8A04FC385C681E93F91F03BF4050D54E7701116D16D1878FDE31591FE9
  ProductCode: SQLite Expert Professional 6 - 32bit_is1
- Architecture: x64
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertProSetup64.exe
  InstallerSha256: D51187F0C9F7E9B3CF5D5D570185D58E2DD34516DCEDFA1BB8D24BBE07921EE6
  ProductCode: SQLite Expert Professional 6 - 64bit_is1
ManifestType: installer
ManifestVersion: 1.12.0
