# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: Amazon.SAM-CLI
PackageVersion: 1.168.0
PackageLocale: en-US
Publisher: AWS Serverless Applications
PublisherUrl: https://github.com/aws/aws-sam-cli
PublisherSupportUrl: https://github.com/aws/aws-sam-cli/issues
Author: AWS Serverless Applications
PackageName: AWS SAM Command Line Interface
PackageUrl: https://aws.amazon.com/serverless/sam
License: Apache-2.0
LicenseUrl: https://github.com/aws/aws-sam-cli/blob/HEAD/LICENSE
Copyright: Copyright (c) Amazon.com, Inc. or its affiliates. All Rights Reserved.
CopyrightUrl: https://raw.githubusercontent.com/aws/aws-sam-cli/master/LICENSE
ShortDescription: The AWS Serverless Application Model (SAM) is an open-source framework for building serverless applications.
Moniker: aws-sam-cli
Tags:
- amazon
- aws
- cli
- sam
- serverless
ReleaseNotes: |-
  Changes:
  63a08f4 - chore(deps): bump the boto group across 1 directory with 4 updates (#9311)
  fe65444 - chore(deps): bump the requests group across 1 directory with 3 updates (#9310)
  70aa72c - chore(deps): bump tzdata from 2026.3 to 2026.4 (#9307)
  90a86b5 - chore(deps): bump werkzeug (#9302)
  077acb4 - chore(deps-dev): bump types-dateparser (#9305)
  242848e - chore(deps): bump github/codeql-action from 4.37.9 to 4.38.2 (#9292)
  6ae768f - chore(deps): bump python-slugify (#9301)
  405d82d - chore(deps): bump dateparser from 1.4.2 to 1.4.3 (#9262)
  2fe6b4e - chore: update aws-sam-translator to 1.114.0 (#9314)
  330d8c9 - chore(deps-dev): bump black from 26.5.1 to 26.10.0 (#9322)
  e32c26e - chore(deps): bump python-dotenv from 1.2.3 to 1.2.4 (#9320)
  e3f7579 - chore(deps-dev): bump types-pywin32 (#9319)
  47f1f3d - chore(deps-dev): bump ruff from 0.16.8 to 0.16.10 (#9317)
  b73a020 - chore: bump version to 1.168.0 (#9324)

  Hashes:
  ────────────────────────────────┬────────────────────────────────────────────────────────────────
  Filename                        │SHA256
  ────────────────────────────────┼────────────────────────────────────────────────────────────────
  aws-sam-cli-macos-x86_64.pkg    │961a8dd4a2bd48c681f97775a49ffce0606e09f2a4db7bce6f9f4f8f2979ae6f
  ────────────────────────────────┼────────────────────────────────────────────────────────────────
  aws-sam-cli-macos-arm64.pkg     │f359b1e9acf52aee8a03e6bd88e921c9d14b83fbbd2b961eb3caa6eba42befeb
  ────────────────────────────────┼────────────────────────────────────────────────────────────────
  AWS_SAM_CLI_64_PY3.msi          │4076255659cb78fa047c01aa9e4944f2084f5c6b13ac1edae084776db87293c3
  ────────────────────────────────┼────────────────────────────────────────────────────────────────
  aws-sam-cli-linux-x86_64.zip    │a187e5a4d4a03bb4fa48c9ac97b0829cda3c7582a1b5ae175869608f94d57ad8
  ────────────────────────────────┼────────────────────────────────────────────────────────────────
  aws-sam-cli-linux-x86_64.zip.sig│973f72bc0b16e5fcae991d86b2cc65beaead8f9432eace60df1fbe2f2bc795f4
  ────────────────────────────────┼────────────────────────────────────────────────────────────────
  aws-sam-cli-linux-arm64.zip     │9f1998b902fb1756f80b5dd7c8c1d562831879b5fb778182faad9a806fc9ae83
  ────────────────────────────────┼────────────────────────────────────────────────────────────────
  aws-sam-cli-linux-arm64.zip.sig │639aa1863d75440f704bb565212fba45d36809efa2743f1d83672ad9880a9f4d
  ────────────────────────────────┴────────────────────────────────────────────────────────────────
ReleaseNotesUrl: https://github.com/aws/aws-sam-cli/releases/tag/v1.168.0
Documentations:
- DocumentLabel: Using the AWS SAM CLI
  DocumentUrl: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/using-sam-cli.html
ManifestType: defaultLocale
ManifestVersion: 1.28.0
