# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SmokeTurner.Vouch
PackageVersion: 2026.10.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: vouch.exe
  PortableCommandAlias: vouch
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/vouch-sh/vouch/releases/download/v2026.10.2/vouch-v2026.10.2-x86_64-pc-windows-msvc.zip
  InstallerSha256: 105BC64E89B8636178367200E5EC4C283D5ABA8BED246717C96C8CBD708653C0
- Architecture: arm64
  InstallerUrl: https://github.com/vouch-sh/vouch/releases/download/v2026.10.2/vouch-v2026.10.2-aarch64-pc-windows-msvc.zip
  InstallerSha256: CC544D5090C282468A88164C78AEFB581B372831D0A47645D7BE73F7F543C2C1
ManifestType: installer
ManifestVersion: 1.12.0
