# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.279
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.279/anchors_0.1.279_windows_amd64.zip
  InstallerSha256: 86A642995CE4FA4AE71FA50EF104CCE8E49FEB4A21DB7BA7FFD5967C19034704
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.279/anchors_0.1.279_windows_arm64.zip
  InstallerSha256: 538ECC069549505FE555F86F36D8E8C5485BD055B0FB672CA408F35FFCFE2721
ManifestType: installer
ManifestVersion: 1.12.0
