# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: kangfenmao.CherryStudio
PackageVersion: 2.1.5
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 41a4ccd8-bcc0-5710-9eee-0e164da68057
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v2.1.5/Cherry-Studio-2.1.5-win-x64-setup.exe
  InstallerSha256: A9B23C41B1BD19DD8E88BF527B995E622A3906F14E6D82D71BF26CB0A864BC3F
  InstallerSwitches:
    Custom: /currentuser
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v2.1.5/Cherry-Studio-2.1.5-win-x64-setup.exe
  InstallerSha256: A9B23C41B1BD19DD8E88BF527B995E622A3906F14E6D82D71BF26CB0A864BC3F
  InstallerSwitches:
    Custom: /allusers
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v2.1.5/Cherry-Studio-2.1.5-win-arm64-setup.exe
  InstallerSha256: 385B37A616BFA5209DD089EAF47EC12402FF1C757CC886B30ED71D8BD9FF71ED
  InstallerSwitches:
    Custom: /currentuser
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v2.1.5/Cherry-Studio-2.1.5-win-arm64-setup.exe
  InstallerSha256: 385B37A616BFA5209DD089EAF47EC12402FF1C757CC886B30ED71D8BD9FF71ED
  InstallerSwitches:
    Custom: /allusers
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
