# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.et
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/et/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 083E01D9F8FBF98B25FA9EF2DC8C5B2AAF9B7B31E4C6D80E648280B25C6D3D36
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/et/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 7AC3A8DB38392446E7268CCE37034394138154529532D3CBBC296828BCB45104
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/et/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 46740230DC8E4214D145A331F5B4BA6C34993B4C91195832DBFF368B48F57E35
ManifestType: installer
ManifestVersion: 1.12.0
