# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Oven-sh.Bun.Baseline
PackageVersion: 1.4.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ./bun-windows-x64-baseline/bun.exe
  PortableCommandAlias: bunx
- RelativeFilePath: bun-windows-x64-baseline/bun.exe
  PortableCommandAlias: bun
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/oven-sh/bun/releases/download/bun-v1.4.3/bun-windows-x64-baseline.zip
  InstallerSha256: D7A7D3EB216614544AAB0CDE2D8D9F2E4E87839BF5A30A1CD11D077F02D84E0C
ManifestType: installer
ManifestVersion: 1.28.0
