# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LotusConverter.Lotus1-2-3FileConverter
PackageVersion: 6.2.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- LotusConverter
FileExtensions:
- "123"
- wk1
- wk3
- wk4
- wks
ProductCode: '{1B8A389E-A34F-4794-9C38-1FE9B525964A}'
AppsAndFeaturesEntries:
- DisplayName: Lotus 1-2-3 File Converter
  Publisher: Lotus Converter
  UpgradeCode: '{F8B9F3C7-35B8-4F71-8B5D-E4B39139E71B}'
Installers:
- Architecture: x64
  InstallerUrl: https://lotusconverter.com/download/LotusConverter-6.2.0.msi
  InstallerSha256: 849AE248A18671BCBA43150AC2BF0923BD80C9771DBCD6AEFCEB16ED8FE9018C
ManifestType: installer
ManifestVersion: 1.12.0
