# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Alibaba.QoderCLI.CN
PackageVersion: 1.1.66
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: qoderclicn.exe
  PortableCommandAlias: qodercn
Commands:
- qodercn
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://static.qoder.com.cn/qoder-cli-cn/releases/1.1.66/qoderclicn-windows-x64.zip
  InstallerSha256: 2010601E43EFC63BB7D0FB67712592E7831696157A2BCF204035FB6161E191B5
- Architecture: arm64
  InstallerUrl: https://static.qoder.com.cn/qoder-cli-cn/releases/1.1.66/qoderclicn-windows-arm64.zip
  InstallerSha256: 5B8D8AC37BBA9FB6E745A3D36CF8B2C79895D0EE3CF7DA5DAA0DDB29DF595C4D
ManifestType: installer
ManifestVersion: 1.12.0
