# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: snapetech.slskr
PackageVersion: 0.2.41
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: slskr-v0.2.41-x86_64-pc-windows-msvc\slskr.exe
  PortableCommandAlias: slskr
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/snapetech/slskr/releases/download/release-v0.2.41/slskr-v0.2.41-x86_64-pc-windows-msvc.zip
  InstallerSha256: 1A2B858149BB03016132EE3B58AC9131C63144E19AA394E092F40A59EFB2729C
ManifestType: installer
ManifestVersion: 1.6.0
