# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESEngine.ReasonixCLI
PackageVersion: 2.30.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: reasonix.exe
Commands:
- reasonix
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v2.30.0/reasonix-windows-amd64.zip
  InstallerSha256: 6601ECD484300FB49948D4D0133ACE1C2DB8C3C3FC31F455BC06B03052C954C7
- Architecture: arm64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v2.30.0/reasonix-windows-arm64.zip
  InstallerSha256: 970F662FD34422D39FB6487B817871EB40E7C0A8B65B257AECED06B157886ECA
ManifestType: installer
ManifestVersion: 1.12.0
