# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.nn-NO
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/nn-NO/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 49EB1B70DE70D9CD9F0B438088F2D33A2EB2CEA2916085F7C90A167810CE1EDC
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/nn-NO/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 936FD8074A94AB8D1CD41D3AD883294BC9411B466976CAC8D35C705BDEC6A560
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/nn-NO/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 4AAD56A4733562D3D1C1419DC65F0AFB3534142B2B5E394C79DB0D5AEBB88CFD
ManifestType: installer
ManifestVersion: 1.12.0
