# Created with WinGet Tracker using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Syngnat.GoNavi
PackageVersion: 1.1.0
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: GoNavi.exe
    PortableCommandAlias: GoNavi
  InstallerUrl: https://github.com/Syngnat/GoNavi/releases/download/v1.1.0/GoNavi-1.1.0-Windows-Amd64-Portable.zip
  InstallerSha256: 076D77A990539AEB2026C3D9AC5738DC7CB608F946228347220FFDA45932D8EB
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: GoNavi.exe
    PortableCommandAlias: GoNavi
  InstallerUrl: https://github.com/Syngnat/GoNavi/releases/download/v1.1.0/GoNavi-1.1.0-Windows-Arm64-Portable.zip
  InstallerSha256: 5AF6EBBD5E34B038CA3C4D5356174030DB37DC682701D8772520381CD7D3EEE1
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/Syngnat/GoNavi/releases/download/v1.1.0/GoNavi-1.1.0-Windows-Amd64-Installer.msi
  InstallerSha256: F0B9372E041DC503BAB0918D278A28737ADAADC38A91051625AF083C0858EFC7
  ProductCode: '{925EF015-6117-4313-9516-E28EA8AB7A81}'
  AppsAndFeaturesEntries:
  - ProductCode: '{925EF015-6117-4313-9516-E28EA8AB7A81}'
    UpgradeCode: '{CDD6BF2F-ED1E-4345-A0AB-DCDB7E15FB23}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\.\GoNavi'
- InstallerLocale: en-US
  Architecture: arm64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/Syngnat/GoNavi/releases/download/v1.1.0/GoNavi-1.1.0-Windows-Arm64-Installer.msi
  InstallerSha256: F375601260994CAFA4F46A1162C6677E7C09F0EDB97F04E230B004B6FDD72520
  ProductCode: '{2296DC2D-6F5B-4FE8-9579-60346D8CBC60}'
  AppsAndFeaturesEntries:
  - ProductCode: '{2296DC2D-6F5B-4FE8-9579-60346D8CBC60}'
    UpgradeCode: '{CDD6BF2F-ED1E-4345-A0AB-DCDB7E15FB23}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\.\GoNavi'
ManifestType: installer
ManifestVersion: 1.12.0
