# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: pnpm.pnpm
PackageVersion: 12.11.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pnpm.exe
  PortableCommandAlias: pnpm
Commands:
- pnpm
ReleaseDate: 2026-10-09
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/pnpm/pnpm/releases/download/v12.11.2/pnpm-win32-x64.zip
  InstallerSha256: 66CAC6B725BFC75FADAC959FC435821048558ADB50B89C82D0D2D5E57465A1DD
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/pnpm/pnpm/releases/download/v12.11.2/pnpm-win32-arm64.zip
  InstallerSha256: 550C8167A14C7F25E156C6FD14196CB440C0F05210CCB618AD904DC42DC90F6C
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
