# Created with WinGet Tracker using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AnalyseDeCircuit.OxideTerm
PackageVersion: 2.2.2
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: OxideTerm
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- ProductCode: OxideTerm
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\OxideTerm'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AnalyseDeCircuit/oxideterm/releases/download/v2.2.2/OxideTerm_2.2.2_windows_x64-setup.exe
  InstallerSha256: 5507693CC484BCE3CBB5326EA07ADBA46D32D56F8BFF9482F51EC021118A7DC2
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/AnalyseDeCircuit/oxideterm/releases/download/v2.2.2/OxideTerm_2.2.2_windows_arm64-setup.exe
  InstallerSha256: 6FE82C1B8337CD4BA00B9630D32267A89793D96685DF6F7AE01DB2EF3F5EC928
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
