# Created with Codex App Manager release workflow using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Wangnov.CodexAppManager
PackageVersion: 0.5.15
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
ProductCode: Codex App Manager
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- Publisher: github
  ProductCode: Codex App Manager
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Codex App Manager'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Wangnov/Codex-App-Manager/releases/download/v0.5.15/CodexAppManager_0.5.15_x64-setup.exe
  InstallerSha256: 779DD8D6D2628D33E5B66FB7E71E2FBD6776FD896A1BC6A497E2C120518CBB3B
- Architecture: arm64
  InstallerUrl: https://github.com/Wangnov/Codex-App-Manager/releases/download/v0.5.15/CodexAppManager_0.5.15_arm64-setup.exe
  InstallerSha256: 30448F3238FDB879C8BC994FAE4D032ED3C38AAFA2646945B0C2724C3285BEC7
ManifestType: installer
ManifestVersion: 1.12.0
