# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Mickem.NSClient
PackageVersion: 0.24.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  InstallLocation: INSTALLLOCATION="<INSTALLPATH>"
UpgradeBehavior: install
AppsAndFeaturesEntries:
- UpgradeCode: '{0B36E3B7-0042-452D-B376-57E0C07ADDBB}'
  InstallerType: wix
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mickem/nscp/releases/download/0.24.0/NSCP-0.24.0-x64.msi
  InstallerSha256: 7273946B50C3FF498F112C2F23D7F7A94ABB7FC2E5BC0C5F933F41E08085DECC
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  ProductCode: '{B4BB975B-77CA-45AB-A2FE-1A597E57E2ED}'
- Architecture: x86
  InstallerUrl: https://github.com/mickem/nscp/releases/download/0.24.0/NSCP-0.24.0-Win32.msi
  InstallerSha256: 972D550F5A233338EB4CE32010391FBC92C39FBF8209A282607026467CB82C66
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
  ProductCode: '{09357BA4-5845-40B1-ADB4-1F218353658E}'
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2026-09-30
