# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Macabacus.Macabacus
PackageVersion: 9.9.5
InstallerType: wix
InstallerSwitches:
  InstallLocation: INSTALLLOCATION="<INSTALLPATH>"
ProductCode: '{B6E1E2DB-E3DB-45DB-9B3E-B1E341C9248B}'
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- UpgradeCode: '{B01A9684-FE17-41E3-A9CB-609D7A88D354}'
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.macabacus.com/software/Macabacus-9.9.5.msi
  InstallerSha256: 00AC0EC801F73EFD330E4B12F5151EA3164DEFB213E51D3E881AE7C3F17D50F0
  InstallerSwitches:
    Custom: OFFICE2016FOUND=1 EULA=1
- Architecture: x64
  InstallerUrl: https://downloads.macabacus.com/software/Macabacus-9.9.5.msi
  InstallerSha256: 00AC0EC801F73EFD330E4B12F5151EA3164DEFB213E51D3E881AE7C3F17D50F0
  InstallerSwitches:
    Custom: OFFICE2016X64FOUND=1 EULA=1
ManifestType: installer
ManifestVersion: 1.12.0
