# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1791091069-gb9917f
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1791091069-gb9917f/amp-windows-x64-baseline.exe
  InstallerSha256: 14433B603AFAFFF9AC7D3E4DA48C7773C77D92D04A1DC2F2DA56EC6BA1CA19F4
ManifestType: installer
ManifestVersion: 1.12.0
