# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: JustArchiNET.ArchiSteamFarm
PackageVersion: 6.3.10.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ArchiSteamFarm.exe
UpgradeBehavior: install
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JustArchiNET/ArchiSteamFarm/releases/download/6.3.10.3/ASF-win-x64.zip
  InstallerSha256: BB995268B9DD47E75A837EE0AE603C0632426D33BFF3D67C8FED645FA8767662
- Architecture: arm64
  InstallerUrl: https://github.com/JustArchiNET/ArchiSteamFarm/releases/download/6.3.10.3/ASF-win-arm64.zip
  InstallerSha256: F297D5BABE392E5C3F79F39D26B72EC441C3CFDA65B573539AB914F98CF95C59
ManifestType: installer
ManifestVersion: 1.12.0
