# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CaptainKillSwitch.CaptainKillSwitch
PackageVersion: 0.4.10
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{2AC0048D-543F-4A28-88DB-721C360564E7}'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- Publisher: Captain Kill Switch Team
  ProductCode: '{2AC0048D-543F-4A28-88DB-721C360564E7}'
  UpgradeCode: '{984FC5FB-4BE0-5465-85FF-3FDCFED283B5}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Captain Kill Switch'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/captainkillswitch/downloads/releases/download/v0.4.10/captain-kill-switch-0.4.10-windows-x64.msi
  InstallerSha256: 03845D220DB6C7659920F89B44FC7994889D24CC381194D3538076C956E130A4
ManifestType: installer
ManifestVersion: 1.12.0
