# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: buchen.portfolio
PackageVersion: 0.88.0
PackageLocale: de-DE
Publisher: Andreas Buchen
PublisherUrl: http://abuchen.name
PublisherSupportUrl: https://github.com/buchen/portfolio/issues
PackageName: Portfolio Performance
PackageUrl: https://github.com/buchen/portfolio
License: EPL-1.0
LicenseUrl: https://github.com/buchen/portfolio/blob/master/LICENSE
ShortDescription: Portfolio Performance berechnet die Gesamtperformance Ihres Anlageportfolios.
Tags:
- eclipse
- financial
- investment-portfolio
- java
- portfolio
- portfolio-performance
- stocks
ReleaseNotes: |-
  * Neu: Sifting steht jetzt als Online-Anbieter für historische Kurse zur Verfügung.
  * Neu: PDF-Importer für Alpian, Chase, Fondsdepot Bank, Morgan Stanley, Relai und Swisscard AECS.
  * Neu: Die Listen der Konten, Depots und Sparpläne lassen sich als CSV exportieren.
  * Verbesserung: PDF-Importer für 1822direkt, 3 Banken, Advanzia Bank, Baader Bank, Bison, Consorsbank, DEGIRO, DZ Bank, Hello Bank, HypoVereinsbank, Hypothekarbank Lenzburg, ING-DiBa, LGT Bank, Liberty Vorsorge, Merkur Privatbank, MLP Banking, N26, Norddeutsche Landesbank, Oldenburgische Landesbank, Pictet, Postbank, Questrade, Quirin Privatbank, Schelhammer Capital Bank, Sutor Bank, Swissquote, Tradegate, UBS, Union Investment, V-Bank, Vanguard, VDK Bank, Volksbank, VZ VermögensZentrum, Weberbank und Zürcher Kantonalbank wurden verbessert.
  * Verbesserung: Die Auswahl der Börsenplätze bei Yahoo Finance zeigt jetzt eine Bezeichnung für Kurse des FTSE Global Index (.FGI).
  * Verbesserung: Beim Umwandeln einer Buchung (zum Beispiel eines Kaufs in eine Einlieferung) bleibt die Quelle des Imports jetzt erhalten.
  * Fehlerbehebung: Historische Kurse von AMFI India werden wieder geladen, nachdem der Anbieter sein Datenformat geändert hat.
  * Fehlerbehebung: Yahoo Finance verwendet jetzt das korrekte Börsenkürzel für die saudische Börse (.SR).
  * Fehlerbehebung: Die Kursvorschau für den Anbieter MFAPI wird jetzt aktualisiert, wenn sich der Scheme Code ändert.
  * Fehlerbehebung: Der Hauptbereich mit den Registerkarten lässt sich nicht mehr versehentlich abdocken.
ReleaseNotesUrl: https://github.com/portfolio-performance/portfolio/releases/tag/0.88.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
