# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Docker.DockerCLI
PackageVersion: 29.9.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: docker\docker.exe
  PortableCommandAlias: docker
- RelativeFilePath: docker\dockerd.exe
  PortableCommandAlias: dockerd
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://download.docker.com/win/static/stable/x86_64/docker-29.9.0.zip
  InstallerSha256: E3FF5D2E4CD1AD7E1C9BCB76F0DF28A84853C43416A915323F08659D8487AD83
ManifestType: installer
ManifestVersion: 1.12.0
