# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: BelajarCaraBelajar.Snipset
PackageVersion: 0.6.852
PackageLocale: en-US
Publisher: Belajar Cara Belajar
PublisherUrl: https://snipset.belajarcarabelajar.com/
PublisherSupportUrl: https://snipset.belajarcarabelajar.com/
Author: Iwan Kurniawan
PackageName: Snipset
PackageUrl: https://snipset.belajarcarabelajar.com/
License: Proprietary
LicenseUrl: https://snipset.belajarcarabelajar.com/
Copyright: Copyright 2026 Belajar Cara Belajar. All rights reserved.
ShortDescription: Smart AI-Powered Snippet Manager and Text Expander for desktop
Description: Snipset is an intelligent snippet manager and smart text expander built with Rust and React for high-performance productivity.
Moniker: snipset
Tags:
- productivity
- rust
- snippet
- tauri
- text-expander
ManifestType: defaultLocale
ManifestVersion: 1.12.0
