# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Fluxer.Fluxer
PackageVersion: 2026.1006.171735
InstallerType: exe # Velopack
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --installto "<INSTALLPATH>"
  Log: --log "<LOGPATH>"
UpgradeBehavior: install
ProductCode: fluxer_desktop
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- Publisher: Fluxer Platform AB
  ProductCode: fluxer_desktop
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\fluxer_desktop'
Installers:
- Architecture: x64
  InstallerUrl: https://api.fluxer.app/dl/desktop/stable/win32/x64/2026.1006.171735/setup
  InstallerSha256: FA54A5B1D48937E3C990BDA04A4FBE3E7ED0E9FBE35C2A0C854D4D417D1A365A
- Architecture: arm64
  InstallerUrl: https://api.fluxer.app/dl/desktop/stable/win32/arm64/2026.1006.171735/setup
  InstallerSha256: 47AC27E1794243AD64574A50EAC18AE4D28445B1D63A508B22BD89A49CDB763B
ManifestType: installer
ManifestVersion: 1.28.0
