# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: can1357.oh-my-pi
PackageVersion: 18.4.5
InstallerType: portable
Commands:
- omp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/can1357/oh-my-pi/releases/download/v18.4.5/omp-windows-x64.exe
  InstallerSha256: 9CE6F832F024AFE7D5E1C3AB6FB63CA92C906D688E7262A293BE1D7302849915
ManifestType: installer
ManifestVersion: 1.12.0
