# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.en-GB
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win32/en-GB/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: E122A2FFDB3777DA66F0E366615BBEC090728A501BC0B18524C83CA01626F5CF
  ProductCode: Mozilla Thunderbird 153.4.0 (x86 en-GB)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 en-GB)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win64/en-GB/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: C0D97B2614DDEA5A7F8D7A63DFB0C6214E6D478519F4AA0C3D2308C0F70AB901
  ProductCode: Mozilla Thunderbird 153.4.0 (x64 en-GB)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 en-GB)
ManifestType: installer
ManifestVersion: 1.12.0
