# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OrcaSVN.OrcaSVN
PackageVersion: 0.6.3
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: OrcaSVN
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- Publisher: orcasvn
  ProductCode: OrcaSVN
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\OrcaSVN'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/wustites/OrcaSVN/releases/download/v0.6.3/OrcaSVN_0.6.3_x64-setup.exe
  InstallerSha256: 575DB871252D56F36DAB9671A74A64853F06A13BB193B6B493871A0520BC31DB
ManifestType: installer
ManifestVersion: 1.12.0
