# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: goldjg.cARL
PackageVersion: 1.0.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: carl.exe
  PortableCommandAlias: carl
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/goldjg/cARL/releases/download/v1.0.1/carl_1.0.1_windows_amd64.zip
  InstallerSha256: EDBDC03B4C53BCD2AB0BD537DBBE026DF9501F163BA9E198D6C49EB814B55EDA
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
