# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.DriveCleaner
PackageVersion: 3.1.1.7
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Drive Cleaner 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/drivecleanerx86
  InstallerSha256: 14FE80E0355DF2D9B3A0E5E22FA1C87DCC943767CFBE2BE5D7D193F8AD228463
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/drivecleanerx64
  InstallerSha256: 198BEC6F233F96F9FA8491868F74C0694C06F1C5658DFC2B762981DD5E56C314
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/drivecleanerarm64
  InstallerSha256: 2B0FF4D27B874D57FD7EB82C76DA3CF936DBAED4FD60E17A81BD2D9F1F437684
ManifestType: installer
ManifestVersion: 1.12.0
