# Automatically updated by the winget bot at 2026/Sep/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: BitSum.ProcessLasso.Beta
PackageVersion: 18.4.0.45
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
ProductCode: ProcessLasso
ReleaseDate: 2026-08-13
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Process Lasso'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
  InstallerSha256: 31A26B5398FFD49E62824F35F061EC0E54C19B7F04110AC010A1BD6CCAE4A4E2
ManifestType: installer
ManifestVersion: 1.28.0
