# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.Nightly.MSIX
PackageVersion: 159.2610.809.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
PackageFamilyName: Mozilla.MozillaFirefoxNightly_jag0gd4e3s9p2
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- DisplayName: Firefox Nightly
  Publisher: Mozilla Corporation
Installers:
- Architecture: x86
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-08-09-43-36-mozilla-central/firefox-159.0a1.multi.win32.installer.msix
  InstallerSha256: 4E8202B451CEE23F51CDF56E71A3D3083C8254934920F2A70E7735F89E0E0D2A
  SignatureSha256: 0B48B48C2CC17928E4F1C6B2C89724292AF1B7890527F3307CD4492233AF7563
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2610.809.0_x86__jag0gd4e3s9p2'
- Architecture: x64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-08-09-43-36-mozilla-central/firefox-159.0a1.multi.win64.installer.msix
  InstallerSha256: 36A5ED0FA1B69D29382B0B46647209A717F73BBD28F78D5ECD81E78459E15D86
  SignatureSha256: 0109B389AB8E86593DAF91F5BAB7ED9DC2A4BD13D6C944F04F8E00D01481EE8C
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2610.809.0_x64__jag0gd4e3s9p2'
- Architecture: arm64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-08-09-43-36-mozilla-central/firefox-159.0a1.multi.win64-aarch64.installer.msix
  InstallerSha256: 792CBDFBFF2B6384994AB6B1C6A979B8636D88B6C6D4F91A1369FEF690898731
  SignatureSha256: C8DD70BBF9873FC3C9C682886F28DC35E802F2A22B498A95547392DF55B095D1
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2610.809.0_arm64__jag0gd4e3s9p2'
ManifestType: installer
ManifestVersion: 1.12.0
