# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HydraLauncher.Hydra
PackageVersion: 4.1.6
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- hydralauncher
ProductCode: 5c15b0c3-fe4f-5c4b-8f22-d37bfd0a3904
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/hydralauncher/hydra/releases/download/v4.1.6/hydralauncher-4.1.6-setup.exe
  InstallerSha256: 9648C41083293073DAA7202AAE86DA79E1657C0E1996386525511F07F0E996C9
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/hydralauncher/hydra/releases/download/v4.1.6/hydralauncher-4.1.6-setup.exe
  InstallerSha256: 9648C41083293073DAA7202AAE86DA79E1657C0E1996386525511F07F0E996C9
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
