# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ghost-him.ZeroLaunch-rs
PackageVersion: 1.4.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
ReleaseDate: 2026-10-09
AppsAndFeaturesEntries:
- UpgradeCode: '{0D8E70B2-4DC8-584D-88B0-7A83BA565C03}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ghost-him/ZeroLaunch-rs/releases/download/v1.4.0/zerolaunch-rs_1.4.0_x64_en-US.msi
  InstallerSha256: E4205EEDED6FAD52B23B5AFE35613DB6ACD8D3DF788C10851B87530775CE7A55
  ProductCode: '{BF19B2BB-FD00-4CC2-8245-28863AD40643}'
- Architecture: arm64
  InstallerUrl: https://github.com/ghost-him/ZeroLaunch-rs/releases/download/v1.4.0/zerolaunch-rs_1.4.0_arm64_en-US.msi
  InstallerSha256: C4075EBFC881A1BE0289BDA05BD2114E916B2494E99DF2DD6C85AC6D4EABF922
  ProductCode: '{A30B9A17-2ECC-45EB-9562-06C57F393ECD}'
ManifestType: installer
ManifestVersion: 1.12.0
