# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.it
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win32/it/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: 605D472AA262C109094AC87F1EEB5974C2022FD4DD9B921FBB6CBA06FDD38DF4
  ProductCode: Mozilla Thunderbird 153.4.0 (x86 it)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 it)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win64/it/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: EF2EF7EF74FC76A249EB6E1E1E3AAF63308D64AECE4A1EFB0E9CB61AF270879A
  ProductCode: Mozilla Thunderbird 153.4.0 (x64 it)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 it)
ManifestType: installer
ManifestVersion: 1.12.0
