# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: snapetech.slskr
PackageVersion: 0.2.49
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: slskr-v0.2.49-x86_64-pc-windows-msvc\slskr.exe
  PortableCommandAlias: slskr
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/snapetech/slskr/releases/download/release-v0.2.49/slskr-v0.2.49-x86_64-pc-windows-msvc.zip
  InstallerSha256: 616DAE7B54D9E322769E8DDA7EC3F9E3AEA9B0B06B02917447A6117573BE6670
ManifestType: installer
ManifestVersion: 1.6.0
