# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.KSnakeDuel
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: ksnakeduel
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/games/ksnakeduel/master/windows/ksnakeduel-master-892-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 7F903C4FB348A2AAF8A4F80BAF86EA4FECBDFC56A54A26E754D6DBD8D9EA4482
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/games/ksnakeduel/master/windows/ksnakeduel-master-892-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 7F903C4FB348A2AAF8A4F80BAF86EA4FECBDFC56A54A26E754D6DBD8D9EA4482
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
