# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Alibaba.OpenCodeReview
PackageVersion: 1.12.12
InstallerType: portable
Commands:
- opencodereview
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/alibaba/open-code-review/releases/download/v1.12.12/opencodereview-windows-amd64.exe
  InstallerSha256: C34033F9DA77E65AEBDDD64E37E671B4DD773AD4868E4F73922D13766EE6BB82
- Architecture: arm64
  InstallerUrl: https://github.com/alibaba/open-code-review/releases/download/v1.12.12/opencodereview-windows-arm64.exe
  InstallerSha256: D848AC9DB1FA3F9DECA6375BA525E817615160425DF4C7ACE078EE5D9B8CBE05
ManifestType: installer
ManifestVersion: 1.12.0
