# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Microsoft.Edge.Beta
PackageVersion: 156.0.4314.8
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msi
Scope: machine
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
AppsAndFeaturesEntries:
- UpgradeCode: '{55B884A6-908D-3E59-BDCE-5E4BFA64FA7B}'
Installers:
  - Architecture: x64
    InstallerUrl: https://download.microsoft.com/download/83d7d41a-239b-4118-a732-2230a2f5ba9e/MicrosoftEdgeBetaEnterpriseX64.msi
    InstallerSha256: FA5B0FFA659253949B55CD09C2B94AB06042A0357346229781CB7DA5F1378DDF
  - Architecture: x86
    InstallerUrl: https://download.microsoft.com/download/83d7d41a-239b-4118-a732-2230a2f5ba9e/MicrosoftEdgeBetaEnterpriseX86.msi
    InstallerSha256: C0EC206385348693712F135C8F1EB254843ABAD06D6B3AD1704AB06C230B8933
  - Architecture: arm64
    InstallerUrl: https://download.microsoft.com/download/83d7d41a-239b-4118-a732-2230a2f5ba9e/MicrosoftEdgeBetaEnterpriseARM64.msi
    InstallerSha256: E14EE6F833207292AACB8EDB198EB7EA0D6A08CB36132FD79C950E7A4BF97D3D
ManifestType: installer
ManifestVersion: 1.10.0

