# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: BiomeJS.Biome
PackageVersion: 2.5.15
InstallerType: portable
UpgradeBehavior: install
Commands:
- biome
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/biomejs/biome/releases/download/@biomejs/biome@2.5.15/biome-win32-x64.exe
  InstallerSha256: F2BEADEE753B78FE76081158123538BE886A31B5E67A34863E42535F3F491926
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/biomejs/biome/releases/download/@biomejs/biome@2.5.15/biome-win32-arm64.exe
  InstallerSha256: 6244A2BB366C76AD869B94F999EE60CE41B94112A11DC23C4F05FD1A7053256A
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.28.0
