# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CyberTimon.RapidRAW
PackageVersion: 1.6.5
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSuccessCodes:
- -1073741819
UpgradeBehavior: install
ProductCode: RapidRAW
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- Publisher: github
  ProductCode: RapidRAW
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\RapidRAW'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CyberTimon/RapidRAW/releases/download/v1.6.5/01_RapidRAW_v1.6.5_windows_x64.exe
  InstallerSha256: 44C38BB74B3C94A4F73CBEE3F8A9A678EFEB39C2ECD98E385438E2E1992DE4D2
- Architecture: arm64
  InstallerUrl: https://github.com/CyberTimon/RapidRAW/releases/download/v1.6.5/01_RapidRAW_v1.6.5_windows-11-arm_arm64.exe
  InstallerSha256: BDAFCC52205FE6D91DFFBE8669765B247EBA6ABC64DA68D2A2EC1A2E329901B9
ManifestType: installer
ManifestVersion: 1.12.0
