# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Pulkitxm.Quinjet
PackageVersion: "0.0.71"
InstallerType: zip
NestedInstallerType: portable
Commands:
  - quinjet
  - q
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Git.Git
ReleaseDate: "2026-10-07"
Installers:
  - Architecture: x64
    NestedInstallerFiles:
      - RelativeFilePath: quinjet.exe
        PortableCommandAlias: quinjet
      - RelativeFilePath: q.exe
        PortableCommandAlias: q
    InstallerUrl: https://github.com/pulkitxm/quinjet/releases/download/v0.0.71/quinjet-windows-x86_64.zip
    InstallerSha256: "E6FFA990784D724991BA1AD7CA1E03F3BAE5C99E5B1B13A69EF4AFDBAC652B4D"
ManifestType: installer
ManifestVersion: 1.12.0
