# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Kaidan
PackageVersion: master
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: Kaidan
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/network/kaidan/master/windows/kaidan-master-7254-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 611E9963D2AA41877932BCA6F5F3DFFA8805742091F2F5F307882D8925F7473E
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/network/kaidan/master/windows/kaidan-master-7254-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 611E9963D2AA41877932BCA6F5F3DFFA8805742091F2F5F307882D8925F7473E
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
