# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.el
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/el/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: C0A35EABA79CBD4797D3FEE00D1264BFD0199BB40202D29B6F41EC76179B805B
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/el/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 1FC28240D5AB9F042137235D54943EA0F4E89941963986AB97917A04327CE4D7
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/el/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 100651D0DC1F2717D0C15CBA81E0ECCAF7F8FF0C1B4343C8F80E8CB32078DB97
ManifestType: installer
ManifestVersion: 1.12.0
