# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ChengSoon.Belfry
PackageVersion: 0.21.13
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/ChengSoon/belfry-desktop/releases/download/v0.21.13/Belfry_0.21.13_x64-setup.exe
  InstallerSha256: AABBBB9A88A0B39799169F9BEC7299A4B6DA43CEB0932E1AE6A8E70A151EE3AA
  ProductCode: Belfry
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/ChengSoon/belfry-desktop/releases/download/v0.21.13/Belfry_0.21.13_x64_en-US.msi
  InstallerSha256: 66DA1690AB1A8833554A48B8BBEF278A13A52D6E659659CFC9BB29A35C0D0A7F
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{F713EA13-6255-4D8E-9A9B-7FE92380D862}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{7EFB541A-3C94-5A57-B8A4-6DB371DBFA56}'
ManifestType: installer
ManifestVersion: 1.12.0
