# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: OO-Software.ShutUp10
PackageVersion: 3.6.1135
InstallerType: portable
Installers:
- MinimumOSVersion: 10.0.0.0
  Architecture: x86
  InstallerUrl: https://package.oo-software.com/winget/shutup10/3.6.1135/ooshutup10_3.6.1135_x86.exe
  InstallerSha256: 21efaa179a6f75f3870b4a1712addc6f881466dc24185d6da243229fd1f277ce
  Commands:
  - shutup10
- MinimumOSVersion: 10.0.0.0
  Architecture: x64
  InstallerUrl: https://package.oo-software.com/winget/shutup10/3.6.1135/ooshutup10_3.6.1135_x64.exe
  InstallerSha256: 925ccd8164a90f6a1c8d907415f38df353a4ff00db73f07598a29b8f7928bb52
  Commands:
  - shutup10
- MinimumOSVersion: 10.0.0.0
  Architecture: arm64
  InstallerUrl: https://package.oo-software.com/winget/shutup10/3.6.1135/ooshutup10_3.6.1135_arm64.exe
  InstallerSha256: 7ba7f267fcef3b967710052fcf9ec0100eb27fa752ded862cf9df9154e546fd8
  Commands:
  - shutup10
ManifestType: installer
ManifestVersion: 1.10.0
