# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: MichalFoist.mailnino
PackageVersion: 1.3.4
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
  - DisplayName: mailnino
    Publisher: Michal Foist
    ProductCode: mailnino
    InstallerType: nullsoft
Installers:
  - Architecture: x64
    InstallerUrl: https://mailnino.cz/mailnino_1.3.4_x64-setup.exe
    InstallerSha256: FF340282D11B27BE586A96F77BFEBC62A1120DE308BB43F99BB6624C2698A997
ManifestType: installer
ManifestVersion: 1.6.0
