# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: RedCactus.Bubble
PackageVersion: 5.1.3
InstallerLocale: en-US
InstallerType: msi
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: '{1C086A9F-BDE7-4046-909A-F29440C90A8F}'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- ProductCode: '{1C086A9F-BDE7-4046-909A-F29440C90A8F}'
  UpgradeCode: '{56FC8793-125F-40DC-8864-EC6FCADC95D4}'
InstallationMetadata:
  DefaultInstallLocation: APPDIR:.
Installers:
- Architecture: x64
  InstallerUrl: https://api.eu.redcactus.cloud/v1/public/software/download/latest/ff582a83-5f70-4629-aec8-4ed498dcc1b8/bubble/windows_x64
  InstallerSha256: 4846FF1B9AA67303495CFE65902D20EFD0E3597A4DAC6805589FC36C0CD00B45
ManifestType: installer
ManifestVersion: 1.12.0
