# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ShareFile.ShareFileForWindows
PackageVersion: 26.9.9.0
PackageLocale: en-US
Publisher: ShareFile
PublisherUrl: https://sharefile.com
PublisherSupportUrl: https://support.sharefile.com/s/
PackageName: ShareFile For Windows
License: Proprietary
ShortDescription: ShareFile for Windows allows you to access your files directly through a mapped drive. ShareFile provides a native Windows Explorer experience.
Tags:
- citrixfiles
- sharefile
ManifestType: defaultLocale
ManifestVersion: 1.12.0
