# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TinyHumansAI.OpenHuman
PackageVersion: 0.64.14
UpgradeBehavior: install
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/tinyhumansai/openhuman/releases/download/v0.64.14/OpenHuman_0.64.14_x64-setup.exe
  InstallerSha256: 993B9B7BB02BEF6859D3DA559488C1B3CB8211E11594CD284F94857D6C8090CC
  ProductCode: OpenHuman
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/tinyhumansai/openhuman/releases/download/v0.64.14/OpenHuman_0.64.14_x64_en-US.msi
  InstallerSha256: 1E16D26CA390577FA7325657616B0B2031ACA077E983AD4E327D5DAFBB5D09FD
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{6E551EB3-02C5-47BC-A6EF-FA653DCB47FA}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{54052255-0CFF-5EA8-82D1-C533E6DE0990}'
ManifestType: installer
ManifestVersion: 1.12.0
