# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 155.1.99.12
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.12/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 7B897F1BD50DFCE3229EF573A1FC478E650996ABEF11FAAC1E0B79FE0063B742
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.12/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: D70B80490B239FB4685BFF52AA6B23EFD49B46D6A51109ECFD506E0EEB2A220C
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.12/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 76AB3E26A3CD59204B41738DC54A4A175EEC5B6DA337EA303701072A2519CBC5
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.12/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: 72EB56B8A15BE9F2BC1C3BA38F22ACA34C6E29C4F0AC2417BDD266C56EA1C5D1
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.12/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 1F8149BEBCA51CB7F2E96953E30D7A757E4B9F44E464FFAE82C81371E9AB542B
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.12/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: 4FAD9498B5D2560D56910F769568BDBD2D8EA254F269AE3BAE1D689B9E213890
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
