# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GiulioSorrentino.IlFortunedinumerone
PackageVersion: 2.4.0.3
InstallerLocale: en-US
InstallerType: wix
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
ProductCode: '{477E4D53-8455-4DD6-B16F-8722656C5713}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/GiulianoSpaghetti/ilfortunedinumeronematerial/releases/download/2.4.0.0/ilfortunedinumerone-2.4.0.3-material-amd64.msi
  InstallerSha256: 5669FE211F3144850F99FE4CEDF5005B715A0F4368D99D4B7EA52477B975E4F5
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-24
