# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: evilmartians.lefthook
PackageVersion: 2.1.16
InstallerType: portable
UpgradeBehavior: install
Commands:
- lefthook
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.1.16/lefthook_2.1.16_Windows_i386.exe
  InstallerSha256: 2FDE86A3D6EAA37CE111800FF40A8E0709C6FC584214BDD47EE36A521DA05215
- Architecture: x64
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.1.16/lefthook_2.1.16_Windows_x86_64.exe
  InstallerSha256: C2DD5F3D79D6D8A89F5F3EA245BB62B964ECA9ED52B7C9521550F7BC1D71BA6E
- Architecture: arm64
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.1.16/lefthook_2.1.16_Windows_arm64.exe
  InstallerSha256: 47A8775ADF9F8C2078163ABCF46E742ED6CBB46385411D033D8D509535369111
ManifestType: installer
ManifestVersion: 1.12.0
