# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Watfaq.ClashRS
PackageVersion: 0.10.10
InstallerType: portable
Commands:
- clash
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/ibigbug/clash-rs/releases/download/v0.10.10/clash-rs-i686-pc-windows-msvc.exe
  InstallerSha256: B231B648CB3A6C8332BE8BBACD00C71A1888ED008C5CC5F811BD344B0A5BA185
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://github.com/ibigbug/clash-rs/releases/download/v0.10.10/clash-rs-x86_64-pc-windows-msvc.exe
  InstallerSha256: E5D2E23534D7A4C294818A8852CF447DCF988DD589FA25B8C56F00D5970D6012
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/ibigbug/clash-rs/releases/download/v0.10.10/clash-rs-aarch64-pc-windows-msvc.exe
  InstallerSha256: 0D43864DD4FE4341A07748CB32754BC4233638906F43802898F9E69F6A930BEE
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
