# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.hu
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win32/hu/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: A064AB81DE45EF3C3B5540ADC3AB2FBAE135A0E9EBDAFE5056134A20F2A93624
  ProductCode: Mozilla Thunderbird 157.0.1 (x86 hu)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win64/hu/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: 219DD6BC3F7674F8980011089DE13CD151B8B31AC8E48F9C58DF86B726DAF7C2
  ProductCode: Mozilla Thunderbird 157.0.1 (x64 hu)
ManifestType: installer
ManifestVersion: 1.12.0
