# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.316
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.316/anchors_0.1.316_windows_amd64.zip
  InstallerSha256: 154FBB51FAFC81F32BD8C03260928C77C49F7ED6A036A6447A753AADD6EB9E41
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.316/anchors_0.1.316_windows_arm64.zip
  InstallerSha256: BEB9ED08E54A43EB68BE29341419D83F52B9DCB74CFD8C1B5DD64FE97009DF76
ManifestType: installer
ManifestVersion: 1.12.0
