# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: JannisX11.Blockbench
PackageVersion: 5.2.2
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
UpgradeBehavior: install
FileExtensions:
- bbmodel
ProductCode: "{F73268A5-4451-5BB0-B2B7-A92A16EE01D9}"
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- DisplayName: Blockbench 5.2.2
  ProductCode: "{F73268A5-4451-5BB0-B2B7-A92A16EE01D9}"
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JannisX11/blockbench/releases/download/v5.2.2/Blockbench_5.2.2.exe
  InstallerSha256: DE14D72E27A6598AD5595CA5E66C15EA0E360DE5218207F934572265245A2BC1
ManifestType: installer
ManifestVersion: 1.12.0
