# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: CaddyServer.Caddy
PackageVersion: 2.11.7
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: caddy.exe
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/caddyserver/caddy/releases/download/v2.11.7/caddy_2.11.7_windows_amd64.zip
  InstallerSha256: 0A1EDC0B799512051C57071CE0E798D3F2CF67DC98171366F1D2B326072E3B06
- Architecture: arm64
  InstallerUrl: https://github.com/caddyserver/caddy/releases/download/v2.11.7/caddy_2.11.7_windows_arm64.zip
  InstallerSha256: 34804A5E61106FA6718682F5BE6C9EDC4CCEEC9601BA7E25BEEC1E176CFC3B47
ManifestType: installer
ManifestVersion: 1.28.0
