# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AurelioAvila.PCTweaker
PackageVersion: 1.15.6
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
ProductCode: pc-tweaker-app
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- DisplayName: pc-tweaker-app
  ProductCode: pc-tweaker-app
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\pc-tweaker-app'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AurelioAvila/pc-tweaker-app/releases/download/v1.15.6/pc-tweaker-app_1.15.6_x64-setup.exe
  InstallerSha256: 67F4D9C91CD2061624F8F98EF9FAC254D02616C55B6DCABC7E47ADCDF314B472
ManifestType: installer
ManifestVersion: 1.12.0
