# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Kubernetes.kustomize
PackageVersion: 5.8.3
PackageLocale: en-US
Publisher: Kubernetes SIGs
PublisherUrl: https://kubernetes.io/
PublisherSupportUrl: https://github.com/kubernetes-sigs/kustomize/issues
PackageName: kustomize
PackageUrl: https://github.com/kubernetes-sigs/kustomize
License: Apache-2.0
LicenseUrl: https://github.com/kubernetes-sigs/kustomize/blob/HEAD/LICENSE
Copyright: Copyright 2026 The Kubernetes Authors.
ShortDescription: Customization of kubernetes YAML configurations
Description: |-
  kustomize lets you customize raw, template-free YAML files for multiple purposes, leaving the original YAML untouched and usable as is.
  kustomize targets kubernetes; it understands and can patch kubernetes style API objects. It's like make, in that what it does is declared in a file, and it's like sed, in that it emits edited text.
Tags:
- cluster
- container
- docker
- k8s
- kubernetes
ReleaseNotes: |-
  This release eliminates dependencies and compressed blobs that were an issue when bumping kustomize-in-kubectl.
  No functional changes in kustomize.
  chore
  #6310: chore: bump to Go 1.27 and latest kube-openapi
  #6318: Update kyaml to v0.21.3
  #6320: Update cmd/config to v0.21.3
  #6321: Update api to v0.21.3
ReleaseNotesUrl: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize/v5.8.3
ManifestType: defaultLocale
ManifestVersion: 1.12.0
