# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MarkusKellermann.Convo
PackageVersion: 1.10.0
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/markolo10/convo-releases/releases/download/v1.10.0/convo-setup.exe
  InstallerSha256: B5803C88C8375BCAE92A127CAB6A00578C2DC76796531AC25EBEEC0CF8E33194
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-06
