# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: PlayStation.PSRemotePlay
PackageVersion: 9.5.0.08040
Platform:
- Windows.Desktop
ElevationRequirement: elevatesSelf
UpgradeBehavior: install
InstallerLocale: en-US
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://remoteplay.dl.playstation.net/remoteplay/module/win/RemotePlayInstaller_9.5.0.08040_x64.msi
  InstallerSha256: A67D36C6FB14E67EC78858B831153FE372A0AF5F7C41649EF710E3E8FC30BC25
  ProductCode: '{A31BCB56-DE48-43B5-8DBC-E07215F6AF65}'
- Architecture: x64
  InstallerType: exe # InstallShield; kept as a legacy secondary installer for those with pre-9.5 Winget installations of PS Remote Play.
  InstallerSwitches:
    Silent: /s /v/qn
    SilentWithProgress: /s /v/qb
  InstallerUrl: https://remoteplay.dl.playstation.net/remoteplay/module/win/RemotePlayInstaller.exe
  InstallerSha256: f10055d503c47a4e96fd2f578fbcba3e651c19ecbe7f30ed87c15bec798f5684
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
    MinimumVersion: 14.51.36247.0
ManifestType: installer
ManifestVersion: 1.28.0
