# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LuisPater.CLIProxyAPI
PackageVersion: 8.0.17
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cli-proxy-api.exe
Commands:
- cli-proxy-api
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/router-for-me/CLIProxyAPI/releases/download/v8.0.17/CLIProxyAPI_8.0.17_windows_amd64.zip
  InstallerSha256: FBAC0BE6FD4AC72E0DF91C5FD9EAC39246D0D8E356D1D624B2603BDF5859DEA0
ManifestType: installer
ManifestVersion: 1.12.0
