# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Atlassian.JiraSoftwareLTS
PackageVersion: 10.3.26
InstallerType: exe
InstallerSwitches:
  Silent: -Vapp.install.service$Boolean=true -VexecuteLauncherAction$Boolean=false -VexistingInstallationDir="C:\Program Files\Jira Software" -Vlaunch.application$Boolean=false -VportChoice=default -Vsys.adminRights$Boolean=true -Vsys.confirmedUpdateInstallationString=false -Vsys.installationDir="C:\Program Files\Atlassian\Jira" -Vsys.languageId=en -Vsys.programGroupAllUsers$Boolean=false -Vsys.programGroupName=Jira -Dinstall4j.debug=true -Dinstall4j.keepLog=true -q
  SilentWithProgress: -Vapp.install.service$Boolean=true -VexecuteLauncherAction$Boolean=false -VexistingInstallationDir="C:\Program Files\Jira Software" -Vlaunch.application$Boolean=false -VportChoice=default -Vsys.adminRights$Boolean=true -Vsys.confirmedUpdateInstallationString=false -Vsys.installationDir="C:\Program Files\Atlassian\Jira" -Vsys.languageId=en -Vsys.programGroupAllUsers$Boolean=false -Vsys.programGroupName=Jira -Dinstall4j.debug=true -Dinstall4j.keepLog=true -q -alerts
Installers:
- Architecture: x64
  InstallerUrl: https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-10.3.26-x64.exe
  InstallerSha256: EBBC33158A9E58D80ED2B224CDFD4BB4E48267F452E12F6BA28038D1082B0F39
ManifestType: installer
ManifestVersion: 1.12.0
