# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1791158509-g485487
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1791158509-g485487/amp-windows-x64-baseline.exe
  InstallerSha256: 74793587DB1FD189E1E94434A8192A0539FCA5CEA8CD8446AD96334974E96CBC
ManifestType: installer
ManifestVersion: 1.12.0
