PackageIdentifier: Sparcle.BoltEnterprise
PackageVersion: 0.1.170
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    Scope: user
    InstallerUrl: https://github.com/SparcleHQ/sparcle.app/releases/download/v0.1.170/Bolt-Enterprise-0.1.170-x86_64-pc-windows-msvc.exe
    InstallerSha256: F5036A069B0EF62B2AB5185C973CB9E54CCAB60E9D8D65275AECCE7AFCCC8C1F
    AppsAndFeaturesEntries:
      - DisplayName: Bolt
        ProductCode: Bolt
ManifestType: installer
ManifestVersion: 1.6.0
