# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.kk
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win32/kk/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: 7ACCB375AF67A82B48A6E04705196EE2653EE1B00E331AC247743F33BF06E42C
  ProductCode: Mozilla Thunderbird 157.0.1 (x86 kk)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win64/kk/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: 606E0B7D5E966BB5F8131EBBCEA5367200803C651D234C24D8F8A2A3285B9FE1
  ProductCode: Mozilla Thunderbird 157.0.1 (x64 kk)
ManifestType: installer
ManifestVersion: 1.12.0
