# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: getreu.tpnote
PackageVersion: 1.27.3
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{F0FDBD28-C3EA-46A1-BD58-509310D074CB}'
ReleaseDate: 2026-09-30
AppsAndFeaturesEntries:
- Publisher: getreu.net
  ProductCode: '{F0FDBD28-C3EA-46A1-BD58-509310D074CB}'
  UpgradeCode: '{6F9619FF-8B86-D011-B42D-00C04FC964FF}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%/Tp-Note'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/getreu/tp-note/releases/download/v1.27.3/tpnote-1.27.3-x64.msi
  InstallerSha256: 931D032239B2E1576001A073015291C6E4F0AD4EF20382F81469EF93D1B0FEFF
ManifestType: installer
ManifestVersion: 1.12.0
