# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Bostrot.WSLManager
PackageVersion: 2.5.0.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: inno
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wsl2distromanager.exe
Scope: machine
ProductCode: '{E4CB01D9-BD26-4D65-A2A7-7EAFD519B2A5}_is1'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- ProductCode: '{E4CB01D9-BD26-4D65-A2A7-7EAFD519B2A5}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\WSL2 Distro Manager'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bostrot/wslmanager/releases/download/v2.5.0/wsl2-distro-manager-v2.5.0-setup.exe
  InstallerSha256: 59690DE6852AA3F5BF878D6657E177CF82C1D5F7EA49929E897951763C826927
ManifestType: installer
ManifestVersion: 1.12.0
