# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Metanorma.Metanorma
PackageVersion: 1.17.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{F3750751-1AE3-44A0-93D8-AA66D81E00DC}'
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- DisplayName: metanorma
  Publisher: Metanorma
  ProductCode: '{F3750751-1AE3-44A0-93D8-AA66D81E00DC}'
  UpgradeCode: '{57CE2E16-2EA0-4B1C-AD8F-7E66F82D0EAA}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\metanorma'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/metanorma/packed-metanorma/releases/download/v1.17.0-1/metanorma-setup-1.17.0-windows-ucrt64.msi
  InstallerSha256: 02E86C4B49BFE9B50E16D8ADEDE0C9FDA4B015ADDC5A0F86D72364CFBD5488BB
ManifestType: installer
ManifestVersion: 1.12.0
