# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.lt
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win32/lt/Firefox%20Setup%20157.0.exe
  InstallerSha256: 2AFFE1923BBE12C171885FF1F481F4365CDEBD6761538EAF8AFAD34E79ED1A3E
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64/lt/Firefox%20Setup%20157.0.exe
  InstallerSha256: F49D87C8769F36B36E9BF05EB84CC45941C80B73953B7188D1FA7652BADBEAD5
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0/win64-aarch64/lt/Firefox%20Setup%20157.0.exe
  InstallerSha256: 916B06D211A7B749F3926C47590D65F74D83D01757F0FAB209EE075364A4528B
ManifestType: installer
ManifestVersion: 1.12.0
