# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Invantive.InvantiveDataLoader
PackageVersion: 27.0.22
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
ProductCode: '{8484118A-71B1-4ED1-BED8-4D42B0018B00}'
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- UpgradeCode: '{8484118A-71B1-4ED1-BED8-4D4200001B00}'
Installers:
- Architecture: x64
  InstallerUrl: https://download.invantive.eu/current/Invantive%20Data%20Loader-current.msi
  InstallerSha256: F198AC47BBBE3AEC6BF8294F0481BD6CB9C45222D659EA02A4419CB38873E822
ManifestType: installer
ManifestVersion: 1.12.0
