# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: MarcoDAmato.WinContig
PackageVersion: 5.0.3.4
PackageLocale: en-US
Publisher: MarcoDAmato
PackageName: WinContig
License: Proprietary
ShortDescription: Portable Defragmentation Tool for files and folders.
Description: |
  WinContig is an easy-to-use stand-alone defragmentation tool that does not create any installation directories or registry entries on your computer. Its purpose is to quickly defragment individual files without the need to defragment the entire disk. WinContig supports FAT32 and NTFS file systems, and works with both hard disks and SSDs.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
