# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Netbird.Netbird
PackageVersion: 0.80.0
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.80.0/netbird_installer_0.80.0_windows_amd64.msi
  InstallerSha256: B9A3EB6BA880F3D4205A30041CAB9738716C89D7EC021DD41AF38A36E21B6FB8
  ProductCode: '{85279BA8-C0CA-4445-864D-6D48FACB0CD9}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 0.80.0
    UpgradeCode: '{6456EC4E-3AD6-4B9B-A2BE-98E81CB21CCF}'
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.80.0/netbird_installer_0.80.0_windows_amd64.exe
  InstallerSha256: 1E02ED3ED2B739C3D4D03F74F740CCB2E4CC71D3CF2F2210CF50314BCA00BD1B
  ProductCode: Netbird
  AppsAndFeaturesEntries:
  - DisplayVersion: 0.80.0.36903612572
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.80.0/netbird_installer_0.80.0_windows_arm64.msi
  InstallerSha256: 347A318EB9DF6CD441584EA22A4FF2816F983472D45EF06D082EFF326D92358E
  ProductCode: '{C32A849B-DCC8-4E67-93BD-FCAAE18DEC82}'
  AppsAndFeaturesEntries:
  - DisplayVersion: 0.80.0
    UpgradeCode: '{6456EC4E-3AD6-4B9B-A2BE-98E81CB21CCF}'
- Architecture: arm64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/netbirdio/netbird/releases/download/v0.80.0/netbird_installer_0.80.0_windows_arm64.exe
  InstallerSha256: 96DAA3AB199F1C2BD78CD621E3FADFBEF9C4C756B0004475E481FB9E3C890782
  ProductCode: Netbird
  AppsAndFeaturesEntries:
  - DisplayVersion: 0.80.0.36903612572
ManifestType: installer
ManifestVersion: 1.12.0
