# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.Nightly.MSIX
PackageVersion: 160.2610.921.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
PackageFamilyName: Mozilla.MozillaFirefoxNightly_jag0gd4e3s9p2
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- DisplayName: Firefox Nightly
  Publisher: Mozilla Corporation
Installers:
- Architecture: x86
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-09-21-40-58-mozilla-central/firefox-160.0a1.multi.win32.installer.msix
  InstallerSha256: 14EC04D838CAF72B25666F6E25C79526BAEDFD5D52017EF21FC8688C23FA967A
  SignatureSha256: 0F9EBA7D3A1B9AF68F4998BCE57598813B65F5C018968F71268DC7B7CEED9277
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_160.2610.921.0_x86__jag0gd4e3s9p2'
- Architecture: x64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-09-21-40-58-mozilla-central/firefox-160.0a1.multi.win64.installer.msix
  InstallerSha256: 33AC74569244B0D0F0ECAF6C48B2B4ED7CE6B2CAE309398132646CD47F21836D
  SignatureSha256: 627C9EF561AEFD31F72CCFF675FA7A7D772AA6C84079A674C59B4034C163ACC0
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_160.2610.921.0_x64__jag0gd4e3s9p2'
- Architecture: arm64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-09-21-40-58-mozilla-central/firefox-160.0a1.multi.win64-aarch64.installer.msix
  InstallerSha256: 6E9C4419F58201AB8E49BCFBB2FE75DF60293B24C2689AF13A74E77513A28233
  SignatureSha256: 0CBC7ED0E9CD698FEDB7F90D8E5BFA1B98291FF7042CFDFC2BDF8BBEBAD78235
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_160.2610.921.0_arm64__jag0gd4e3s9p2'
ManifestType: installer
ManifestVersion: 1.12.0
