# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: holland-built.Bloxsmith
PackageVersion: 3.82.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: bloxsmith.exe
  PortableCommandAlias: bloxsmith
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/holland-built/bloxsmith/releases/download/v3.82.0/bloxsmith_3.82.0_windows_amd64.zip
  InstallerSha256: 2F09D6663CF262B9544E63F6A614F4F68ED90C84BB95192E8237615E5F9DFC2D
ManifestType: installer
ManifestVersion: 1.12.0
