# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mwo-dk.Coxswain.Terminal
PackageVersion: 2.20.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: coxswain-terminal-v2.20.3-x86_64-pc-windows-msvc/cox.exe
  PortableCommandAlias: cox
- RelativeFilePath: coxswain-terminal-v2.20.3-x86_64-pc-windows-msvc/coxswain.exe
  PortableCommandAlias: coxswain
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mwo-dk/coxswain/releases/download/v2.20.3/coxswain-terminal-v2.20.3-x86_64-pc-windows-msvc.zip
  InstallerSha256: 4768B32643F20C7CB8EEBFB24BA391F6B56B247DE4D8421015B3F9912630CE5B
ManifestType: installer
ManifestVersion: 1.12.0
