# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: SJMC.SJMCL
PackageVersion: 1.3.2
InstallerType: nullsoft
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/UNIkeEN/SJMCL/releases/download/v1.3.2/SJMCL_1.3.2_windows_x86_64_setup.exe
    InstallerSha256: d6673da6ac1665110379f69b7da8138506ab890ae7b6418dce4636aa00af619e
  - Architecture: x86
    InstallerUrl: https://github.com/UNIkeEN/SJMCL/releases/download/v1.3.2/SJMCL_1.3.2_windows_i686_setup.exe
    InstallerSha256: 80ac2189a19613cd28afa436b95dc1b8a14d539bda9962cbf67ef818bbbf4993
  - Architecture: arm64
    InstallerUrl: https://github.com/UNIkeEN/SJMCL/releases/download/v1.3.2/SJMCL_1.3.2_windows_aarch64_setup.exe
    InstallerSha256: 5dfe2c1384f264595a73e5438ed55837b09adbebdb51cd9c6737b5c004047970
ManifestType: installer
ManifestVersion: 1.10.0
