# Automatically updated by the winget bot at 2026/Oct/03
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Kumospace.Kumospace
PackageVersion: 7.2.0
InstallerLocale: en-US
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: Kumospace
  Publisher: Kumospace, Inc.
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.kumospace.com/production/windows/x64/latest/Kumospace-Setup.exe
  InstallerSha256: 91ED8A2A4A0077B70FF68EC8E85E14555DC3C9CC253567A9F76E1CC35F128075
ManifestType: installer
ManifestVersion: 1.28.0
