# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.IntegrationRuntime
PackageVersion: 5.70.9748.2
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLLOCATION="<INSTALLPATH>"
FileExtensions:
- dmgbackup
- irbackup
ProductCode: '{2F713E3A-D88B-4813-B2AE-C80500A4AFA2}'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- UpgradeCode: '{49681305-13D3-47DE-95B3-90767D1F2148}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Microsoft Integration Runtime'
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/e/4/7/e4771905-1079-445b-8bf9-8a1a075d8a10/IntegrationRuntime_5.70.9748.2.msi
  InstallerSha256: B899039C894A2DDD64045759CD22A4C394F1766072B23AFEF2DA61AB79329B86
ManifestType: installer
ManifestVersion: 1.12.0
