# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Kamjin.Chatless
PackageVersion: 0.7.1
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/kamjin3086/chatless/releases/download/v0.7.1/Chatless_0.7.1_x64-setup.exe
  InstallerSha256: F2ECDE9807F0C915841719B7FE307A8AAF52A30CA421828433AF12793382E71E
  ProductCode: Chatless
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/kamjin3086/chatless/releases/download/v0.7.1/Chatless_0.7.1_x64_en-US.msi
  InstallerSha256: FB4671E8A358DB59EC8FD8D4F7AE072B9DB0361BA3695968B971F41E30ADFF80
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{9667937E-C9C8-4482-BA1B-A109EEFAA74C}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{701F5048-B5EF-5865-929A-76016298B01E}'
ManifestType: installer
ManifestVersion: 1.12.0
