# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.en-CA
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win32/en-CA/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: BA7B60CC3189CCC4AE580DC7F60E1C52067572625A8B4B85B0A678EE4AEEF9F1
  ProductCode: Mozilla Thunderbird 153.4.0 (x86 en-CA)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 en-CA)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win64/en-CA/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: 37E78DBE5A10A5733A07D7616D2C2104F98CB6CC0A1B41A4D72CC3DA0DBC2AB0
  ProductCode: Mozilla Thunderbird 153.4.0 (x64 en-CA)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 en-CA)
ManifestType: installer
ManifestVersion: 1.12.0
