# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: futrime.lip
PackageVersion: 0.34.9
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: lip.exe
  PortableCommandAlias: lip
- RelativeFilePath: lipd.exe
  PortableCommandAlias: lipd
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.Runtime.10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/futrime/lip/releases/download/v0.34.9/lip-0.34.9-win-x64.zip
  InstallerSha256: A38F0ECE59648EAC471F29F576181299F84289123FAF054D3E50C5C984A87833
- Architecture: arm64
  InstallerUrl: https://github.com/futrime/lip/releases/download/v0.34.9/lip-0.34.9-win-arm64.zip
  InstallerSha256: 090B69A5F0F9CA03049E7A78D0C486B6D2BDB35002CD8DD77BEBE5C8C6072D3D
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-07
