# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenJS.Electron.44
PackageVersion: 44.7.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: electron.exe
  PortableCommandAlias: electron
UpgradeBehavior: install
ReleaseDate: 2026-10-07
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/electron/electron/releases/download/v44.7.0/electron-v44.7.0-win32-x64.zip
  InstallerSha256: EEE30DC8FA1F5EA95490E59F44E46EA68DD24C6E93D22FACF70FE5C2D4C2665C
- Architecture: arm64
  InstallerUrl: https://github.com/electron/electron/releases/download/v44.7.0/electron-v44.7.0-win32-arm64.zip
  InstallerSha256: EE2621A4513F92A952273D5363E153DB6F0E4DD183D89F2C0F740FAA13623316
ManifestType: installer
ManifestVersion: 1.12.0
