# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AuthorMore.PenpotDesktop
PackageVersion: 1.0.0
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: fce6a886-f595-5ead-8bc0-3232435b1b25
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/author-more/penpot-desktop/releases/download/v1.0.0/penpot-desktop-x64.exe
  InstallerSha256: 5629D8D23D6A3887EEEE11996EDA19F2DCDA225396DBCB1D9D5FAB635410AA02
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/author-more/penpot-desktop/releases/download/v1.0.0/penpot-desktop-x64.exe
  InstallerSha256: 5629D8D23D6A3887EEEE11996EDA19F2DCDA225396DBCB1D9D5FAB635410AA02
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/author-more/penpot-desktop/releases/download/v1.0.0/penpot-desktop-arm64.exe
  InstallerSha256: F1BE6603E51C60B5BF9EAD3B945380FBFC4C6261138F3BF9016230FC387D9500
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/author-more/penpot-desktop/releases/download/v1.0.0/penpot-desktop-arm64.exe
  InstallerSha256: F1BE6603E51C60B5BF9EAD3B945380FBFC4C6261138F3BF9016230FC387D9500
  InstallerSwitches:
    Custom: /allusers
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
