# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Notion.Notion
PackageVersion: 7.37.0
Protocols:
- notion
FileExtensions:
- markdown
- md
- mdown
- mkd
- mkdn
- rmd
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://desktop-release.notion-static.com/Notion%20Setup%207.37.0.exe
  InstallerSha256: C999111715005B44FA60B6CDA0986291B88DF7BAF5471F9CD5F940DCCC1C5F43
  InstallerSwitches:
    Upgrade: --updated
  ExpectedReturnCodes:
  - InstallerReturnCode: 2
    ReturnResponse: packageInUse
  UpgradeBehavior: install
  ProductCode: 661f0cc6-343a-59cb-a5e8-8f6324cc6998
- Architecture: arm64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://desktop-release.notion-static.com/Notion%20Setup%207.37.0%20arm64.exe
  InstallerSha256: 51E03FA7E62F1BB55AB57D9840D57EF4111D2AD08E091068528A5E95353585DA
  InstallerSwitches:
    Upgrade: --updated
  ExpectedReturnCodes:
  - InstallerReturnCode: 2
    ReturnResponse: packageInUse
  UpgradeBehavior: install
  ProductCode: 661f0cc6-343a-59cb-a5e8-8f6324cc6998
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://desktop-release.notion-static.com/Notion-7.37.0.msix
  InstallerSha256: 06F3BB1CB59E93F52223E320609B6DEA2B28E0A94642293BF347A2E5B4096399
  SignatureSha256: 5C064C58F5A3E409604E8EA26CA3542797D5F260BBADFADA49EB45D5DEA5B7B0
  PackageFamilyName: com.notion.app.desktop.notion_87smfmv0eebam
  Capabilities:
  - internetClient
  - microphone
  RestrictedCapabilities:
  - packageManagement
  - runFullTrust
  - unvirtualizedResources
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.19041.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://desktop-release.notion-static.com/Notion-arm64-7.37.0.msix
  InstallerSha256: BBE4B0BD5D08A5C5856FCB6A54E1FF695AF1D7E2121096FF5A44481B93B99F5F
  SignatureSha256: D1C1391A292B8C51AB2AFCD6F28019238EBC8E067DB208EBE1E8A8135908A80B
  PackageFamilyName: com.notion.app.desktop.notion_87smfmv0eebam
  Capabilities:
  - internetClient
  - microphone
  RestrictedCapabilities:
  - packageManagement
  - runFullTrust
  - unvirtualizedResources
ManifestType: installer
ManifestVersion: 1.12.0
