PackageIdentifier: EazyMake.EazyMake
PackageVersion: 1.4.9
InstallerLocale: en-US
InstallerType: zip
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/3667808244/EazyMake/releases/download/v1.4.9/ezmk-windows-x64.zip
    InstallerSha256: db571d666fbfec162f0d7e675b1a64852d57fb91e024d0c1b4d796852b9bcee0
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: ezmk.exe
        PortableCommandAlias: ezmk
ManifestType: installer
ManifestVersion: 1.6.0
