# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Moonfin.Moonfin
PackageVersion: 2.7.0
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Moonfin-Client/Moonfin-Core/releases/download/2.7.0/Moonfin_Windows_v2.7.0.exe
  InstallerSha256: D7BAE3F42233E7B1EF76B00E2746FBA3FEF25EF7AFB5A45EAAED28749B7EC3E7
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/Moonfin-Client/Moonfin-Core/releases/download/2.7.0/Moonfin_WindowsARM64_v2.7.0.exe
  InstallerSha256: 67371C27DD452E2B7B5698D2AFEAE1D430BCF3F75B764E8E6378BF457F50EF57
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-09
