# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: spaam.svtplay-dl
PackageVersion: '4.199'
DefaultLocale: en-GB
ManifestType: version
ManifestVersion: 1.28.0
