# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Amazon.Redshift.ODBC.v2
PackageVersion: 2.2.4.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{0272D150-34AD-4D61-9B85-7E66AD7BEBBD}'
ReleaseDate: 2026-09-24
AppsAndFeaturesEntries:
- ProductCode: '{0272D150-34AD-4D61-9B85-7E66AD7BEBBD}'
  UpgradeCode: '{384ACDAA-EBC3-49FA-BF62-82B4E612F8B1}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Amazon Redshift ODBC Driver x64'
Installers:
- Architecture: x64
  InstallerUrl: https://s3.amazonaws.com/redshift-downloads/drivers/odbc/2.2.4.0/AmazonRedshiftODBC64-2.2.4.0.msi
  InstallerSha256: AE7D7D32248A60019F438DC1489EEA692B7F872B09E09C4033EB0425675FB30B
ManifestType: installer
ManifestVersion: 1.12.0
