# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PDFsam.PDFsam
PackageVersion: 6.0.6.0
PackageLocale: en-US
Publisher: Sober Lemur S.r.l.
PublisherUrl: https://soberlemur.com/
PublisherSupportUrl: https://github.com/torakiki/pdfsam/issues
PrivacyUrl: https://pdfsam.org/privacy-policy/
Author: Sober Lemur S.r.l.
PackageName: PDFsam Basic
PackageUrl: https://pdfsam.org/pdfsam-basic/
License: AGPL-3.0
LicenseUrl: https://github.com/torakiki/pdfsam/blob/HEAD/LICENSE
Copyright: Copyright by Sober Lemur S.r.l.
ShortDescription: A free, open source, multi-platform software designed to split, merge, extract pages, mix and rotate PDF files.
Moniker: pdfsam
Tags:
- pdf
ReleaseNotes: |-
  - Sejda 6.0.0.M7
  - Updated translations and added Armenian
  - Updated dependencies
  - Added support for reading Brotli compressed streams
  - Fixed sambox#253: error processing documents with malformed XMP metadata
  - Fixed sejda#515: Split by bookmarks: control characters in bookmark titles no longer end up in generated file names
  - Fixed sejda#265: Extract: [BASENAME] can now be used alone as output prefix
  - Fixed dialogs not following the application window when moved to a second monitor
ReleaseNotesUrl: https://github.com/torakiki/pdfsam/releases/tag/v6.0.6
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://pdfsam.org/documentation/#basic-documentation
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/torakiki/pdfsam/wiki
- DocumentLabel: FAQ
  DocumentUrl: https://pdfsam.org/faq/#faq-pdfsam-basic
ManifestType: defaultLocale
ManifestVersion: 1.12.0
