# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Muse.MuseHub
PackageVersion: 3.4.1.2340
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- musehub
ProductCode: MuseHub
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://muse-cdn.com/Muse_Hub.exe
  InstallerSha256: 4632A0CB0FB926AD9C45250F9E1DDE4D64D46B3456CA3894D4AA2E13F0C17FCC
ManifestType: installer
ManifestVersion: 1.12.0
