# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Craftbag.Craftbag
PackageVersion: 0.2.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: craftbag-mcp.exe
  PortableCommandAlias: craftbag-mcp
- RelativeFilePath: craftbag.exe
  PortableCommandAlias: craftbag
UpgradeBehavior: install
Commands:
- craftbag
- craftbag-mcp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-10-04
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/craftbag/craftbag/releases/download/v0.2.2/craftbag-x86_64-pc-windows-msvc.zip
  InstallerSha256: 9384305436C01F5B9DAB96F0C9EF9867FF050900CF1250A6363BDA29AA4D8E6F
ManifestType: installer
ManifestVersion: 1.12.0
