# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MetalBear.mirrord
PackageVersion: 3.267.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: uninstallPrevious
Commands:
- mirrord
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{66331571-6325-4D24-B3B3-21C16E359C97}'
AppsAndFeaturesEntries:
- DisplayVersion: 1.3.2670
  ProductCode: '{66331571-6325-4D24-B3B3-21C16E359C97}'
  UpgradeCode: '{EAFD3591-E78C-4B78-85BF-5FE0E72BB7A2}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/metalbear-co/mirrord/releases/download/3.267.0/mirrord.msi
  InstallerSha256: 39B49FE2B2967E369477090B7143BD30FC9308C2B2C40C10EF3CF9A6117B573A
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
