# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Docker.DockerDesktop
PackageVersion: 4.94.0
InstallerLocale: en-US
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: install --quiet
  SilentWithProgress: install --quiet
  Interactive: install
  Custom: --accept-license --backend=wsl-2 --no-windows-containers
UpgradeBehavior: install
ReleaseDate: 2026-10-02
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://desktop.docker.com/win/main/amd64/241994/Docker%20Desktop%20Installer.exe
  InstallerSha256: A9814E31049D66156477A86614E83365669677733014EC72F74229623FF3890A
- Architecture: arm64
  InstallerUrl: https://desktop.docker.com/win/main/arm64/241994/Docker%20Desktop%20Installer.exe
  InstallerSha256: 2CFDD5F1A325F0F38C02ADDA47FF35AB929DA328684DF5633EA21E522AD79EC5
ManifestType: installer
ManifestVersion: 1.12.0
