# Created with WinGet Tracker using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mg-chao.snow-shot
PackageVersion: 1.2.5
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
ExpectedReturnCodes:
- InstallerReturnCode: 10
  ReturnResponse: packageInUse
UpgradeBehavior: install
ProductCode: SnowShot
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- ProductCode: SnowShot
ElevationRequirement: elevationRequired
InstallationMetadata:
  DefaultInstallLocation: Documents\SnowShot
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mg-chao/snow-apps/releases/download/v1.2.5_snow-shot/snow-shot-1.2.5-windows-x64-offline.exe
  InstallerSha256: 77E59DEA657182243CE18F0B88B1DCBD3FA969F1B01D53DF560D6C5D9C402DFB
ManifestType: installer
ManifestVersion: 1.12.0
