# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CaptainKillSwitch.CaptainKillSwitch
PackageVersion: 0.4.13
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{3C54335F-AFC4-4C4B-A0B4-0D9DB631C2E8}'
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- Publisher: Captain Kill Switch Team
  ProductCode: '{3C54335F-AFC4-4C4B-A0B4-0D9DB631C2E8}'
  UpgradeCode: '{984FC5FB-4BE0-5465-85FF-3FDCFED283B5}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Captain Kill Switch'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/captainkillswitch/downloads/releases/download/v0.4.13/captain-kill-switch-0.4.13-windows-x64.msi
  InstallerSha256: B4B6BBBEBB03D560D7D9F8BF9DB174B8FB20A1A2C735F88D155969E96644E4AF
ManifestType: installer
ManifestVersion: 1.12.0
