# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: HP.HPCloudRecoveryTool
PackageVersion: 2.36.2.1072
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /s
UpgradeBehavior: install
ProductCode: '{8852DA80-3D24-4AF1-BEC8-5BAE8850B5B6}'
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://ftp.hp.com/pub/softpaq/sp174001-174500/sp174296.exe
  InstallerSha256: B23AD852704EC59E703084E8F418F0A1768EF3693252DE2FF5B173E127DAE468
ManifestType: installer
ManifestVersion: 1.28.0
