# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mwo-dk.Coxswain.Terminal
PackageVersion: 2.17.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: coxswain-terminal-v2.17.0-x86_64-pc-windows-msvc/cox.exe
  PortableCommandAlias: cox
- RelativeFilePath: coxswain-terminal-v2.17.0-x86_64-pc-windows-msvc/coxswain.exe
  PortableCommandAlias: coxswain
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mwo-dk/coxswain/releases/download/v2.17.0/coxswain-terminal-v2.17.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 6E5435E3E007D6B1EF43F2E950704713D46CA6F29EC1A7EE3E0D1237AECC08CB
ManifestType: installer
ManifestVersion: 1.12.0
