# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: rustty.Rustty
PackageVersion: 2.17.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{A25A0484-2EEB-4686-96B4-F261DC29A3A3}'
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- ProductCode: '{A25A0484-2EEB-4686-96B4-F261DC29A3A3}'
  UpgradeCode: '{3B253B6F-30AE-53D8-984C-60148C2CAC85}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Rustty'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Aleixenandros/Rustty/releases/download/v2.17.1/Rustty_2.17.1_x64.msi
  InstallerSha256: 8F3506B0D4A05427240C2A558B53B386746AABD798E1BD0876AD0B3F1F9C07BE
ManifestType: installer
ManifestVersion: 1.12.0
