# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: AprilNEA.OpenLogi
PackageVersion: 0.8.13
InstallerType: wix
UpgradeBehavior: install
ReleaseDate: 2026-10-09
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%/Programs/OpenLogi/bin'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AprilNEA/OpenLogi/releases/download/v0.8.13/OpenLogi-v0.8.13-windows-x86_64.msi
  InstallerSha256: AFB456D326135A822D216B21A06113DE8178515B38D5E153B4E167D7927EB6A5
  ProductCode: '{760EB450-B9FE-4442-B153-BF0345F73AA3}'
  AppsAndFeaturesEntries:
  - ProductCode: '{760EB450-B9FE-4442-B153-BF0345F73AA3}'
    UpgradeCode: '{981D0C70-179E-4EE8-8F1E-0EB6877EAE94}'
- Architecture: arm64
  InstallerUrl: https://github.com/AprilNEA/OpenLogi/releases/download/v0.8.13/OpenLogi-v0.8.13-windows-arm64.msi
  InstallerSha256: 15369FECE8B169471726EDBCF2A3A7B1D17B721C4ADC86125178EFA42F4E53CE
  ProductCode: '{A70C8F5A-DA4D-4F4D-864A-8019EAF420A8}'
  AppsAndFeaturesEntries:
  - ProductCode: '{A70C8F5A-DA4D-4F4D-864A-8019EAF420A8}'
    UpgradeCode: '{2A989A66-36FE-4999-ACE2-3E79AE02D12A}'
ManifestType: installer
ManifestVersion: 1.28.0
