# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LasseMarkusRautiainen.TextEditorPro
PackageVersion: 37.3.0
Scope: machine
FileExtensions:
- abap
- adb
- ads
- ahk
- as
- asc
- asm
- asp
- au3
- awk
- bas
- bat
- bi
- c
- carbon
- cbproj
- cf
- cgi
- chpl
- class
- clj
- cljc
- cljs
- cls
- cmake
- cmd
- coffee
- cp
- cpp
- cs
- csl
- css
- d
- dart
- def
- dfm
- di
- diff
- dpk
- dpr
- dproj
- dtd
- dws
- e
- edb
- edn
- elm
- eml
- erl
- es
- ex
- exs
- exw
- fmx
- form
- fs
- gcode
- gd
- gitattributes
- gitignore
- glsl
- go
- gravity
- groovy
- groupproj
- gsh
- gvy
- gy
- h
- hack
- hc11
- hck
- hh
- hpp
- hrl
- htm
- html
- i3
- iecst
- ig
- impl.carbon
- inc
- ini
- ino
- iss
- java
- jl
- js
- json
- json5
- kt
- kts
- lat
- lex
- lisp
- lng
- log
- lua
- m
- m2
- m3
- mak
- make
- matlab
- md
- mg
- mht
- mi
- mk
- ml
- mod
- nc
- nim
- nsi
- obs
- odin
- opml
- pas
- pb
- pbp
- pdf
- php
- pjx
- pl
- pm
- pp
- prg
- ps1
- py
- r
- rb
- rbw
- rc
- rda
- rdata
- rdf
- rds
- red
- reds
- rkt
- rtf
- scala
- sh
- sol
- sql
- st
- svg
- swift
- tcl
- tex
- ts
- txt
- uc
- v
- vb
- vbs
- vrc
- vrcm
- vtl
- wxs
- xml
- xsd
- xsl
- xslt
- yml
- zig
ReleaseDate: 2026-10-04
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://www.texteditor.pro/downloads/TextEditorPro32.exe
  InstallerSha256: B781937144BFE5FF7F0E74A660FD9DF5022F5B4773759C683057E46A56A0E8DA
  ProductCode: '{FC8AD371-A765-4E22-B25F-D5914D7193F1}}_is1'
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://www.texteditor.pro/downloads/TextEditorPro64.exe
  InstallerSha256: ACF5553905A591990174BD7ABD5B9FAECD0DCE8390AE871183A4080976BFD293
  ProductCode: '{FC8AD371-A765-4E22-B25F-D5914D7193F1}}_is1'
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://www.texteditor.pro/downloads/TextEditorPro32.msi
  InstallerSha256: 26F47F82A58603610612AE43D96BE3409080C0174917197F9595E3192C3D7770
  InstallerSwitches:
    InstallLocation: TEXTEDITORPRODIR="<INSTALLDIR>"
  ProductCode: '{93444150-9F94-43EE-84D1-A9CC2BDC4DD9}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{FCD58DD3-3A13-408E-944F-D4A0826C866C}'
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://www.texteditor.pro/downloads/TextEditorPro64.msi
  InstallerSha256: 462F2234D57BECDB98AD03D45CCD276AE0E91A8D57CDB31EAAB1FA0E13F9CA60
  InstallerSwitches:
    InstallLocation: TEXTEDITORPRODIR="<INSTALLDIR>"
  ProductCode: '{78426A2B-297B-4408-9813-F341704D96F8}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{FCD58DD3-3A13-408E-944F-D4A0826C866C}'
ManifestType: installer
ManifestVersion: 1.12.0
