# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.DuplicateFinder
PackageVersion: 2.0.6.8
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Duplicate Finder 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/duplicatefinderx86
  InstallerSha256: 9C1471D2F7815B577292C8EF60887395286BD212B9F1806F718350ABD7D433D6
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/duplicatefinderx64
  InstallerSha256: AF5FA80B8E5F988F3DC040CF6C0B1063872EAE0E16A44E35CDC19BDE3100D369
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/duplicatefinderarm64
  InstallerSha256: 211BDFA7221A388A1E286541D0B9A29EEC4B8410B3DD8B1511B03F383E4431E1
ManifestType: installer
ManifestVersion: 1.12.0
