# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: electerm.electerm
PackageVersion: 5.5.76
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: cdebb73f-ddf5-57cd-a4a4-998a5c7283dd
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- DisplayName: electerm 5.5.76
  ProductCode: cdebb73f-ddf5-57cd-a4a4-998a5c7283dd
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/electerm/electerm/releases/download/v5.5.76/electerm-5.5.76-win-x64-installer.exe
  InstallerSha256: F22AFD451B6F020B65E8DFD1EA639900EDBEE5A61A62DD77076695731C74BA5D
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/electerm/electerm/releases/download/v5.5.76/electerm-5.5.76-win-x64-installer.exe
  InstallerSha256: F22AFD451B6F020B65E8DFD1EA639900EDBEE5A61A62DD77076695731C74BA5D
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/electerm/electerm/releases/download/v5.5.76/electerm-5.5.76-win-arm64-installer.exe
  InstallerSha256: B5E66C6C512AA9EA9251E1AF071610137D62A8A40BCECF36FA0AEF7C2A97BE4C
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/electerm/electerm/releases/download/v5.5.76/electerm-5.5.76-win-arm64-installer.exe
  InstallerSha256: B5E66C6C512AA9EA9251E1AF071610137D62A8A40BCECF36FA0AEF7C2A97BE4C
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
