# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.en-GB
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win32/en-GB/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: 540DAD7E9D477477F354B07546D7F649A7B15854F5872B66D2A7DB4A3D969D58
  ProductCode: Mozilla Thunderbird 157.0.1 (x86 en-GB)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win64/en-GB/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: 4B346E97E782CFC03F374EC1E132DCB639B7366F0E8830D56AA75214EF4EEBCA
  ProductCode: Mozilla Thunderbird 157.0.1 (x64 en-GB)
ManifestType: installer
ManifestVersion: 1.12.0
