# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JetBrains.dotTrace
PackageVersion: 2026.2.3.1
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /Silent=True
  SilentWithProgress: /Silent=True
  Log: /LogFile="<LOGPATH>"
FileExtensions:
- dtp
- dtt
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.jetbrains.com/resharper/dotUltimate.2026.2.3.1/JetBrains.dotTrace.2026.2.3.1.web.exe
  InstallerSha256: 99C3D8A04F363B6BDD60A54E1275FD21240B5E4D85FABC938977BBE7F8977C4F
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.jetbrains.com/resharper/dotUltimate.2026.2.3.1/JetBrains.dotTrace.2026.2.3.1.web.exe
  InstallerSha256: 99C3D8A04F363B6BDD60A54E1275FD21240B5E4D85FABC938977BBE7F8977C4F
  InstallerSwitches:
    Custom: /PerMachine=True
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
