# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Anchore.Grype
PackageVersion: 0.120.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: grype.exe
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/anchore/grype/releases/download/v0.120.0/grype_0.120.0_windows_amd64.zip
  InstallerSha256: 024927F5CAEFDC05AA4F98453E269A40E9A82978A142DACAF18C67FCAB378810
ManifestType: installer
ManifestVersion: 1.28.0
