# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Zen-Team.Zen-Browser
PackageVersion: 1.23.1b
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
  Custom: /DesktopShortcut=false
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Zen Browser
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/1.23.1b/zen.installer.exe
  InstallerSha256: C647C7989B547EA31907F649136836B708FEFF203A67DA6CA50E6315B3FFC2AC
- Architecture: arm64
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/1.23.1b/zen.installer-arm64.exe
  InstallerSha256: EB54F1E71FD84097D12C0634515D1E205D88B0E0BA8849C0B398DF8E2024BF87
ManifestType: installer
ManifestVersion: 1.28.0
