# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KhanhKit.PxGo
PackageVersion: 0.8.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pxgo.exe
  PortableCommandAlias: pxgo
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/khanhkit/pxgo/releases/download/v0.8.1/pxgo_windows_amd64.zip
  InstallerSha256: EC3352F67689E895EDF774797C25D90910E44D8035E185D4D01A11C18057206C
- Architecture: arm64
  InstallerUrl: https://github.com/khanhkit/pxgo/releases/download/v0.8.1/pxgo_windows_arm64.zip
  InstallerSha256: 45BE1FD059CD538B2E054B75227C6D27EEC22753B7317A0A670B0352BD90A90C
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-02
