# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: jcardama.LeopardWM
PackageVersion: 0.3.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Commands:
- leopardwm
- leopardwm-cli
- lwm
ProductCode: '{4588190F-2BD3-4577-BC20-B22EC24C060B}'
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- ProductCode: '{4588190F-2BD3-4577-BC20-B22EC24C060B}'
  UpgradeCode: '{EE10F2D5-DA80-43EA-B4D4-A0D37C69DE83}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\LeopardWM\bin'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jcardama/LeopardWM/releases/download/v0.3.1/LeopardWM-0.3.1-x86_64.msi
  InstallerSha256: 73BE6AE4FD651C76B1024C573D5CACE58A5849371361D4CC95632267518A214A
ManifestType: installer
ManifestVersion: 1.12.0
