# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Chill-Astro.Lamina
PackageVersion: 11.28000.19.0
InstallerType: inno
Scope: machine
ProductCode: '{633C1E5F-90A3-492B-933F-84ECEE95A462}_is1'
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- DisplayName: Lamina ✦ Installer Helper
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Chill-Astro\Lamina'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Chill-Astro/Lamina-Calculator/releases/download/v11.28000.19.0/Setup.exe
  InstallerSha256: D44B4BF5D9EED17B8A56998C2D72580318958239600D08D147B8EA515727ED85
ManifestType: installer
ManifestVersion: 1.12.0
