# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Servo.Servo.Nightly
PackageVersion: "1.0"
InstallerType: burn
Scope: machine
Protocols:
- http
- https
ProductCode: '{F9D6BD69-94FB-4776-81D4-7114F5FD5EA4}'
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- DisplayName: ServoShell
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/servo/servo-nightly-builds/releases/download/2026-10-03/servo-x86_64-windows-msvc.exe
  InstallerSha256: 5892FA21AB97646047B482A66762090507A53330E0BB6699D47CABD82BAD4BC1
ManifestType: installer
ManifestVersion: 1.12.0
