# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: kcl-lang.kcl
PackageVersion: 0.13.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: kcl.exe
UpgradeBehavior: install
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kcl-lang/cli/releases/download/v0.13.1/kcl-v0.13.1-windows-amd64.zip
  InstallerSha256: F4DD8E0B57BB22012FED3B282087D645747032788F83ED05BB8CE793D0F22171
- Architecture: arm64
  InstallerUrl: https://github.com/kcl-lang/cli/releases/download/v0.13.1/kcl-v0.13.1-windows-arm64.zip
  InstallerSha256: 745F22C88C0003C49930BD7765990A92E12BBDD11994E0306EB0113F44F89255
ManifestType: installer
ManifestVersion: 1.12.0
