# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json
PackageIdentifier: Microsoft.VisualStudio.Professional       # i.e. Microsoft.VisualStudio.Community.Insiders
PackageVersion: 18.9.2             # i.e. 18.0.11010.61
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
