# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Corsinvest.cv4pve.pepper
PackageVersion: 2.0.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cv4pve-pepper.exe
  PortableCommandAlias: cv4pve-pepper
ReleaseDate: 2026-09-29
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Corsinvest/cv4pve-pepper/releases/download/v2.0.1/cv4pve-pepper.exe-win-x86.zip
  InstallerSha256: E68E6E45B23A73D328C7C69B6A023624282FCF0A37949B3664F170BC8B9F4BFE
- Architecture: x64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-pepper/releases/download/v2.0.1/cv4pve-pepper.exe-win-x64.zip
  InstallerSha256: FD67D72E420918E54ABC5C2E515E1A07D0EECB6E3B5182E8DC3BB29C1ADD961B
- Architecture: arm64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-pepper/releases/download/v2.0.1/cv4pve-pepper.exe-win-arm64.zip
  InstallerSha256: F1C3FBC5C354E4F97BC9093D90C7485D589F0ED27CBE7EC47CBDDB7D751C6CEC
ManifestType: installer
ManifestVersion: 1.12.0
