# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ActiveDirectoryPro.ADProToolkit
PackageVersion: 3.2.7
InstallerType: msi
Scope: machine
InstallerSwitches:
  InstallLocation: APPDIR="<INSTALLPATH>"
ProductCode: '{B6FD60B6-A08A-4079-A69A-F10A4BF92B24}'
ReleaseDate: 2026-10-02
AppsAndFeaturesEntries:
- UpgradeCode: '{0974AC06-5134-4B50-BAD1-578FDABD2EF8}'
Installers:
- Architecture: x64
  InstallerUrl: https://store.activedirectorypro.com/downloads/ADProToolkit.msi
  InstallerSha256: C7376E684BC64A74B39C269AED0A19E9C5C5CEA579A481EF763A8D2DD4D85055
ManifestType: installer
ManifestVersion: 1.12.0
