# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: teoslayer.shell.online
PackageVersion: 0.24.1
InstallerType: portable
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
Commands:
- shell
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/TeoSlayer/shell.online/releases/download/v0.24.1/shell-windows-386.exe
  InstallerSha256: 8D054A03A6B459E4AA9A82AA4F0541549DC310984A3C510EA00A26DA2CD2EEEB
- Architecture: x64
  InstallerUrl: https://github.com/TeoSlayer/shell.online/releases/download/v0.24.1/shell-windows-amd64.exe
  InstallerSha256: 843F74B252E8A265EE68D2B92CDD595107E00A80F485F05BA405DE1F2F4A6AB0
- Architecture: arm64
  InstallerUrl: https://github.com/TeoSlayer/shell.online/releases/download/v0.24.1/shell-windows-arm64.exe
  InstallerSha256: F4BA9D5253379241143F90299C51092338FD6BE0044ABC5EB022E405452BE23A
ManifestType: installer
ManifestVersion: 1.28.0
