# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Superhuman.Superhuman
PackageVersion: 1041.0.69
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- mailto
- superhuman
ProductCode: 49b7df64-6557-59ab-9b2b-f97a2de29e77
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://download.superhuman.com/native-update/Superhuman%20Setup%201041.0.69-latest.exe
  InstallerSha256: 95BE7B8A37E6E0CA13A31F0709EAB9F3FE458AF9CFF2B1108F3936370C8B7FE2
- Architecture: arm64
  InstallerUrl: https://download.superhuman.com/native-update/Superhuman%20Setup%201041.0.69-latest.exe
  InstallerSha256: 95BE7B8A37E6E0CA13A31F0709EAB9F3FE458AF9CFF2B1108F3936370C8B7FE2
ManifestType: installer
ManifestVersion: 1.12.0
