# Created with WinGet Tracker using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: zerx-lab.FluxDown
PackageVersion: 0.5.4
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /CURRENTUSER
UpgradeBehavior: install
ProductCode: '{B7E3F2A1-5C4D-4E8F-9A6B-1D2E3F4A5B6C}_is1'
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- ProductCode: '{B7E3F2A1-5C4D-4E8F-9A6B-1D2E3F4A5B6C}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\FluxDown'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zerx-lab/FluxDown/releases/download/v0.5.4/FluxDown-0.5.4-windows-x64-setup.exe
  InstallerSha256: 6FD5FEEC03182A8676A20F7BE69EF054318C4491B4192C93E2B587E42042409C
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/zerx-lab/FluxDown/releases/download/v0.5.4/FluxDown-0.5.4-windows-arm64-setup.exe
  InstallerSha256: B1D862073BD93F087571AB3DD8C233565E88B50C4D350EF7B29A99AB726F99B1
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
