# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.Azd
PackageVersion: 1.35.200
InstallerLocale: en-US
InstallerType: wix
InstallerSwitches:
  Custom: INSTALLEDBY="winget"
ProductCode: '{EC74A925-98E8-4EBB-9FBD-414B00AB2590}'
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/8e24abae-5936-48e8-9d1f-f0749ec8c3f2/08f31dd9-57a0-438c-b944-32936f5fa1ff/azd-windows-amd64.msi
  InstallerSha256: 206CD6BF6FFB070ADF8BB4713B598BFBA9716E87D54F8B08C587AC53B6045213
ManifestType: installer
ManifestVersion: 1.12.0
