# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: misxzaiz.Polaris
PackageVersion: 10.6.4
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{39826E9E-6849-4C04-892E-49C1A914AF60}'
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- UpgradeCode: '{B90F6FC4-DDEE-59A6-9DE8-49A41A495360}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/misxzaiz/Polaris/releases/download/v10.6.4/polaris_10.6.4_x64_en-US.msi
  InstallerSha256: 34B38A8AEFFB72BB7F98455C649F682AFB8F30F56D518EFE6C19A32F840F879B
ManifestType: installer
ManifestVersion: 1.12.0
