# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: misxzaiz.Polaris
PackageVersion: 10.6.3
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{DF35AC63-8042-4A4F-A6A3-F51C62A9AD33}'
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- UpgradeCode: '{B90F6FC4-DDEE-59A6-9DE8-49A41A495360}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/misxzaiz/Polaris/releases/download/v10.6.3/polaris_10.6.3_x64_en-US.msi
  InstallerSha256: 7F98D36895A6035CE31E328084BA7E327B7C15D1DC55B1628CCF7DE9D4CF8DBC
ManifestType: installer
ManifestVersion: 1.12.0
