# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.308
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.308/anchors_0.1.308_windows_amd64.zip
  InstallerSha256: DBD595D3BF9BA685EC611E33817AA41270497BF8BF394A3147B4613208A0E131
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.308/anchors_0.1.308_windows_arm64.zip
  InstallerSha256: 08525BEB330E7EE0F1D180F10853D5D1FD25BE1689E44DA4B3B1EE7B185B9181
ManifestType: installer
ManifestVersion: 1.12.0
