# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Kaedei.Dandanplay
PackageVersion: 18.2.0
PackageLocale: zh-CN
Publisher: Kaedei
PublisherUrl: https://www.dandanplay.com/
PublisherSupportUrl: https://www.dandanplay.com/contact.html
PrivacyUrl: https://www.dandanplay.com/privacy.html
Author: Kaedei
PackageName: 弹弹play
PackageUrl: https://www.dandanplay.com/
License: 免费软件
Copyright: Copyright © Kaedei 2012-2026
ShortDescription: 全功能“本地视频+弹幕”播放器
Tags:
- 动漫
- 动画
- 多媒体
- 媒体
- 弹幕
- 影音
- 播放器
- 视频
ReleaseNotes: |-
  更新内容：
  - 现在需要先注册并登录弹弹 play 账号才能使用相关在线服务；
  - 优化用户中心登录、注册、找回密码、邮箱验证等相关流程；
  - 当播放器加载和播放失败时，使用统一的错误窗口显示问题原因；
  - 『弹幕外挂』控制台窗口合并至播放器主窗口，不再有窗口丢失、状态错误等问题出现；
  - 在线观看功能支持 Kazumi 源；
  - 远程媒体库支持连接到阿里云盘；
  - 远程媒体库支持通过 SFTP 连接到服务器；
  - 新增弹幕 GPU 渲染（实验性），需要在设置中开启；
  - 更新了部分缺失的多国语言翻译；
  - 修复了显示 SRT 字幕时可能漏掉最后一句字幕的问题；
  - 修复了 DirectVobSub 相关的字幕显示问题；
  - 修复了使用 v3+ 下载内核时，下载出错可能导致主程序退出的问题；
  - 修复了使用 VLC 内核并关闭弹弹 play 字幕渲染器时，部分情况下无法显示字幕的问题；
  - 修复了媒体库刷新时可能会报错的问题；
  - 修复了 libass 可能和部分组件冲突的问题；
  - 修复了部分情况下进程没有正确退出的问题；
  - 修复了自动下载功能与 qBittorrent 5.0 相关的兼容性问题；
  - 修复了自动下载 RSS 解析的问题并优化了检查时机；
  - 修复了 5dm 插件的弹幕解析问题；
  - 修复了部分情况下媒体库后台刷新异常问题；
  - 修复了远程媒体库中与 Jellyfin 12 版本的兼容性问题；
  - 修复了暗黑模式下部分颜色错误的问题；
  - 完善了启动失败的检测机制，启动失败时会记录相关问题日志并提示用户。
ReleaseNotesUrl: https://www.dandanplay.com/blog.html
ManifestType: locale
ManifestVersion: 1.12.0
