# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.vi
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win32/vi/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: E6A3B2B929110A6E74BBF82B7AE36EF28898833A2A635CE3DC4434CA93725B29
  ProductCode: Mozilla Thunderbird 153.4.0 (x86 vi)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 vi)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win64/vi/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: 07CBBA1FEB73151F176F73ADAD9ECA015ACBA5D573805C1DE355713CBCEF0783
  ProductCode: Mozilla Thunderbird 153.4.0 (x64 vi)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 vi)
ManifestType: installer
ManifestVersion: 1.12.0
