# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: FlowDevs.PrimeDictate
PackageVersion: 6.1.1
InstallerType: wix
Scope: machine
InstallerSwitches:
  Custom: LAUNCHATLOGIN=0
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/flowdevs-io/PrimeDictate/releases/download/v6.1.1/PrimeDictate-Setup-v6.1.1-x64.msi
  InstallerSha256: F73BEF9F8AF63975F30173FD067527697EBA97087E6619E1B2C33E4E7969E8F6
  ProductCode: " {8C0B48E4-09B9-4D37-B328-8BFDFC9A24F0}"
- Architecture: arm64
  InstallerUrl: https://github.com/flowdevs-io/PrimeDictate/releases/download/v6.1.1/PrimeDictate-Setup-v6.1.1-arm64.msi
  InstallerSha256: CFB5B68911498B94F1EF47C47B1448E9DF5CB90322B41128BE003182A6AB0A3A
  ProductCode: " {62BDB20C-CB98-4B41-B924-684A60AD96C8}"
ManifestType: installer
ManifestVersion: 1.10.0
