# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: misxzaiz.Polaris
PackageVersion: 10.6.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{15B2B05D-1A72-4A58-8680-81C1F96D51EE}'
ReleaseDate: 2026-10-02
AppsAndFeaturesEntries:
- UpgradeCode: '{B90F6FC4-DDEE-59A6-9DE8-49A41A495360}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/misxzaiz/Polaris/releases/download/v10.6.0/polaris_10.6.0_x64_en-US.msi
  InstallerSha256: EDB09216FC62E0182DF25D5D6EDF4E4C71A02412D543132FE1AC1E1190352F2E
ManifestType: installer
ManifestVersion: 1.12.0
