# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Dataflare.Dataflare
PackageVersion: 3.2.4
InstallerType: nullsoft
Scope: user
ProductCode: Dataflare
ReleaseDate: 2026-10-02
AppsAndFeaturesEntries:
- Publisher: dataflare
  ProductCode: Dataflare
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Dataflare'
Installers:
- Architecture: x64
  InstallerUrl: https://assets.dataflare.app/release/windows/x86_64/Dataflare-Setup-3.2.4.exe
  InstallerSha256: 5F82E8F31BE83F30FCE318C4CA1F2E9FAF3F19AD676CC07440BAAFEDC2128366
- Architecture: arm64
  InstallerUrl: https://assets.dataflare.app/release/windows/aarch64/Dataflare-Setup-3.2.4.exe
  InstallerSha256: 387AE0FD775A373ACA77240898B4C6E1CFC40974F35A02CE1EA65B08FA83BA83
ManifestType: installer
ManifestVersion: 1.28.0
