# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.274
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.274/anchors_0.1.274_windows_amd64.zip
  InstallerSha256: 25A22E21CB79A2543C60BF4D28450DE806D00CA6C1056C09E6E1C693A8CF51E0
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.274/anchors_0.1.274_windows_arm64.zip
  InstallerSha256: 34543B6BE262B12B5ACB3017ED5CF2332454221F84E8E99F0ACB9C8B3BFF1AF2
ManifestType: installer
ManifestVersion: 1.12.0
