# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FedeB2160.WinGetStudio
PackageVersion: 1.11.1
InstallerLocale: en-US
InstallerType: inno
UpgradeBehavior: uninstallPrevious
ProductCode: '{80A0A054-6278-4145-AD5A-2B3C4853019F}_is1'
AppsAndFeaturesEntries:
- ProductCode: '{80A0A054-6278-4145-AD5A-2B3C4853019F}_is1'
  InstallerType: inno
- ProductCode: FedeB2160.WinGetStudio_Microsoft.Winget.Source_8wekyb3d8bbwe
  InstallerType: portable
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/FedeB2160/WinGetStudio/releases/download/v1.11.1/WinGetStudio_Setup.exe
  InstallerSha256: A06E9F69E23859E8AE84ECA749DF59FCB1005120DC32984B74EE7AF19C9D305E
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-09
