# Automatically updated by the winget bot at 2026/Oct/03
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Serverdata.Ascend
PackageVersion: 2.33.58.0
UpgradeBehavior: install
Protocols:
- ascendmeetings
ReleaseDate: 2026-07-28
Installers:
- Architecture: x86
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://cp.serverdata.net/Voice/Pbx/SoftPhoneReleases/Ascend/Latest-Win/ascend-uc-ia32.msi
  InstallerSha256: 84BCB2E881226D65AEE0F5A3A9B82D1EA121B657E6AE781545666DABD5C77B57
  InstallerSwitches:
    InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
  ProductCode: '{B1F65356-28D3-4958-BBC0-A91215368608}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{F6C37FB9-FF59-447F-89D1-F9685A4FCC01}'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://cp.serverdata.net/Voice/Pbx/SoftPhoneReleases/Ascend/Latest-Win/ascend-uc-x64.msi
  InstallerSha256: B6C4E264B83816279DAE536CE4AC3934F93273DA425F539F8CE4A18848A15D92
  InstallerSwitches:
    InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
  ProductCode: '{9C89C9AD-7BC1-4589-B8D1-75B0A9354479}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{F6C37FB9-FF59-447F-89D1-F9685A4FCC01}'
ManifestType: installer
ManifestVersion: 1.28.0
