# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: wl-std.pulse
PackageVersion: "2.2"
InstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
- Architecture: x64
  InstallerUrl: https://dl1.wl-std.com/Pulse-2.2-Setup.exe
  InstallerSha256: D0778D354E534EBA716C0876CA6719EC91FDFE4E99784404E76EB5CE7CCD9ADF
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
