# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: DigitalScholar.Zotero
PackageVersion: 10.0.6
PackageLocale: en-US
Publisher: Corporation for Digital Scholarship
PublisherUrl: https://digitalscholar.org/
PublisherSupportUrl: https://www.zotero.org/support/
PrivacyUrl: https://www.zotero.org/support/privacy
Author: Corporation for Digital Scholarship
PackageName: Zotero
PackageUrl: https://www.zotero.org/
License: AGPL-3.0
LicenseUrl: https://www.zotero.org/support/licensing
Copyright: © Corporation for Digital Scholarship
CopyrightUrl: https://www.zotero.org/support/terms/trademark
ShortDescription: Your personal research assistant
Description: Zotero is a free, easy-to-use tool to help you collect, organize, annotate, cite, and share research.
Tags:
- academics
- article
- citation
- cite
- literature
- paper
- research
- thesis
ReleaseNotes: |-
  - Fixed Find Full Text not finding files on some sites
  - Fixed Find Full Text stalling on various server errors
  - [Mac] Re-enabled local voices in Read Aloud on macOS 27 and fixed clicking after each sentence
  - Fixed slow rendering of PDFs with JPEG2000 images
  - [Security] Updated Mozilla platform to 140.17.0esr
  - [Developer] Local API: Decode + as a space in form-encoded requests
ReleaseNotesUrl: https://www.zotero.org/support/changelog#changes_in_1006_october_7_2026
ManifestType: defaultLocale
ManifestVersion: 1.12.0
