# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EarendilWorks.pi
PackageVersion: 1.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pi.exe
Commands:
- pi
ReleaseDate: 2026-10-01
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/earendil-works/pi/releases/download/v1.0.0/pi-windows-x64.zip
  InstallerSha256: F7DBD39814BF6763F01E7F688AD089615DE1D0EB55FC8915A49ACDC2088F4404
- Architecture: arm64
  InstallerUrl: https://github.com/earendil-works/pi/releases/download/v1.0.0/pi-windows-arm64.zip
  InstallerSha256: 122D3A1825EAC4AA17081C769188C1D058FEBF579A9407091AE829626997EA96
ManifestType: installer
ManifestVersion: 1.12.0
