# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Gologin.Gologin
PackageVersion: 4.22.2
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: e254751a-2537-5636-8393-c4573034c5f6
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- ProductCode: e254751a-2537-5636-8393-c4573034c5f6
Installers:
- Architecture: x64
  InstallerUrl: https://releases.gologin.com/Gologin%20Setup%204.22.2.exe
  InstallerSha256: B246301680E099B5DBBC8C0D4C4B982E67B9A00915F4E6D8E4EB3405E82088DA
ManifestType: installer
ManifestVersion: 1.28.0
