# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: GitHub.CopilotApp
PackageVersion: 1.1.25
UpgradeBehavior: install
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/github/app/releases/download/v1.1.25/GitHub-Copilot-windows-x64-setup.exe
  InstallerSha256: 6CA31B9003DCEEFD434A62D5B58B59E44A07B6083D1628EF5A137039E64B130E
  ProductCode: GitHub Copilot
  AppsAndFeaturesEntries:
  - ProductCode: GitHub Copilot
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\GitHub Copilot'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/github/app/releases/download/v1.1.25/GitHub-Copilot-windows-x64.msi
  InstallerSha256: B5A6D6C971B08E57F877B2A523836A5F025743BA8D0789B942CEEC1E976D48E2
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{E57077E8-639A-46A0-851A-06570632C712}'
  AppsAndFeaturesEntries:
  - ProductCode: '{E57077E8-639A-46A0-851A-06570632C712}'
    UpgradeCode: '{91C1652C-D75F-5DE7-92AE-9BB88EB110EE}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/GitHub Copilot'
- Architecture: arm64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/github/app/releases/download/v1.1.25/GitHub-Copilot-windows-arm64-setup.exe
  InstallerSha256: BE03904EC6DCC61154B24DA9FAB9C272AA23BB0F09DCF5E54A34A2C20839D267
  ProductCode: GitHub Copilot
  AppsAndFeaturesEntries:
  - ProductCode: GitHub Copilot
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\GitHub Copilot'
- Architecture: arm64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/github/app/releases/download/v1.1.25/GitHub-Copilot-windows-arm64.msi
  InstallerSha256: 65D56C1F1D6BFDFC2CFB5E9EC3F52B67CD69A3A0CC7D20B8E6FC0FB09BBB5A4A
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{E3E82C95-1099-4AA1-A383-C3A1F586FE87}'
  AppsAndFeaturesEntries:
  - ProductCode: '{E3E82C95-1099-4AA1-A383-C3A1F586FE87}'
    UpgradeCode: '{91C1652C-D75F-5DE7-92AE-9BB88EB110EE}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/GitHub Copilot'
ManifestType: installer
ManifestVersion: 1.28.0
