# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ggml.llamacpp
PackageVersion: b11515
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: llama-batched-bench.exe
- RelativeFilePath: llama-bench.exe
- RelativeFilePath: llama-cli.exe
- RelativeFilePath: llama-gguf-split.exe
- RelativeFilePath: llama-imatrix.exe
- RelativeFilePath: llama-mtmd-cli.exe
- RelativeFilePath: llama-perplexity.exe
- RelativeFilePath: llama-quantize.exe
- RelativeFilePath: llama-server.exe
- RelativeFilePath: llama-tokenize.exe
- RelativeFilePath: llama-tts.exe
ReleaseDate: 2026-10-09
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ggml-org/llama.cpp/releases/download/b11515/llama-b11515-bin-win-vulkan-x64.zip
  InstallerSha256: 013275BB02719D6DE02107D0E1DACA91462BFC6385AC56712F43DB8418690358
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/ggml-org/llama.cpp/releases/download/b11515/llama-b11515-bin-win-vulkan-arm64.zip
  InstallerSha256: 977096FB02BF60C0E76806BEAA34E0562C927D82E29EA71D395C165489C635C4
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
