# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: CircleCI.CLI
PackageVersion: 1.0.52018
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: circleci.exe
  PortableCommandAlias: circleci
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.52018/circleci-cli_1.0.52018_windows_amd64.zip
  InstallerSha256: 18C003D1AD57C6C7F7B31DCF5DE1243446EE55A7EF3261E2C49300399A1A1E2B
- Architecture: arm64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.52018/circleci-cli_1.0.52018_windows_arm64.zip
  InstallerSha256: D2FB46AA38963A7567F6BF6CBA541E1FEB314B2DADF48906E659D6E693846E45
ManifestType: installer
ManifestVersion: 1.28.0
