# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Lime.Lime
PackageVersion: 1.149.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- lime
ProductCode: lime
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limecloud/lime/releases/download/v1.149.0/Lime-1.149.0.Setup.exe
  InstallerSha256: A8AA61090E568D906097C6305643291713EA90B61DBA00392467DB0FD57979B3
ManifestType: installer
ManifestVersion: 1.12.0
