# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SosomLab.NexaDir
PackageVersion: 0.24.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
AppsAndFeaturesEntries:
- DisplayName: Nexa Dir
  Publisher: SosomLab
  ProductCode: '{D73BE7F2-A2AD-4827-81C2-F4E42B07AA64}'
  UpgradeCode: '{7D1F7E3A-5C2B-4F0E-9A61-3B9D2C8E4F10}'
  InstallerType: wix
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SosomLab/nexa-dir3/releases/download/v0.24.0/nexa-dir-0.24.0-windows-x64.msi
  InstallerSha256: 632534e0c28d6fbce225ca1844f82428d81f6e689a33787529030989770beace
  ProductCode: '{D73BE7F2-A2AD-4827-81C2-F4E42B07AA64}'
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-10
