# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SoftPerfect.RAMDisk
PackageVersion: "26.10"
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: '{33A14ED9-0340-4193-BEDB-B95BC8196182}_is1'
ReleaseDate: 2026-10-04
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://www.softperfect.com/download/files/ramdisk_setup.exe
  InstallerSha256: 21CA228F822D926B7218279BEB580786E5F707F3C88082B96AC8A39CA108E0A4
ManifestType: installer
ManifestVersion: 1.12.0
