# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Devolutions.UniGetUI
PackageVersion: 2026.3.1
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{889610CC-4337-4BDB-AC3B-4F21806C0BDE}_is1'
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- ProductCode: '{889610CC-4337-4BDB-AC3B-4F21806C0BDE}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.devolutions.net/download/Devolutions.UniGetUI.win-x64.2026.3.1.0.exe
  InstallerSha256: B4763D43A927B995D1AEE3C017B5689A1678B8739BCA681A511281E811AE0EA9
  InstallerSwitches:
    Custom: /CURRENTUSER /NoWinGet /NoAutoStart
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.devolutions.net/download/Devolutions.UniGetUI.win-x64.2026.3.1.0.exe
  InstallerSha256: B4763D43A927B995D1AEE3C017B5689A1678B8739BCA681A511281E811AE0EA9
  InstallerSwitches:
    Custom: /ALLUSERS /NoWinGet /NoAutoStart
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\UniGetUI'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://cdn.devolutions.net/download/Devolutions.UniGetUI.win-arm64.2026.3.1.0.exe
  InstallerSha256: 8E04F9BAD59C561EF1FB9F3B82853911ABA77C2124B6335536951A15CE093830
  InstallerSwitches:
    Custom: /CURRENTUSER /NoWinGet /NoAutoStart
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://cdn.devolutions.net/download/Devolutions.UniGetUI.win-arm64.2026.3.1.0.exe
  InstallerSha256: 8E04F9BAD59C561EF1FB9F3B82853911ABA77C2124B6335536951A15CE093830
  InstallerSwitches:
    Custom: /ALLUSERS /NoWinGet /NoAutoStart
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\UniGetUI'
ManifestType: installer
ManifestVersion: 1.12.0

