# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Consumer.Windows
PackageVersion: 16.1.1.6
InstallerLocale: pt-BR
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://files.consumer.com.br/public/setup/Setup-Consumer-16.1.1.6.exe
  InstallerSha256: 6df97dfe18329d32ec5f0e22b304160e524304f19cb6224d6db75ac348dc3cb0
  ProductCode: Consumer
  AppsAndFeaturesEntries:
  - DisplayName: Consumer
    Publisher: Consumer Soluções em Tecnologia Ltda
    DisplayVersion: 16.1.1.6
    ProductCode: Consumer
    InstallerType: exe
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-09-21
