# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.lt
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/lt/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 0D923CA973ECB5459501F0DE19D4A145CF7BD4D21F1C7516A537C66283D0E096
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/lt/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 55DB3AD14ED430D3FBF3FB8A2A530489BA1D2D6CEC5D6E1A8B4D916B429BAB3A
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/lt/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: DC93474683BF1188286021EB49DEC0F91980DBDD603D1F02B0C3AD009C4AAD1A
ManifestType: installer
ManifestVersion: 1.12.0
