# Created with winget-pkgs-updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: alecdotdev.Markpad
PackageVersion: 2.8.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- md
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
ProductCode: Markpad
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- ProductCode: Markpad
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Markpad'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sftwrdotdev/Markpad/releases/download/v2.8.1/Markpad_2.8.1_x64-setup.exe
  InstallerSha256: BFD7C4862D564097A092B4486DA430EDE81700EB57C13D6E8DA35CB3E8F49C79
- Architecture: arm64
  InstallerUrl: https://github.com/sftwrdotdev/Markpad/releases/download/v2.8.1/Markpad_2.8.1_arm64-setup.exe
  InstallerSha256: EFF71830B03A418D3A9FF8B1C2C963EA8EBD7062855D9D6B40D193C5DD7BCC39
ManifestType: installer
ManifestVersion: 1.12.0
