# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MangoDisk.CLI
PackageVersion: 1.1.6
InstallerType: portable
UpgradeBehavior: install
Commands:
- mangodisk
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/harry0703/MangoDisk/releases/download/v1.1.6/MangoDisk-1.1.6-windows-cli.exe
  InstallerSha256: 6D7F944499B09C454A657057ADED1CA6ECA356E714628A1D1FA6CBF669DF8DB4
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-04
