# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Hibbiki.Chromium
PackageVersion: 154.0.8037.98
InstallerType: exe
InstallModes:
- silent
UpgradeBehavior: install
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/Hibbiki/chromium-win64/releases/download/v154.0.8037.98-r1689415/mini_installer.exe
  InstallerSha256: 3775B601EB777A0040610821373B59967D006F0808B31252F8E37F21E160155F
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/Hibbiki/chromium-win64/releases/download/v154.0.8037.98-r1689415/mini_installer.exe
  InstallerSha256: 3775B601EB777A0040610821373B59967D006F0808B31252F8E37F21E160155F
  InstallerSwitches:
    Custom: --system-level
ManifestType: installer
ManifestVersion: 1.12.0
