# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: PlanetScale.CLI
PackageVersion: 0.342.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pscale.exe
Commands:
- pscale
ReleaseDate: 2026-10-02
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.342.0/pscale_0.342.0_windows_386.zip
  InstallerSha256: 0F93C767224EAC247A7782DAA65FAC39E1ADC255CDA1589795B5C2D2FAA58833
- Architecture: x64
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.342.0/pscale_0.342.0_windows_amd64.zip
  InstallerSha256: 62F31E221E4F8E97A174FD35E35113852D0D0E60DB9F8032D769B8D5CE94DF77
- Architecture: arm64
  InstallerUrl: https://github.com/planetscale/cli/releases/download/v0.342.0/pscale_0.342.0_windows_arm64.zip
  InstallerSha256: A82B2ADB329945FC369BF5FE4B5626F83738F37154069575B891C22C282FE4A0
ManifestType: installer
ManifestVersion: 1.28.0
