# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.AntigravityCLI
PackageVersion: 1.2.17
InstallerType: portable
Commands:
- agy
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://storage.googleapis.com/antigravity-public/antigravity-cli/1.2.17-6683332533157888/windows-x64/cli_windows_x64.exe
  InstallerSha256: 6224A54C35D31B9B85232BBFB23E3306002C418481930442519743FAB585F65A
- Architecture: arm64
  InstallerUrl: https://storage.googleapis.com/antigravity-public/antigravity-cli/1.2.17-6683332533157888/windows-arm/cli_windows_arm64.exe
  InstallerSha256: 5F7CE5BCCDCCB72DA9C5882262A3BC433B8836AE6B88F74112D5CA14B7F5E755
ManifestType: installer
ManifestVersion: 1.12.0
