# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.GeminiDesktop
PackageVersion: 1.13.1
InstallerType: nullsoft
Scope: user
ProductCode: Gemini
ReleaseDate: 2026-09-25
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/Google%20DeepMind/addznku7or7dm5tq34obrljjxjxq_1.13.1/GeminiSetup-1.13.1_uncompressed.exe
  InstallerSha256: E660BFD7BF1BFFFCE65D8227BF8DC8CAED34317110EC5139AE3ACE5BCB5AAA94
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/Google%20DeepMind/adxgwi777onjspkiyhmhq4nmn7ca_1.13.1/GeminiSetup-1.13.1_uncompressed.exe
  InstallerSha256: 0B1A7D5384B9D08C1A0512A38A86B5002F313E9197781A1EFDD0D213B399901E
ManifestType: installer
ManifestVersion: 1.12.0
