# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AurelioAvila.Redaxa
PackageVersion: 0.4.11
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
ProductCode: Redaxa
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- ProductCode: Redaxa
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Redaxa'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AurelioAvila/redaxa/releases/download/v0.4.11/Redaxa_0.4.11_x64-setup.exe
  InstallerSha256: C5AF96BA03671D327A62DD49BB33970AE676E203626C78C44B43A990F905A2D8
ManifestType: installer
ManifestVersion: 1.12.0
