# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SiakHooi.Json2Table
PackageVersion: 1.2.0
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: json2table.exe
  PortableCommandAlias: json2table
UpgradeBehavior: install
Commands:
- json2table
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SiakHooi/Json2Table/releases/download/v1.2.0/json2table_1.2.0_Windows_x86_64.zip
  InstallerSha256: fcf5fce017aa315d5295d201aae106dfb1005d15579c1eb2c54fe6927f7a44f9
- Architecture: arm64
  InstallerUrl: https://github.com/SiakHooi/Json2Table/releases/download/v1.2.0/json2table_1.2.0_Windows_arm64.zip
  InstallerSha256: fea5006000d92a68f06594164a127a9062c67b3c6ceca1aa8322fd444aa75229
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-04
