# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.th
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win32/th/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: CE284593C87A984CA894F526C3EA41FA25D96988DCB34F5EF84026284088192F
  ProductCode: Mozilla Thunderbird 153.4.0 (x86 th)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 th)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win64/th/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: 1A99507B28AE46FEE568FE5FEA0701429FE5307C39EEC0F9B41A83EE3073AAEC
  ProductCode: Mozilla Thunderbird 153.4.0 (x64 th)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 th)
ManifestType: installer
ManifestVersion: 1.12.0
