# Automatically updated by the winget bot at 2026/Oct/09
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: ReincubateLtd.CamoStudio
PackageVersion: 2.9.2.25892
InstallerLocale: en-US
InstallerType: wix
Installers:
- Architecture: x64
  InstallerUrl: https://reincubate.com/res/labs/camo/camo-windows-latest.msi
  InstallerSha256: 777B5F90E2BCBBB741EE7D56A391DE376A5A24CD07C751D59F79CDF0CC01336F
  ProductCode: '{C6D65CF8-797E-4F8B-A8C4-82FD88E7423B}'
ManifestType: installer
ManifestVersion: 1.28.0
