# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: pnpm.pnpm
PackageVersion: 12.10.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pnpm.exe
  PortableCommandAlias: pnpm
Commands:
- pnpm
ReleaseDate: 2026-10-06
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/pnpm/pnpm/releases/download/v12.10.1/pnpm-win32-x64.zip
  InstallerSha256: 299009317554B82905927F8E9782EC5F0AFB08EB7B5CC5EB2B15A923CB1A56EF
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/pnpm/pnpm/releases/download/v12.10.1/pnpm-win32-arm64.zip
  InstallerSha256: 67C0980C2223D2F89B46CEEDB09CAAA37BFAB075D8319D0E651EB659D00C66E9
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
