# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.da
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win32/da/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: 9473DE62159E2A6B40E1B86EA0E5364EBCA52245DE70D2ECB59D366C7DE54A29
  ProductCode: Mozilla Thunderbird 153.4.0 (x86 da)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 da)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win64/da/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: 278A9C7B6D8E5BE088E80D17B00EDD20CC80F1473D29D1E8C8A60F9DD9F76F48
  ProductCode: Mozilla Thunderbird 153.4.0 (x64 da)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 da)
ManifestType: installer
ManifestVersion: 1.12.0
