# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.Chrome.Canary
PackageVersion: 157.0.8083.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Log: --verbose-logging --log-file="<LOGPATH>"
  Custom: --chrome-sxs --do-not-launch-chrome
ExpectedReturnCodes:
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 4
  ReturnResponse: downgrade
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Google Chrome
ReleaseDate: 2026-10-02
Installers:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/cpzgjebnr4cig3vy7ysgajpwyu_157.0.8083.0/157.0.8083.0_chrome_installer_uncompressed.exe
  InstallerSha256: 02FFD38691FF4AD23CBFAB4E30326C5EE0DF460EFB0C98017C6989F9B55FB12E
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/ketbjcevrjb4t2jwvb36crbvbu_157.0.8083.0/157.0.8083.0_chrome_installer_uncompressed.exe
  InstallerSha256: 391441C09E2D9407251934CE30CFE1E28497E693DF195710E89B8B291FB2A0BD
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/ad5ljvgy3ijr6htjh5zqty3vl4yq_157.0.8083.0/157.0.8083.0_chrome_installer_uncompressed.exe
  InstallerSha256: 7492DEB366C28F393838731201A70530D61D7069DB13F60634184777684185CC
ManifestType: installer
ManifestVersion: 1.12.0
