# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mwo-dk.Coxswain.Terminal
PackageVersion: 2.8.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: coxswain-terminal-v2.8.2-x86_64-pc-windows-msvc/cox.exe
  PortableCommandAlias: cox
- RelativeFilePath: coxswain-terminal-v2.8.2-x86_64-pc-windows-msvc/coxswain.exe
  PortableCommandAlias: coxswain
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mwo-dk/coxswain/releases/download/v2.8.2/coxswain-terminal-v2.8.2-x86_64-pc-windows-msvc.zip
  InstallerSha256: 6F0999CD9F532A0DFA24C5A6245D4BA8A649F6E0446904C5833B6CF69290CD9D
ManifestType: installer
ManifestVersion: 1.12.0
