# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Termius.Termius
PackageVersion: 10.1.3
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- ssh
- terminus
ProductCode: 4f53adaa-a4b2-50c1-b605-e304e4d14011
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://autoupdate.termius.com/windows/Install%20Termius.exe
  InstallerSha256: CE83D11C2EAC9ECCC84F6D8721DF780D95D8FF0E7E014B62922C31F5F010EA38
- Architecture: x64
  InstallerUrl: https://autoupdate.termius.com/windows/Install%20Termius.exe
  InstallerSha256: CE83D11C2EAC9ECCC84F6D8721DF780D95D8FF0E7E014B62922C31F5F010EA38
ManifestType: installer
ManifestVersion: 1.12.0
