# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Lime.Lime
PackageVersion: 1.152.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- lime
ProductCode: lime
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limecloud/lime/releases/download/v1.152.0/Lime-1.152.0.Setup.exe
  InstallerSha256: BF059ACA558BA7A16AD81F6B9BD16F8B694FB7685B460C59141B9ABDE9EAD80C
ManifestType: installer
ManifestVersion: 1.12.0
