# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: StablyAI.Orca
PackageVersion: 1.4.221
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 2b325ec9-0ed1-575f-ad70-e08307aee879
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/stablyai/orca/releases/download/v1.4.221/orca-windows-setup.exe
  InstallerSha256: D618239BC89429ABB183B2832CC83D371B01E9B3FA296607F0073566D503A181
ManifestType: installer
ManifestVersion: 1.12.0
