# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: CarthageSoftware.Mago
PackageVersion: 1.54.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: mago-1.54.0-x86_64-pc-windows-msvc/mago.exe
  PortableCommandAlias: mago
Commands:
- mago
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/carthage-software/mago/releases/download/1.54.0/mago-1.54.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 643649190F7AEA27997245923EA4E7E2F298AB974BD593FCDCA2C0278273FF6D
ManifestType: installer
ManifestVersion: 1.12.0
