# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FreedomScientific.Fusion.2026
PackageVersion: 2026.2609.11.400
InstallerType: burn
Scope: machine
UpgradeBehavior: install
FileExtensions:
- fsca
- jcf
- mls
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
ReleaseDate: 2026-09-25
AppsAndFeaturesEntries:
- UpgradeCode: '{06446218-C061-4FAE-86AF-75B4902BBCD4}'
Installers:
- Architecture: x64
  InstallerUrl: https://software.vfo.digital/Fusion/2026/2026.2609.11.400/423B9C36-1A0E-4E6B-B8CD-DDAA2D02C5D1/F2026.2609.11.400-Offline-x64.exe
  InstallerSha256: E442DC2657A286B14409E6ECFB767D6FB191360E1597C5750656C52D37755C6A
  ProductCode: '{9DF2CE79-C0DC-42C4-A2E7-1621A4751A44}'
- Architecture: arm64
  InstallerUrl: https://software.vfo.digital/Fusion/2026/2026.2609.11.400/423B9C36-1A0E-4E6B-B8CD-DDAA2D02C5D1/F2026.2609.11.400-Offline-arm64.exe
  InstallerSha256: 6759C1696DA879C5C54A896516F1370855CFDEA19E790A5659666CD5424D99ED
  ProductCode: '{957FF3A4-23D8-482F-B8CB-F4FE722C58C2}'
ManifestType: installer
ManifestVersion: 1.12.0
