# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.WindowsApp
PackageVersion: 2.0.1482.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
Protocols:
- ms-cloudpc
- ms-cp
- ms-remotedesktop
- ms-remotedesktop-launch
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCLibs.Desktop.14
  - PackageIdentifier: Microsoft.WindowsAppRuntime.2
PackageFamilyName: MicrosoftCorporationII.Windows365_8wekyb3d8bbwe
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/477617b7-ba1e-48b9-a2c8-14cd1c2722d5/WindowsApp_x86_Release_2.0.1482.0.msix
  InstallerSha256: 4479B84F6B609810771CE1C57C7F7E466FE0C792E7D20BAFA667D41FACBBBBE0
  SignatureSha256: 847D535EFCF44EBF59BF52909512A5DFDB02547E5941D8CA949C1C1209CF5720
- Architecture: x64
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/390902f9-2a4c-42d4-a574-c56461957534/WindowsApp_x64_Release_2.0.1482.0.msix
  InstallerSha256: 2FEF58ED626C5E611B70B1F0161F2B4F0FB877092F22B102BBDE2F15BE127AF4
  SignatureSha256: 4225809F99A72DB2E5343209BBBF1268FA905A00B962A5A6E495B58D2315B269
- Architecture: arm64
  InstallerUrl: https://res.cdn.office.net/remote-desktop-windows-client/c156d3e8-85f6-4111-bf6a-fc655e745642/WindowsApp_arm64_Release_2.0.1482.0.msix
  InstallerSha256: A51AB3ECA6A0BFA77A4C6D6DA538154BDA0EDBB53A1051BD56940784C521EED5
  SignatureSha256: 6953F513F2DCF6C367779F559D89697C8817CC4C179D1E17C1BCEC49E1A2ACAB
ManifestType: installer
ManifestVersion: 1.12.0
