# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Doist.Todoist
PackageVersion: 9.31.0
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
ExpectedReturnCodes:
- InstallerReturnCode: 2
  ReturnResponse: packageInUse
UpgradeBehavior: install
Protocols:
- todoist
ProductCode: 046cc9a8-e645-5367-8486-409093e0b69a
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://electron-dl.todoist.net/windows/Todoist-win32-9.31.0-x64-latest.exe
  InstallerSha256: 00110EB28296CD86588F11626431792123C07A867FDF11953E8D3C68EEB91E1B
- Architecture: arm64
  InstallerUrl: https://electron-dl.todoist.net/windows/Todoist-win32-9.31.0-arm64-latest.exe
  InstallerSha256: 00877024D9FEBA5A9EC7E734D45B75FB362547F16A6B97F0BFCDCC1BF6CD36D2
ManifestType: installer
ManifestVersion: 1.12.0
