# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Tomclanc.GestureSignV2
PackageVersion: 18.3.3
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
    MinimumVersion: 10.0.0
  - PackageIdentifier: Microsoft.WindowsAppRuntime.2
    MinimumVersion: 2.3.1
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Tomclanc/GestureSignv2/releases/download/v18.3.3/GestureSign-V2-18.3.3-x64.msi
  InstallerSha256: 6449FB0E0906214151BD547A9CE624DE35E4A89F616EC63DE59974F9CBB90ABD
  ProductCode: '{53EBD45F-72F3-4870-AC97-556914768369}'
  AppsAndFeaturesEntries:
  - DisplayName: GestureSign V2
    Publisher: TransposonY / WinUI rebuild
    ProductCode: '{53EBD45F-72F3-4870-AC97-556914768369}'
- Architecture: arm64
  InstallerUrl: https://github.com/Tomclanc/GestureSignv2/releases/download/v18.3.3/GestureSign-V2-18.3.3-arm64.msi
  InstallerSha256: 25CE244491EE54738F143924AE1DF50B1563A2A32536E3511B5C8FB5DA94F951
  ProductCode: '{B4139500-BBD0-4032-AF8D-6675493FB2B9}'
  AppsAndFeaturesEntries:
  - DisplayName: GestureSign V2
    Publisher: TransposonY / WinUI rebuild
    ProductCode: '{B4139500-BBD0-4032-AF8D-6675493FB2B9}'
ManifestType: installer
ManifestVersion: 1.12.0
