# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.RegistryCleaner
PackageVersion: 4.1.0.7
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente Registry Cleaner 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/registrycleanerx86
  InstallerSha256: FC67A39D7182579870C45499E255633EA253C439432FC616CE40E5327A84DEFF
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/registrycleanerx64
  InstallerSha256: E2F1ABD7F7954AF80B4CA59C23172A3265817621679995451D09EE57060E5EAA
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/registrycleanerarm64
  InstallerSha256: DFF39CAA8EFD62B5D83874AEFD41761FB3575A135C27BB99B45B52653EEFB7FB
ManifestType: installer
ManifestVersion: 1.12.0
