# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GitHub.GitHubDesktop
PackageVersion: 3.6.7
UpgradeBehavior: install
Protocols:
- github-windows
- x-github-client
- x-github-desktop-auth
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://desktop.githubusercontent.com/releases/3.6.7-dbc92f97/GitHubDesktopSetup-x64.exe
  InstallerSha256: 2E38DB8D986884474A1E45AFDDF554A7187F42124BD38A3D7EA165BE7F77F90D
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  ProductCode: GitHubDesktop
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://desktop.githubusercontent.com/releases/3.6.7-dbc92f97/GitHubDesktopSetup-x64.msi
  InstallerSha256: E1510C4FA6BC348AADE90CDDA7ED55D8FD1E984AEBF2D66AD290741B92977053
  ProductCode: '{26696D2B-A87F-49FB-BC8C-C55A769CE685}'
  AppsAndFeaturesEntries:
  - DisplayName: GitHub Desktop Deployment Tool
    UpgradeCode: '{00D8E2EE-13EA-5BEB-87F0-70EFC46A7D4A}'
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://desktop.githubusercontent.com/releases/3.6.7-dbc92f97/GitHubDesktopSetup-arm64.exe
  InstallerSha256: 37203F6F453DEAAAFBE0656B0855CB60F19FBE1E5785F638C32D637A5837FA7C
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  ProductCode: GitHubDesktop
- Architecture: arm64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://desktop.githubusercontent.com/releases/3.6.7-dbc92f97/GitHubDesktopSetup-arm64.msi
  InstallerSha256: 076D0044F2A5E6ACD0131578D83336F6B2DA2504A070A7850C58E2B41CC851EA
  ProductCode: '{C93D0E0B-B130-4740-BAC8-4FE9A350FCA8}'
  AppsAndFeaturesEntries:
  - DisplayName: GitHub Desktop Deployment Tool
    UpgradeCode: '{00D8E2EE-13EA-5BEB-87F0-70EFC46A7D4A}'
ManifestType: installer
ManifestVersion: 1.12.0
