# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenCLICollective.codereview-cli
PackageVersion: 0.10.322
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cr.exe
  PortableCommandAlias: cr
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/open-cli-collective/codereview-cli/releases/download/v0.10.322/cr_v0.10.322_windows_amd64.zip
  InstallerSha256: 84FF9F33801D7C5623AB14FFA37B1692638539370C7F05A386B241B6B7A53B1E
- Architecture: arm64
  InstallerUrl: https://github.com/open-cli-collective/codereview-cli/releases/download/v0.10.322/cr_v0.10.322_windows_arm64.zip
  InstallerSha256: E8E61AAC917EE309ACB02EC8661D6B477D112FD87214094CCB4D26B5BBCB6EED
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-02
