# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.Azd
PackageVersion: 1.35.100
InstallerLocale: en-US
InstallerType: wix
InstallerSwitches:
  Custom: INSTALLEDBY="winget"
ProductCode: '{7674FF0A-FD5A-4818-8EA6-5C1B04565D38}'
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/3b75e905-7425-4145-af00-45ce9e143be8/6f786d12-6390-49c4-885b-201bd074242e/azd-windows-amd64.msi
  InstallerSha256: 525FB305A4AFCA96CEF5CE8CA9514A5EED7C61B96197BC2ED9B066F7802A3865
ManifestType: installer
ManifestVersion: 1.12.0
