# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BrowserOS.BrowserClawServer
PackageVersion: 0.0.66
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: resources\bin\browseros-claw-server.exe
Commands:
- browseros-claw-server
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/browseros-ai/BrowserOS/releases/download/claw-server/v0.0.66/browseros-claw-server-rust-resources-windows-x64.zip
  InstallerSha256: 52F5E5C76B0629074BB1CC41DBCD3E6109F2DA66C950095B9271869DB4F63288
ManifestType: installer
ManifestVersion: 1.12.0
