# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: Froststrap.Froststrap
PackageVersion: 2.0.5
PackageLocale: en-US
Publisher: Froststrap
PublisherUrl: https://github.com/Froststrap
PublisherSupportUrl: https://github.com/Froststrap/Froststrap/issues
PackageName: Froststrap
PackageUrl: https://github.com/Froststrap/Froststrap
License: MPL-2.0
LicenseUrl: https://github.com/Froststrap/Froststrap/blob/HEAD/LICENSE
ShortDescription: Froststrap is a fork of Bloxstrap and Fishstrap, focused on performance and customization.
ReleaseNotes: |-
  Froststrap v2.0.5 - What's new?
  More bug fixes... yay!

  Added
  jackshit (or more bugs to fix idk)

  Fix
  - Avalonia new TrayIcon api change which slipped through the cracks
    - this is what broke the tray for activity watcher
    - didnt give any warning about this change so im annoyed this happened

  Codebase
  - Moved from dependabot to Renovate by Mend.io
  - notify now uses the dbus crate
    - 70% compile speed up in debug mode
    - less bloat in the resulting linux binary
    - note: the old crate did implement its own dbus, so now you do need libdbus
ReleaseNotesUrl: https://github.com/Froststrap/Froststrap/releases/tag/v2.0.5
ManifestType: defaultLocale
ManifestVersion: 1.28.0
