# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CrossPlusA.Balabolka
PackageVersion: 2.15.0.921
InstallerType: zip
FileExtensions:
- bxt
- bxz
ReleaseDate: 2026-10-10
Installers:
- Architecture: x86
  NestedInstallerType: exe
  NestedInstallerFiles:
  - RelativeFilePath: setup.exe
  InstallerUrl: https://www.cross-plus-a.com/balabolka.zip
  InstallerSha256: FAF3202AC969996B893B7602EE66352085A3B7F573C7A395004C97A543709477
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  InstallerSwitches:
    Silent: -silent
    SilentWithProgress: -silent
  UpgradeBehavior: install
  ProductCode: Balabolka
- Architecture: x86
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Balabolka\balabolka.exe
  InstallerUrl: https://www.cross-plus-a.com/balabolka_portable.zip
  InstallerSha256: D276730F8861385E6B3E726B9613CE65E85DF9ADD281942B641FD96BBEB8E7A7
  UpgradeBehavior: uninstallPrevious
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
