# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: SteelSeries.GG
PackageVersion: 121.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: SteelSeries GG
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- ProductCode: SteelSeries GG
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\SteelSeries\GG'
Installers:
- Architecture: x64
  InstallerUrl: https://engine.steelseriescdn.com/SteelSeriesGG121.0.0Setup.exe
  InstallerSha256: 2FFFD8FE5A22172F6D8C47BDCD79237C097F0691D6C7DB531FA4D37E2DC21907
ManifestType: installer
ManifestVersion: 1.28.0
