# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: hrzlgnm.zux
PackageVersion: 1.19.3
PackageLocale: en-US
Publisher: hrzlgnm
PublisherUrl: https://github.com/hrzlgnm
PublisherSupportUrl: https://github.com/hrzlgnm/zux/issues
Author: hrzlgnm
PackageName: zux
PackageUrl: https://github.com/hrzlgnm/zux
License: MIT
LicenseUrl: https://github.com/hrzlgnm/zux/blob/HEAD/LICENSE
Copyright: Copyright (c) hrzlgnm
ShortDescription: zux
Description: mDNS-SD visualizer with force-directed graph visualization
Tags:
- mdns-sd
- sveltejs
- tauri-app
- tauri-v2
- vis-network
ReleaseNotes: |-
  1.19.3 (2026-10-03)
  Bug Fixes
  - android: hold targetSdk at 36 to keep local-network access (#453) (2fab699)
  Dependencies
  - update dependency cargo-auditable to v0.7.7 (#450) (e0f864b)
  - update dependency tauri-plugin-android-update-api to ^0.3.0 (#452) (08f7958)
  - update dependency typescript-eslint to v8.71.0 (#448) (86dcbf2)
  - update dtolnay/rust-toolchain digest to 89b1218 (#449) (3a20428)
  - update pnpm to v12.8.0 (#445) (3165844)
  - update pnpm to v12.8.1 (#447) (bd933af)
  - update rust crate tokio to v1.53.2 (#451) (0af10fe)
  - update tauri monorepo (#444) (7c100e5)
ReleaseNotesUrl: https://github.com/hrzlgnm/zux/releases/tag/v1.19.3
ManifestType: defaultLocale
ManifestVersion: 1.12.0
