# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.be
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/be/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: F639FE5D6CB985CC7F3B7E83A01F9F4567590910F8DA326C321676961AB84D0A
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/be/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: D501DBABB4BEF37A5EE02B7F56295FB7D7749DC9418C3BCC52659740B2AB50EC
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/be/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 6C24C71E7777F5D647E36573DC5C21FB18D5A5E48B6FEBA4341CD8656DA8C31F
ManifestType: installer
ManifestVersion: 1.12.0
