# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.pa-IN
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win32/pa-IN/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: 4F00DB8263B2EFB0299E2B0CDE2B33D19E55985A70F29DF415FD150B6886BFDC
  ProductCode: Mozilla Thunderbird 157.0.1 (x86 pa-IN)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win64/pa-IN/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: AAC1136A7209AE7EB93E7796CB573C531F4140A2D2161191FC4E89BDC969D24B
  ProductCode: Mozilla Thunderbird 157.0.1 (x64 pa-IN)
ManifestType: installer
ManifestVersion: 1.12.0
