# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Coder.Coder
PackageVersion: 2.35.9
Commands:
- coder
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: coder.exe
  InstallerUrl: https://github.com/coder/coder/releases/download/v2.35.9/coder_2.35.9_windows_amd64.zip
  InstallerSha256: E04A5DDDD1422ECB2030408E013EBF2201FB3483C187C43088E2C54A32B77627
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/coder/coder/releases/download/v2.35.9/coder_2.35.9_windows_amd64_installer.exe
  InstallerSha256: A01DA1CAE22EBD1E29E8D11FE1DD57060B3E903DC5C65C5672A3ECF347D8CB50
  ProductCode: Coder
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: coder.exe
  InstallerUrl: https://github.com/coder/coder/releases/download/v2.35.9/coder_2.35.9_windows_arm64.zip
  InstallerSha256: 92B6F5A53C33A9EC39152856091FD3BECA52EBB5C874B8F957ED936224979786
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
