# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Opera.OperaGX
PackageVersion: 136.0.6008.111
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /runimmediately
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- opera-gxstable
FileExtensions:
- crx
- gxanimations
- htm
- html
- opdownload
- pdf
- shtml
- xht
- xhtml
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/136.0.6008.111/win/Opera_GX_136.0.6008.111_Setup.exe
  InstallerSha256: CB5FF0272FE2614BECCAA0E126C9DF1866873A8880CCCA8DEBA5A60DD92F67E3
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x86
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/136.0.6008.111/win/Opera_GX_136.0.6008.111_Setup.exe
  InstallerSha256: CB5FF0272FE2614BECCAA0E126C9DF1866873A8880CCCA8DEBA5A60DD92F67E3
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: x64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/136.0.6008.111/win/Opera_GX_136.0.6008.111_Setup_x64.exe
  InstallerSha256: 722B956B765B588CD8F7B5ECE17970E52EB316CE2E9922D0B55D7496A492F52B
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera_gx/136.0.6008.111/win/Opera_GX_136.0.6008.111_Setup_x64.exe
  InstallerSha256: 722B956B765B588CD8F7B5ECE17970E52EB316CE2E9922D0B55D7496A492F52B
  InstallerSwitches:
    Custom: /allusers=1
ManifestType: installer
ManifestVersion: 1.12.0
