# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GregorDadera.AIContextBuilder
PackageVersion: 0.5.500.1
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
ElevationRequirement: elevationRequired
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gregordadera/aicb-roslyn-mcp/releases/download/v0.5.500.1/AIContextBuilder-Setup-0.5.500.1.exe
  InstallerSha256: 9CAAFE369527B8FEFBC77BB4F378A0DA3AAA47B27C7232AC90A0F4144755604C
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ManifestType: installer
ManifestVersion: 1.12.0
