# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sourcegraph.Amp
PackageVersion: 0.0.1791489635-gdf6e24
InstallerType: portable
Commands:
- amp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://static.ampcode.com/cli/0.0.1791489635-gdf6e24/amp-windows-x64-baseline.exe
  InstallerSha256: B7DBE885523B29E4D7E0DAA4AA0D8B71599317F780E7F9E673F399D3649F4CA6
ManifestType: installer
ManifestVersion: 1.12.0
