# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Sogou.SogouInput
PackageVersion: 16.9.0.5523
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- sgreg
FileExtensions:
- scel
- scpf
- ssf
ProductCode: Sogou Input
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://ime.gtimg.com/pc/build/_sogou_pinyin_16.9.0.5523_0.exe
  InstallerSha256: B7CD6BD32A522213C4B58F958F9B6349E9F95923ADA64D7EBC8BA7FB879DDBB3
- Architecture: x64
  InstallerUrl: https://ime.gtimg.com/pc/build/_sogou_pinyin_16.9.0.5523_0.exe
  InstallerSha256: B7CD6BD32A522213C4B58F958F9B6349E9F95923ADA64D7EBC8BA7FB879DDBB3
- Architecture: arm64
  InstallerUrl: https://ime.gtimg.com/pc/build/_sogou_pinyin_16.9.0.5523_0.exe
  InstallerSha256: B7CD6BD32A522213C4B58F958F9B6349E9F95923ADA64D7EBC8BA7FB879DDBB3
ManifestType: installer
ManifestVersion: 1.12.0
