# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.EdgeDriver
PackageVersion: 154.0.4258.62
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: msedgedriver.exe
  PortableCommandAlias: msedgedriver
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://msedgedriver.microsoft.com/154.0.4258.62/edgedriver_win32.zip
  InstallerSha256: C61B9BD9F8112726BCE64A6B721B9B2CCF8B78930E41A5D81EA59E9878757760
- Architecture: x64
  InstallerUrl: https://msedgedriver.microsoft.com/154.0.4258.62/edgedriver_win64.zip
  InstallerSha256: C99F91B608E165831251DBD01245996BCF9FDE3932D56BD39BED297C1407B42E
- Architecture: arm64
  InstallerUrl: https://msedgedriver.microsoft.com/154.0.4258.62/edgedriver_arm64.zip
  InstallerSha256: 24DA562B1C8B3AECB0918B0415341A34D3C5563FD5ED55033657B110F871E866
ManifestType: installer
ManifestVersion: 1.12.0
