# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ShortArrow.gitreant
PackageVersion: 0.2.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: gitreant.exe
  PortableCommandAlias: gitreant
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Git.Git
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ShortArrow/gitreant/releases/download/v0.2.3/gitreant-x86_64-pc-windows-msvc.zip
  InstallerSha256: 6A7251BE95AD72C5B2E10264AA42C757FB8B4C7720D4E8221EB40EF6FD3DC767
- Architecture: arm64
  InstallerUrl: https://github.com/ShortArrow/gitreant/releases/download/v0.2.3/gitreant-aarch64-pc-windows-msvc.zip
  InstallerSha256: 99248880893EA746C72EFDE88321FEEBABF39A9F9CF4D0231009C0D8FC67625B
ManifestType: installer
ManifestVersion: 1.12.0
