# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KDE.Blinken
PackageVersion: 26.11.70
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: Blinken
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://cdn.kde.org/ci-builds/education/blinken/master/windows/blinken-master-865-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: FCDE1995CEE00B54CE5503ECA8E4E24CAAE3FE9E07B0FAFAE42E05895A08DCEF
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://cdn.kde.org/ci-builds/education/blinken/master/windows/blinken-master-865-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: FCDE1995CEE00B54CE5503ECA8E4E24CAAE3FE9E07B0FAFAE42E05895A08DCEF
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.12.0
