# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: AES256Afro.VideoKidnapper
PackageVersion: 1.9.0
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: "{8C8E1A2F-5D4B-4E6A-9F32-7C1A5B2D6E84}_is1"
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- ProductCode: "{8C8E1A2F-5D4B-4E6A-9F32-7C1A5B2D6E84}_is1"
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/AES256Afro/VideoKidnapper/releases/download/v1.9.0/VideoKidnapper-Setup-1.9.0.exe
  InstallerSha256: 412C331997068D5DBEC701DC13B2397BC95B3B82A9554BA496F779EA2BE47F3F
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/AES256Afro/VideoKidnapper/releases/download/v1.9.0/VideoKidnapper-Setup-1.9.0.exe
  InstallerSha256: 412C331997068D5DBEC701DC13B2397BC95B3B82A9554BA496F779EA2BE47F3F
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: "%ProgramFiles%\\VideoKidnapper"
ManifestType: installer
ManifestVersion: 1.12.0
