# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Meta.QuestRemoteDesktop
PackageVersion: 109.0.4.107
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{7F57DCA4-E09E-42E1-BCAA-A71A91DB26DC}'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- UpgradeCode: '{BC5E6690-391D-48C6-9A51-5BD7C3C931C7}'
Installers:
- Architecture: x64
  InstallerUrl: https://securecdn.oculus.com/binaries/download/?id=28435644126062371
  InstallerSha256: 145403F4ED7C5D67E23377AEF7251A7F823CE6258C1013A8CEAFC5A9FA9A64CE
ManifestType: installer
ManifestVersion: 1.12.0
