# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LunarWerxs.SageThumbs2K
PackageVersion: 3.6.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
ProductCode: '{B0A1C2D3-E4F5-4607-8899-AABBCCDDEEFF}_is1'
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- ProductCode: '{B0A1C2D3-E4F5-4607-8899-AABBCCDDEEFF}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\SageThumbs2K'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/LunarWerxs/SageThumbs-2k/releases/download/v3.6.0/SageThumbs2K-Setup-3.6.0.exe
  InstallerSha256: 8F5C49D5D27E970FB23728A97256A59B3A9A9830FB1046B8B56A71DDBB83713B
  UnsupportedOSArchitectures:
  - arm64
- Architecture: arm64
  InstallerUrl: https://github.com/LunarWerxs/SageThumbs-2k/releases/download/v3.6.0/SageThumbs2K-Setup-3.6.0-arm64.exe
  InstallerSha256: D8C21079CEC0DE0FD3343E0D41C07F0B43118172D32171B58CB2AC47DB577780
ManifestType: installer
ManifestVersion: 1.12.0
