# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.be
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0/win32/be/Thunderbird%20Setup%20157.0.exe
  InstallerSha256: A5604050F3E3A076130EDE8EB1C44A80B4A3E173BBCCF5045E5016947801B1E7
  ProductCode: Mozilla Thunderbird 157.0 (x86 be)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0/win64/be/Thunderbird%20Setup%20157.0.exe
  InstallerSha256: 0E275B23D645E431DCA8E602256CE5497A2ABE9DA5AE4BE4A4D7BC4C5C5B0CEC
  ProductCode: Mozilla Thunderbird 157.0 (x64 be)
ManifestType: installer
ManifestVersion: 1.12.0
