# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Corsinvest.cv4pve.cli
PackageVersion: 2.4.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cv4pve-cli.exe
  PortableCommandAlias: cv4pve-cli
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Corsinvest/cv4pve-cli/releases/download/v2.4.0/cv4pve-cli.exe-win-x86.zip
  InstallerSha256: E29D613DF4F7F843B4935C1768F64819356015DC500F7AFCAFF7CD4B174FF3DF
- Architecture: x64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-cli/releases/download/v2.4.0/cv4pve-cli.exe-win-x64.zip
  InstallerSha256: 418663366E88A34BABC54EDBF08C3EE998D38F3E1D033349D8E0A102AC69A857
- Architecture: arm64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-cli/releases/download/v2.4.0/cv4pve-cli.exe-win-arm64.zip
  InstallerSha256: 1E4515A1173B51FE705558F8540C0383BCC06CA50005D1FF67DD4F4C0D39661D
ManifestType: installer
ManifestVersion: 1.12.0
