# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Zeffuro.ZeffBoy
PackageVersion: 0.4.2
InstallerType: inno
Scope: user
UpgradeBehavior: install
InstallationMetadata:
  DefaultInstallLocation: '%LOCALAPPDATA%\Programs\Zeff Boy'
  Files:
  - RelativeFilePath: zeff-boy.exe
    FileType: launch
    DisplayName: Zeff Boy
ProductCode: '{C2417DE7-B9ED-4BE0-AB8B-74873C3B0C49}_is1'
AppsAndFeaturesEntries:
- DisplayName: Zeff Boy
  Publisher: Zeffuro
  ProductCode: '{C2417DE7-B9ED-4BE0-AB8B-74873C3B0C49}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Zeffuro/zeff-boy/releases/download/v0.4.2/zeff-boy-v0.4.2-x86_64-pc-windows-msvc-setup.exe
  InstallerSha256: AEE107DB6B49ABA8C76A65D79C86A1BFBDC0522AEACA3B0A4B5067EED08232E5
ManifestType: installer
ManifestVersion: 1.12.0
