# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anthropic.Claude
PackageVersion: 2.19675.1
Protocols:
- claude
ReleaseDate: 2026-10-05
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.19675.1/Claude-8613680e2e16d90700c039e084a7883f321ed4e3.msix
  InstallerSha256: 07B4935F7A75C5D980B9D63C4D059FDF0AEFE68903FE96E65A5C45CD1A106A93
  SignatureSha256: A57550333FE40532C632D262081ED3AD873DCB8FC0CFBFC70DFE8812D14E0DC3
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.18362.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.19675.1/Claude-8613680e2e16d90700c039e084a7883f321ed4e3.msix
  InstallerSha256: 9556E8566307A1EB9434B8E23CD4BC34B339B61D3F79D303ABF843AF5D4748E0
  SignatureSha256: 95EC95B58BE07A3277459B18CE8F159204157AB65A6561C39FD67ED2F6C0C48E
  PackageFamilyName: Claude_pzs8sxrjxfjjc
  Capabilities:
  - internetClient
  RestrictedCapabilities:
  - localSystemServices
  - packagedServices
  - runFullTrust
  - unvirtualizedResources
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/x64/2.19675.1/Claude-8613680e2e16d90700c039e084a7883f321ed4e3.exe
  InstallerSha256: 692DE1F6B82850FB92A5ECA4F7A64A8C41FA6BD8CF5D97F5105D0E68C0F28980
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.claude.ai/releases/win32/arm64/2.19675.1/Claude-8613680e2e16d90700c039e084a7883f321ed4e3.exe
  InstallerSha256: 04CFFA31263D948819581898AE7275296F982B4251DCBECEAD34E7875DA539CD
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  UpgradeBehavior: install
  ProductCode: AnthropicClaude
ManifestType: installer
ManifestVersion: 1.12.0
