# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Kraken.KrakenDesktop
PackageVersion: 1.32.0
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: APPLICATIONFOLDER="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{AB930DA7-43AF-4198-9EDF-6C203B3F3811}'
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- ProductCode: '{AB930DA7-43AF-4198-9EDF-6C203B3F3811}'
  UpgradeCode: '{239520EB-CBE7-4EF6-BC20-ABE5F0FE7F76}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Kraken Desktop'
Installers:
- Architecture: x64
  InstallerUrl: https://desktop-downloads.kraken.com/ebeca4bc7490b75e0cbb492bb785e3c9b63ec2b2/KrakenDesktopInstaller.msi
  InstallerSha256: 3F647EBABF575F76E23BD4423F1A22D296AC6764A9CE0AD67CA82793ED1C3B33
ManifestType: installer
ManifestVersion: 1.28.0
