# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SQLBI.Whiteboard
PackageVersion: 1.7.5
MinimumOSVersion: 10.0.19041.0
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/sql-bi/SQLBI-Whiteboard/releases/download/v1.7.5/SQLBI.Whiteboard.1.7.5.x64.msi
  InstallerSha256: 331DB7BC6F7F9F52F27558568437AE3896CC8F5F02B196203AAACCD104F1BFDE
  ProductCode: '{440997B4-5528-4326-BF1C-D0AFDC160B30}'
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/sql-bi/SQLBI-Whiteboard/releases/download/v1.7.5/SQLBI.Whiteboard.1.7.5.x64-userinstaller.msi
  InstallerSha256: 99E9007F4616CA9C0A87F9021D52DE13CABFE4CF532A561318213CA03DAD9BDA
  ProductCode: '{7338BDD7-5143-4327-B0ED-9A768B9468D7}'
ManifestType: installer
ManifestVersion: 1.12.0
