# Automatically updated by the winget bot at 2026/Oct/05
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: CatConnect.SotaConnect
PackageVersion: 1.8.8+1690
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://storage.sota.ac/api/v1/public/storage/sotaconnect_setup.exe
  InstallerSha256: 9146340557F5F130793613FD9F58D919A2B294B8C027FAE1981D1B9E6900A38D
ManifestType: installer
ManifestVersion: 1.28.0
