# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ToDesktop.ToDesktop
PackageVersion: 0.38.3
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
FileExtensions:
- todesktop
ProductCode: ecb05659-2faa-5c23-bdf5-d11c4e79b6f7
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://download.todesktop.com/2108257l5oobyoe/ToDesktop%20Builder%20Setup%200.38.3%20-%20Build%20261004ea81cac27-x64.exe
  InstallerSha256: 8B87B61D5B0F0C36F5CDF8D2B769CFD41682E6860DBBF60BE92A6933951154BD
ManifestType: installer
ManifestVersion: 1.12.0
