# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lanxiuyun.Catrace
PackageVersion: 26.10.10
InstallerType: nullsoft
Scope: user
ProductCode: Catrace
ReleaseDate: 2026-10-10
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Catrace'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lanxiuyun/Catrace/releases/download/v26.10.10/Catrace_26.10.10_x64-setup.exe
  InstallerSha256: 4B6F1626BE7947D8F46BACF0532DD83BA369A61D0083E24157DA58D31BC19A48
ManifestType: installer
ManifestVersion: 1.12.0
