# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Vita3K.Vita3K
PackageVersion: 0.2.1.4103
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: Vita3K.exe
  PortableCommandAlias: vita3k
FileExtensions:
- bin
- pkg
- pup
- rif
- vpk
- zip
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-09-30
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Vita3K/Vita3K/releases/download/continuous/windows-latest.zip
  InstallerSha256: B2DD56E5D180B4C9F9D1B3492ED3F4FD9A0A26554955AF7E2F7F6352841BD947
ManifestType: installer
ManifestVersion: 1.12.0
