# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: can1357.oh-my-pi
PackageVersion: 18.8.6
InstallerType: portable
Commands:
- omp
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/can1357/oh-my-pi/releases/download/v18.8.6/omp-windows-x64.exe
  InstallerSha256: C139A5C4653EC475F63AC9076DCB1B1DA150432A3B4F6C832131CEAF70AC8A86
ManifestType: installer
ManifestVersion: 1.12.0
