# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Buildkite.Agent
PackageVersion: 4.2.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: buildkite-agent.exe
  PortableCommandAlias: buildkite-agent
Commands:
- buildkite-agent
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/buildkite/agent/releases/download/v4.2.1/buildkite-agent-windows-386-4.2.1.zip
  InstallerSha256: 82AEC9D0847B3B793644AF761B314FC3595AE608241DF8F6B2F7E9E02918511A
- Architecture: x64
  InstallerUrl: https://github.com/buildkite/agent/releases/download/v4.2.1/buildkite-agent-windows-amd64-4.2.1.zip
  InstallerSha256: FBEF5FCDE256BBE7AB4C0A02C075D450168D4EAB111DAB3C5398AA811DB23378
- Architecture: arm64
  InstallerUrl: https://github.com/buildkite/agent/releases/download/v4.2.1/buildkite-agent-windows-arm64-4.2.1.zip
  InstallerSha256: 74A6483AB48593D10EAD56A6C6D49776ED75B36D405D988A6ADD94338B90FD48
ManifestType: installer
ManifestVersion: 1.28.0
