# Automatically updated by the winget bot at 2026/Oct/01
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: NAVER.Whale
PackageVersion: 5.39.412.57
InstallerType: exe
InstallerSwitches:
  Silent: /silent
AppsAndFeaturesEntries:
- Publisher: NAVER Corp
  ProductCode: Naver Whale
Installers:
- Architecture: x86
  InstallerUrl: https://installer-whale.pstatic.net/downloads/sa_installers/WhaleSetupX86.exe
  InstallerSha256: 5884938AE73EF7B6655D99C2F0EC2292C980CE975BE9DA49DD5685BAC17525A6
- Architecture: x64
  InstallerUrl: https://installer-whale.pstatic.net/downloads/sa_installers/WhaleSetupX64.exe
  InstallerSha256: E206D97D863393A5CCD21A871C01F1BDC782FDE5B356A379CC2E5B17C1768610
- Architecture: arm64
  InstallerUrl: https://installer-whale.pstatic.net/downloads/sa_installers/WhaleSetupARM64.exe
  InstallerSha256: 650BDA30083C3C07932E3499B51FA73762B5FF0A0B84FCE2E757B79390760E14
ManifestType: installer
ManifestVersion: 1.28.0
