# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Rustlang.Rust.GNU.LLVM
PackageVersion: 1.99.0
InstallerType: wix
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://static.rust-lang.org/dist/rust-1.99.0-x86_64-pc-windows-gnullvm.msi
  InstallerSha256: 9FE13F586254A4FA41AFE8553DF0097349D952AC1F1583BAA398330315706AE0
  ProductCode: '{AAF6A960-7886-4BE5-A531-5F6C24FD6C91}'
  AppsAndFeaturesEntries:
  - ProductCode: '{AAF6A960-7886-4BE5-A531-5F6C24FD6C91}'
    UpgradeCode: '{BA2B2E96-F3E2-4DE9-8809-38C31382CC96}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Rust'
- Architecture: arm64
  InstallerUrl: https://static.rust-lang.org/dist/rust-1.99.0-aarch64-pc-windows-gnullvm.msi
  InstallerSha256: DD52CD90DC2020BB80F98C111F73A1C0F6322D7D0C792CAA3F11AAC3D5C3D520
  ProductCode: '{7C9DC99D-7D71-457A-B86A-3E9F719025F5}'
  AppsAndFeaturesEntries:
  - ProductCode: '{7C9DC99D-7D71-457A-B86A-3E9F719025F5}'
    UpgradeCode: '{DB29CBDE-CDDF-4EC9-9C68-B6F00038EEDD}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/Rust'
ManifestType: installer
ManifestVersion: 1.28.0
