# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Corsinvest.cv4pve.report
PackageVersion: 2.8.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cv4pve-report.exe
  PortableCommandAlias: cv4pve-report
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Corsinvest/cv4pve-report/releases/download/v2.8.1/cv4pve-report.exe-win-x86.zip
  InstallerSha256: 77AD94FB07E514C97FBC4FB172CD096DE678E07B583C1B1BE656C11DB2BE7C02
- Architecture: x64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-report/releases/download/v2.8.1/cv4pve-report.exe-win-x64.zip
  InstallerSha256: 115301102EE41235E88BD1739050EF58C301EB5F9165E328DC4E004FC3CC0CF4
- Architecture: arm64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-report/releases/download/v2.8.1/cv4pve-report.exe-win-arm64.zip
  InstallerSha256: B7CA12E190FB3D66A3BCF45B5B355F0A5B625515B076006223F4264074E3D45F
ManifestType: installer
ManifestVersion: 1.12.0
