# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Wargaming.GameCenter
PackageVersion: 26.05.00.3403
PackageLocale: en-GB
PackageName: Wargaming.net Game Centre
Description: |-
  Wargaming.net Game Centre is the official game launcher for all Wargaming titles.
  It provides a unified platform to download, install, update, and manage games like World of Tanks, World of Warships, and World of Warplanes.
  The launcher features automatic game updates, news feeds, and easy access to your Wargaming account.
Tags:
- wargaming-came-centre
- wargaminggamecentre
- game-launcher
- games-launcher
- gamelauncher
- gaming
- military-games
- worldoftanks
- worldofwarplanes
- worldofwarships
- world-of-tanks
- world-of-warplanes
- world-of-warships
- wot
- wows
ManifestType: locale
ManifestVersion: 1.12.0
