# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.oc
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/oc/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 9CC428343DE745874E74314591B927E355A19A7A610CFB0604ED1AEDD9A75A74
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/oc/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: E5E7D18953922E90D9AA0384E38119E2088F28B40A593C3AD6DF9CE268263366
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/oc/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 6F753B3D927B69DFEEB4B728F929D17A372FB7BFFC785A29158B2BFDD12A221F
ManifestType: installer
ManifestVersion: 1.12.0
