# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Elastic.Winlogbeat
PackageVersion: 9.5.5
Commands:
- winlogbeat
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-9.5.5-windows-x86_64.msi
  InstallerSha256: 8ED967F1CCC821AA4840C287B7A7FD29E7CF80EB481B7C894E9F6CC3069B38A3
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  UpgradeBehavior: install
  ProductCode: '{2DE7C165-4793-5EE1-9DF0-372082858E2B}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{2DE7C165-4793-5EE1-9DF0-3720F2352E2B}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Elastic\Beats\9.1.2\winlogbeat'
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: winlogbeat-9.5.5-windows-x86_64\winlogbeat.exe
    PortableCommandAlias: winlogbeat
  InstallerUrl: https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-9.5.5-windows-x86_64.zip
  InstallerSha256: 788D004E1BD0C6F8ACAB7B5A4520C636DA960FFAE3686D0C218988210DF5EB2D
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
