# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: jerrywu001.cc-sessions-viewer
PackageVersion: 0.5.3
UpgradeBehavior: install
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/jerrywu001/cc-sessions-viewer/releases/download/v0.5.3/Sessions.Viewer_0.5.3_x64-setup.exe
  InstallerSha256: 0CC25DEFD82EDDF7D93538A5BB161669D88AFB0FFB4E948D6501A96F0471C66E
  ProductCode: Sessions Viewer
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/jerrywu001/cc-sessions-viewer/releases/download/v0.5.3/Sessions.Viewer_0.5.3_x64_en-US.msi
  InstallerSha256: 67FED3021DC0AC3FD68C362BCDC462298F68555420F61B44F6C991EE5D74479F
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{77203F54-C7F3-4A45-AEC5-2D5F5FF58279}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{8E2574C0-969D-515B-A3BA-FA3339E97BD2}'
ManifestType: installer
ManifestVersion: 1.12.0
