# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: squidowl.halloy
PackageVersion: 2026.9.0
InstallerType: inno
Scope: user
ReleaseDate: 2026-10-01
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/squidowl/halloy/releases/download/2026.9/halloy-installer.exe
    InstallerSha256: 06fc514de697a378e9a3e8a8280b5f76045ae1ddd0f8e83d4cc4771c08501b1a
InstallerLocale: en-US
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Halloy'
ProductCode: '{3ED18662-FB43-4803-A4F9-89BBBC0B6D01}_is1'
AppsAndFeaturesEntries:
  - DisplayName: Halloy 2026.9.0
    ProductCode: '{3ED18662-FB43-4803-A4F9-89BBBC0B6D01}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
