# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: hrzlgnm.mdns-browser
PackageVersion: 2.5.6
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: mdns-browser
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- Publisher: github
  ProductCode: mdns-browser
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\mdns-browser'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hrzlgnm/mdns-browser/releases/download/v2.5.6/mdns-browser_2.5.6_x64-setup.exe
  InstallerSha256: EE7CA9308BDE57571C6215A50A96061F089787918F2EE19DF4AFA4F1B8B74D65
ManifestType: installer
ManifestVersion: 1.12.0
