# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: EarendilWorks.pi
PackageVersion: 1.0.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pi.exe
Commands:
- pi
ReleaseDate: 2026-10-05
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/earendil-works/pi/releases/download/v1.0.4/pi-windows-x64.zip
  InstallerSha256: 6BDBFB7BAC252EEA36A0095E4B741C9D5784D5BA99146E2D76E9246DEE409B58
- Architecture: arm64
  InstallerUrl: https://github.com/earendil-works/pi/releases/download/v1.0.4/pi-windows-arm64.zip
  InstallerSha256: CA8A2F2687D2097D3F93EAD151E943315A262CF499ABE6635C09E293CCED164D
ManifestType: installer
ManifestVersion: 1.12.0
