# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Docker.DockerCompose
PackageVersion: 5.6.0
InstallerType: portable
Commands:
- docker-compose
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/docker/compose/releases/download/v5.6.0/docker-compose-windows-x86_64.exe
  InstallerSha256: 8AEAA0055E660E12CF07CD70680DC8333957FE6718528B91EC3DA084EAB62483
- Architecture: arm64
  InstallerUrl: https://github.com/docker/compose/releases/download/v5.6.0/docker-compose-windows-aarch64.exe
  InstallerSha256: 73CDC73A03443CBA37C7AE91AEC12C7B86C0EB75A8F40F296AAA5159E66B29BC
ManifestType: installer
ManifestVersion: 1.12.0
