# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: UpNote.UpNote
PackageVersion: 9.22.6
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
Protocols:
- upnote
ProductCode: 25d6aa7b-585b-5b4c-8403-aece86b972ea
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.getupnote.com/app/UpNote%20Setup.exe
  InstallerSha256: 96E5385F357233387C8977A6FD02E6C2E6BA9CCBB4997B2F7053F3CE061A9997
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.getupnote.com/app/UpNote%20Setup.exe
  InstallerSha256: 96E5385F357233387C8977A6FD02E6C2E6BA9CCBB4997B2F7053F3CE061A9997
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
