# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: bullpae.keymander
PackageVersion: 0.16.9
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: keymander/kmd-daemon.exe
  PortableCommandAlias: kmd-daemon
- RelativeFilePath: keymander/kmd-desktop.exe
  PortableCommandAlias: kmd-desktop
- RelativeFilePath: keymander/kmd.exe
  PortableCommandAlias: kmd
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bullpae/keymander/releases/download/v0.16.9/keymander-portable-x86_64-pc-windows-msvc.zip
  InstallerSha256: 2FA8C20FC6F59C8F878B91466D289AD0728D837696E34208E260541834DF08B8
- Architecture: arm64
  InstallerUrl: https://github.com/bullpae/keymander/releases/download/v0.16.9/keymander-portable-aarch64-pc-windows-msvc.zip
  InstallerSha256: 075C67B091942C549000AE8285D9A215A15E4231A068B4E542CAC2F8811E41D1
ManifestType: installer
ManifestVersion: 1.12.0
