# Automatically updated by the winget bot at 2026/Oct/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: AISwitcher.AISwitcher
PackageVersion: 0.6.6
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/AariyJP/ai-switcher/releases/latest/download/AI.Switcher_x64-setup.exe
  InstallerSha256: F622152107603DE2987B8EC0EF5940F1C2B0A17A586563B926BCFCCC4FDA1064
ManifestType: installer
ManifestVersion: 1.28.0
