# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NodirTemirkhodjaev.FortFirewall
PackageVersion: 3.20.3
InstallerType: inno
Scope: machine
ProductCode: Fort Firewall_is1
ReleaseDate: 2026-10-09
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/tnodir/fort/releases/download/v3.20.3/FortFirewall-3.20.3-windows-x86.exe
  InstallerSha256: 024428B3FE05E54070BDA5203901BC15ED4A0ABC7A96B35EBE6C74A79B6B06FD
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://github.com/tnodir/fort/releases/download/v3.20.3/FortFirewall-3.20.3-windows10-x86_64.exe
  InstallerSha256: 9B48FE13B928920E2A1E8A0A5F5731C09B2182E15BBA4B2651BED3124B8EE906
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/tnodir/fort/releases/download/v3.20.3/FortFirewall-3.20.3-windows10-arm64.exe
  InstallerSha256: B36F745A812032F3F6B4A42C9A663FED1D30C8ECDA7E4E53F0E97AAF73AE9925
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
