# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CoralCreek.SQLiteExpert.Personal
PackageVersion: 6.2.5.739
InstallerType: inno
Scope: machine
ReleaseDate: 2026-10-03
Installers:
- Architecture: x86
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertPersSetup32.exe
  InstallerSha256: 027366F84275A3E2A95E2D323FB56FA799B82C4318CBCEE9D8DFA508B85F6FFA
  ProductCode: SQLite Expert Personal 6 - 32bit_is1
- Architecture: x64
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertPersSetup64.exe
  InstallerSha256: 863C5D578F48343C3A4551660F81E660287D532B150EFAE679813BCE4DE02DE6
  ProductCode: SQLite Expert Personal 6 - 64bit_is1
ManifestType: installer
ManifestVersion: 1.12.0
