# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.EdgeWebView2Runtime
PackageVersion: 154.0.4258.62
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /silent /install
  SilentWithProgress: /silent /install
InstallerSuccessCodes:
- -2147219416
- -2147219187
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
ProductCode: Microsoft EdgeWebView
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/72a30254-c583-4d82-9d8d-80022f4ccb01/MicrosoftEdgeWebView2RuntimeInstallerX86.exe
  InstallerSha256: 1F02CCFFEE6708621DFF4BFF363D4491A87B4286634FFB4DACA5D7BFD1E76A77
- Architecture: x86
  Scope: machine
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/72a30254-c583-4d82-9d8d-80022f4ccb01/MicrosoftEdgeWebView2RuntimeInstallerX86.exe
  InstallerSha256: 1F02CCFFEE6708621DFF4BFF363D4491A87B4286634FFB4DACA5D7BFD1E76A77
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/18c66e75-0385-4019-be3f-3f4a2bb867d5/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  InstallerSha256: AC22ECDC19C5B88B87F3FA752C00DA9541653A8F5C0C5FC4A3B2B6EBE6591F69
- Architecture: x64
  Scope: machine
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/18c66e75-0385-4019-be3f-3f4a2bb867d5/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  InstallerSha256: AC22ECDC19C5B88B87F3FA752C00DA9541653A8F5C0C5FC4A3B2B6EBE6591F69
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/2b6d458d-70d9-4399-92c3-1bfbd1ec1591/MicrosoftEdgeWebView2RuntimeInstallerARM64.exe
  InstallerSha256: AC62B0296E1A57B04B05F0BF2174E67ACD672FE381581AB967E4EE51A6DA3447
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/2b6d458d-70d9-4399-92c3-1bfbd1ec1591/MicrosoftEdgeWebView2RuntimeInstallerARM64.exe
  InstallerSha256: AC62B0296E1A57B04B05F0BF2174E67ACD672FE381581AB967E4EE51A6DA3447
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
