# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SaaSGroup.Tower
PackageVersion: 14.1.586
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://www.git-tower.com/apps/tower3-win/586-6dd78fd9/Tower-14.1.586.exe
  InstallerSha256: 5CED09E9CE3EBD5698F2E8C207E490A3E72C1DA87EEE7CB503752B8285BF1D75
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  ProductCode: Tower
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://www.git-tower.com/apps/tower3-win/586-6dd78fd9/Tower-14.1.586.msi
  InstallerSha256: 8B68CD58B05629ABAAF14432A2D665033E19F86F9B5D8C9D77823A0171612B84
  InstallerSwitches:
    InstallLocation: APPLICATIONROOTDIRECTORY="<INSTALLPATH>"
  ProductCode: MSI:Tower
  AppsAndFeaturesEntries:
  - InstallerType: exe
ManifestType: installer
ManifestVersion: 1.12.0
