# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.244
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.244/anchors_0.1.244_windows_amd64.zip
  InstallerSha256: 7ED59EAE62881F0C129CCDE2F7D6A3029C9E721B08168C07DB1AA74EF84AACA8
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.244/anchors_0.1.244_windows_arm64.zip
  InstallerSha256: F1C9D23A9984A7B736A75583FA161DE863196EB2B9705460E5809742D2592856
ManifestType: installer
ManifestVersion: 1.12.0
