# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Namespace.nsc
PackageVersion: 0.0.587
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: bazel-credential-nsc.exe
- RelativeFilePath: docker-credential-nsc.exe
- RelativeFilePath: nsc.exe
Commands:
- nsc
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://get.namespace.so/packages/nsc/v0.0.587/nsc_0.0.587_windows_amd64.zip
  InstallerSha256: 41BA7E3D49FF281DE85474D6D309ADE24BA14A3C36A4480706E02199A2B391B9
- Architecture: arm64
  InstallerUrl: https://get.namespace.so/packages/nsc/v0.0.587/nsc_0.0.587_windows_arm64.zip
  InstallerSha256: E89059E3173B6C1C108A9F9828F3CBBBA4AF9537D6108C9F378E81F368C7691E
ManifestType: installer
ManifestVersion: 1.28.0
