# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Elastic.Filebeat
PackageVersion: 9.5.5
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Commands:
- filebeat
ProductCode: '{84CD8645-4DB1-5D89-81E3-071FF2DC5EAE}'
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- UpgradeCode: '{84CD8645-4DB1-5D89-81E3-071F628CFEAE}'
Installers:
- Architecture: x64
  InstallerUrl: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-9.5.5-windows-x86_64.msi
  InstallerSha256: BF3DC69E18A28B6C1932B7BF91C9909751E1EC02B84A3F76C25D7E0034C52990
ManifestType: installer
ManifestVersion: 1.12.0
