# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: TomasBruckner.dbc
PackageVersion: 0.38.1
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: dbc
  Publisher: Tomáš Bruckner
  ProductCode: dbc
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tomasbruckner/dbc/releases/download/v0.38.1/dbc-win-Setup.exe
  InstallerSha256: 11260C53B9D726A991A6AF22AFCE263223E2266C8546B744BC08AC440E557110
ReleaseDate: 2026-10-02
ManifestType: installer
ManifestVersion: 1.12.0
