# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Oracle.OCI-CLI
PackageVersion: 3.94.2
InstallerType: msi
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- oci
ProductCode: '{69BC146E-B8E7-4770-B48B-0911BE022CA1}'
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- DisplayName: oci-cli
  ProductCode: '{69BC146E-B8E7-4770-B48B-0911BE022CA1}'
  UpgradeCode: '{48B079F4-B598-438D-A62A-8A233A3F8901}'
InstallationMetadata:
  DefaultInstallLocation: Lib
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/oracle/oci-cli/releases/download/v3.94.2/oci-cli-3.94.2-Windows-Server-Installer.msi
  InstallerSha256: 5E2A3978AE9E1706EF4F65BF6037919BC9AF37533D1D4996B14D88323F509EF8
ManifestType: installer
ManifestVersion: 1.28.0
