# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Anthropic.Ant
PackageVersion: 1.39.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ant.exe
Commands:
- ant
ReleaseDate: 2026-10-07
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/anthropics/anthropic-cli/releases/download/v1.39.0/ant_1.39.0_windows_386.zip
  InstallerSha256: BE2C92BC85556746A3CA0FF92D3AE013BD196EC88758A83127D5DD4E6D912B9E
- Architecture: x64
  InstallerUrl: https://github.com/anthropics/anthropic-cli/releases/download/v1.39.0/ant_1.39.0_windows_amd64.zip
  InstallerSha256: 4995E9101E583355D99211F99237975995F37B1C49C56ECA9A42973B8767AD98
- Architecture: arm64
  InstallerUrl: https://github.com/anthropics/anthropic-cli/releases/download/v1.39.0/ant_1.39.0_windows_arm64.zip
  InstallerSha256: 474EE0653417FB27C4155916121CD908D23726927BC777F5E7CD29D37C8A98E6
ManifestType: installer
ManifestVersion: 1.12.0
