# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.498.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.498.0&arch=x86
  InstallerSha256: D2133F64983F7876E492631FA839FFD7BABAF2A2EE468896A824BBE18D25D49A
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.498.0&arch=amd64
  InstallerSha256: D47FB82FF7A42B6B81994C41BEB9F7D39E55359688D081A939D6AC3C3321C95E
ManifestType: installer
ManifestVersion: 1.28.0
