# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.SystemManager
PackageVersion: 1.0.5.2
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente System Manager 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerx86
  InstallerSha256: 3D1B5B18C7993344BA763ED1F93A7FE135C69D5061A60F6D0AEFE3F480A590AB
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerx64
  InstallerSha256: C36C052AF4D3597BF496077AF815A8530D60554B892B123195DE8D6A911378FA
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerarm64
  InstallerSha256: B0B2FE785A5F59091A9BD39125EBB196F01209B22B111C20ED2D45E6D2EF9406
ManifestType: installer
ManifestVersion: 1.12.0
