# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: qingchencloud.ClawPanel
PackageVersion: 0.21.9
UpgradeBehavior: install
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/qingchencloud/clawpanel/releases/download/v0.21.9/ClawPanel_0.21.9_x64-setup-full.exe
  InstallerSha256: 1F498B5114B734973E0D62D14DE2FF1C47E918F6CFEBD4DF0B2C00014A131890
  ProductCode: ClawPanel
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/qingchencloud/clawpanel/releases/download/v0.21.9/ClawPanel_0.21.9_x64-full_en-US.msi
  InstallerSha256: 6E9604AB8B763CE0DFC9854C35F255DABDB1601048B6C595C740E1B9F57AC2E4
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{8BA473B2-3649-4806-BC41-96F20797C925}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{AA908EA1-FFA0-5A0E-B2C5-14A7B8C64033}'
ManifestType: installer
ManifestVersion: 1.12.0
