# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PowerUserZ.OpenTokenUsage
PackageVersion: 0.7.3
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Custom: AUTOLAUNCHAPP=True
UpgradeBehavior: install
ProductCode: '{77AB5E0C-1F2A-403B-8FC5-9ACB7BD97F29}'
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- Publisher: sunstory
  ProductCode: '{77AB5E0C-1F2A-403B-8FC5-9ACB7BD97F29}'
  UpgradeCode: '{28D7E68F-C9A6-5E8E-A566-097F6F3B8A75}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/OpenTokenUsage'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PowerUserZ/OpenTokenUsage/releases/download/v0.7.3/OpenTokenUsage_0.7.3_x64_en-US.msi
  InstallerSha256: B1D559040D7DB244EB542540AF26A5E0967FD227F5981C0B61154EB06A2A025A
ManifestType: installer
ManifestVersion: 1.12.0
