# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nabukodonozor.NabuSQL
PackageVersion: 1.0.110
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://nabusql.nabu.work/releases/NabuSQL_1.0.110_x64-setup.exe
  InstallerSha256: 928223E04F3D8223014D525DD07B4D6680D4BB63AC98B783002E4835A36708B3
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-02
