# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NotedeckDev.NoteDeck
PackageVersion: 1.75.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
ProductCode: NoteDeck
ReleaseDate: 2026-09-30
AppsAndFeaturesEntries:
- Publisher: notedeck
  ProductCode: NoteDeck
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\NoteDeck'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/notedeck-dev/notedeck/releases/download/v1.75.1/NoteDeck-1.75.1-windows-x64-setup.exe
  InstallerSha256: 8AEE052574321D9954EEFA7B3CA508ACECB6344C5628FC6D1633A2028084F512
ManifestType: installer
ManifestVersion: 1.12.0
