# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SlackTechnologies.Slack
PackageVersion: 4.52.178
UpgradeBehavior: install
Protocols:
- slack
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://downloads.slack-edge.com/desktop-releases/windows/x64/4.52.178/SlackSetup.exe
  InstallerSha256: EDEC34A6CD42A33DA7556BAC0CEB4046AE9E37AC0B1A4AE83A1B321C381EE062
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  ProductCode: slack
  RequireExplicitUpgrade: true
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.17763.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://downloads.slack-edge.com/desktop-releases/windows/x64/4.52.178/Slack.msix
  InstallerSha256: FA6D100271873E5163C8464C4AD122504E03A7AE2C4BED5D67289630DDC1AB69
  SignatureSha256: ECEAA2478114356BF0AEE56A74E98B9AF8254320F2F5A6C28DE1ED585D7A86C2
  PackageFamilyName: com.tinyspeck.slackdesktop_8yrtsj140pw4g
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.17763.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://downloads.slack-edge.com/desktop-releases/windows/arm64/4.52.178/Slack.msix
  InstallerSha256: 6C764AA2816A1917D1F9AFF9FF7868775D51C06378B0331A78389206091F8372
  SignatureSha256: 545EA6535D9410EDC75D8ACB71B482A7E2E7478550DBD8797C2209B1C49D5232
  PackageFamilyName: com.tinyspeck.slackdesktop_8yrtsj140pw4g
ManifestType: installer
ManifestVersion: 1.12.0
