# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: FreedomTerminal.Koegaki
PackageVersion: 1.10.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ProductCode: Koegaki
ReleaseDate: 2026-10-08
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Koegaki'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/vishutdhar/koegaki-releases/releases/download/v1.10.0/Koegaki-1.10.0-setup.exe
    InstallerSha256: 2E544FFED6B19C87BE0D4ED2B5C343FFA41E44B064C93DB76D5429B2BA684B1A
ManifestType: installer
ManifestVersion: 1.12.0
