# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: CircleCI.CLI
PackageVersion: 1.2.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: circleci.exe
  PortableCommandAlias: circleci
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.2.0/circleci-cli_1.2.0_windows_amd64.zip
  InstallerSha256: 609C35E9F342BE1E680F95ACA3454ABC8F0A2E6AD695361CE77FC24694CDEBA7
- Architecture: arm64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.2.0/circleci-cli_1.2.0_windows_arm64.zip
  InstallerSha256: F7A44D472B284C6ECF639A5FCE6FCB72EE45F88902CF9A0C703C47F3E19128A7
ManifestType: installer
ManifestVersion: 1.28.0
