# Automatically updated by the winget bot at 2026/Oct/02
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: ComfortSoftwareGroup.ComfortOSK
PackageVersion: 10.0.1.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{6EB17721-6249-417B-99B9-DAF3FD532955}_is1'
ReleaseDate: 2022-05-17
AppsAndFeaturesEntries:
- ProductCode: '{6EB17721-6249-417B-99B9-DAF3FD532955}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\ComfortKeyboard'
Installers:
- Architecture: x86
  InstallerUrl: https://www.comfortsoftware.com/download/ComfortOSKSetup.exe
  InstallerSha256: DF129AFE668C6EE4253EED1D4B5C7FA3BBDC5FEFA847D3AA3B8ACFE45503BFAF
ManifestType: installer
ManifestVersion: 1.28.0
