# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: zig.zig
PackageVersion: 0.17.0
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: zig-x86-windows-0.17.0/zig.exe
  InstallerUrl: https://ziglang.org/download/0.17.0/zig-x86-windows-0.17.0.zip
  InstallerSha256: C7B83507549C7BCD42CD58C4910B47037F4150ED7778E11B3684F130620969D1
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: zig-x86_64-windows-0.17.0/zig.exe
  InstallerUrl: https://ziglang.org/download/0.17.0/zig-x86_64-windows-0.17.0.zip
  InstallerSha256: B5663F69581DCF391293FBF16C06CB80D81D806545CE618B4D0BAB7F0EB8C428
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: zig-aarch64-windows-0.17.0/zig.exe
  InstallerUrl: https://ziglang.org/download/0.17.0/zig-aarch64-windows-0.17.0.zip
  InstallerSha256: 0A59D91FA1CB40CF068E9B0954434CE973500C7A2EA749F1E01AF62CDAB52D26
ManifestType: installer
ManifestVersion: 1.28.0
