PackageIdentifier: Sparcle.BoltEnterprise
PackageVersion: 0.1.168
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    Scope: user
    InstallerUrl: https://github.com/SparcleHQ/sparcle.app/releases/download/v0.1.168/Bolt-Enterprise-0.1.168-x86_64-pc-windows-msvc.exe
    InstallerSha256: 57FFDE3085453E7757A86E4526D1D00AF5638501C438FE60CE2A4DFE6DCBBC33
    AppsAndFeaturesEntries:
      - DisplayName: Bolt
        ProductCode: Bolt
ManifestType: installer
ManifestVersion: 1.6.0
