# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Innovaphone.myApps
PackageVersion: 16.1.1009
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\innovaphone\myApps'
Installers:
- Architecture: x86
  InstallerUrl: https://store.innovaphone.com/release/1700300/innovaphone-appstore?filename=1611009myappswindowsmyAppsSetup32.msi&nameout=myAppsSetup32.msi&update=true
  InstallerSha256: FD6C38D5C1E6394C16EFD513233E2A28EA39224C3E910054D21E958F4937433B
  ProductCode: '{AFF4AD43-A706-4820-B35B-66F4C0B9A0F6}'
  AppsAndFeaturesEntries:
  - DisplayName: innovaphone myApps 1611009
    ProductCode: '{AFF4AD43-A706-4820-B35B-66F4C0B9A0F6}'
    UpgradeCode: '{41FF4E29-A422-46F6-8C0F-F7D9B30A32B6}'
- Architecture: x64
  InstallerUrl: https://store.innovaphone.com/release/1700300/innovaphone-appstore?filename=1611009myappswindowsmyAppsSetup.msi&nameout=myAppsSetup.msi&update=true
  InstallerSha256: 0AA21BD1F19FB4DBCE315B593F49B737CEC78204B64D952AECF59FAFA59DB65D
  ProductCode: '{FE246EB2-5B75-4E04-8DA7-424F48EED3B5}'
  AppsAndFeaturesEntries:
  - DisplayName: innovaphone myApps 1611009
    ProductCode: '{FE246EB2-5B75-4E04-8DA7-424F48EED3B5}'
    UpgradeCode: '{41FF4E29-A422-46F6-8C0F-F7D9B30A32B6}'
ManifestType: installer
ManifestVersion: 1.12.0
