# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.267
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.267/anchors_0.1.267_windows_amd64.zip
  InstallerSha256: EA6B9D49BDBA8D0AD77EC2F8786D65C0C17CA86EC5375C0965AA4574D472788D
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.267/anchors_0.1.267_windows_arm64.zip
  InstallerSha256: 15123AC6EFCC8611098A50816DE9037035F68943910F9F1EE6F1B4E81AB24EAA
ManifestType: installer
ManifestVersion: 1.12.0
