# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: OpenWhisperSystems.Signal.Beta
PackageVersion: 8.30.0-beta.1
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: b39ac3a0-cc73-5ec2-ba18-5ab3c4de1ca1
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- ProductCode: b39ac3a0-cc73-5ec2-ba18-5ab3c4de1ca1
Installers:
- Architecture: x64
  InstallerUrl: https://updates.signal.org/desktop/signal-desktop-beta-win-8.30.0-beta.1.exe
  InstallerSha256: BB3A3969207613DD54055F851B47353700E6B87D69BC6F644EB5DEA14C5C8B8B
ManifestType: installer
ManifestVersion: 1.28.0
