# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PWPW.SigillumManager
PackageVersion: 1.0.17
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silentWithProgress
InstallerSwitches:
  Silent: install --accept-licenses --confirm-command --auto-answer installationErrorWithCancel=Ignore
  SilentWithProgress: install --accept-licenses --confirm-command --auto-answer installationErrorWithCancel=Ignore
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-09-03
Installers:
- Architecture: x86
  InstallerUrl: https://sigillum.pl/binaries/content/assets/Pliki/Sigman/Windows/Sigman_1.0.17.exe
  InstallerSha256: 268960F84557992E7F7FAEFA6CD8A2829D9236ABACD110E304DE15574FCABF84
ManifestType: installer
ManifestVersion: 1.12.0
