# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: joyint.joy
PackageVersion: 0.22.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: joy.exe
  PortableCommandAlias: joy
Commands:
- joy
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/joyint/joy/releases/download/v0.22.0/joy-cli-x86_64-pc-windows-msvc.zip
  InstallerSha256: 9B5AE14BE980EC1E0EC6A540518F92AD5B537278BCDB3A6B4A677EF481B15587
ManifestType: installer
ManifestVersion: 1.12.0
