# Automatically updated by the winget bot at 2026/Oct/04
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.28.0.schema.json

PackageIdentifier: PrestoSoft.ExamDiff
PackageVersion: 1.9.4.3
PackageLocale: zh-CN
License: 免费软件
ShortDescription: 免费可视化文件比较工具
Description: ExamDiff 是一款免费的 Windows 可视化文件对比工具，操作快捷简便，并具备多项用户期待已久的文件比对实用功能。
Tags:
- diff
- patch
- 合并
- 文件
- 文件夹
- 比较
ManifestType: locale
ManifestVersion: 1.28.0
