# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: newdee.Magpie
PackageVersion: 0.5.10
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.5.10/magpie_0.5.10_x64-setup.exe
  InstallerSha256: A1B60F2C26184674B04D8ED1F850A31C2F5EE5AB7B99FD73CD0F96B3EE2ABB87
  ProductCode: magpie
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/newdee/magpie/releases/download/v0.5.10/magpie_0.5.10_x64_en-US.msi
  InstallerSha256: 6ABE958AC1016C8A6378BD467D5C9934A82B7E317F649F7463FEF2706A356541
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{F7610D0C-F604-4BD1-A483-7E38272C91E6}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{285F4DB5-673C-524F-B28E-235FEC26AD24}'
ManifestType: installer
ManifestVersion: 1.12.0
