# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NimbusAgent.Nimbus
PackageVersion: 7.35.1
InstallerType: wix
ProductCode: '{6A2EFF03-D76E-48F1-9B1F-723D18763F55}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nimbus-agent/Nimbus/releases/download/v7.35.1/nimbus-headless-windows-x64.msi
  InstallerSha256: 75AEC4CC2108CE79C7483CD76A0CD6F7EF90EABC4EA6B2E0E4D2175F1FAE8A9A
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
