# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: snapetech.iptvtunerr
PackageVersion: 0.1.86
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: iptv-tunerr-v0.1.86-windows-amd64/iptv-tunerr.exe
  PortableCommandAlias: iptv-tunerr
Commands:
- iptv-tunerr
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/snapetech/iptvtunerr/releases/download/v0.1.86/iptv-tunerr-v0.1.86-windows-amd64.zip
  InstallerSha256: 311ba182d539f32fc7b8a0214d2a8255c64da9beb02aa5f52a970710df22859d
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-01
