# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: szTheory.exifcleaner
PackageVersion: 4.5.0
InstallerLocale: en-US
InstallModes:
- silent
FileExtensions:
- gif
- jpg
- m4a
- mov
- mp4
- pdf
- png
- tiff
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/szTheory/exifcleaner/releases/download/v4.5.0/ExifCleaner.Setup.4.5.0.exe
  InstallerSha256: CEA672BE3A969BDA26CE2E967B04E4ACD4D6889F4DDD48B1B203A779C4A416BA
  UpgradeBehavior: install
  ProductCode: 8457e380-8acb-5e7f-a000-5966971ba7cc
  AppsAndFeaturesEntries:
  - DisplayName: ExifCleaner 4.5.0
    ProductCode: 8457e380-8acb-5e7f-a000-5966971ba7cc
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/szTheory/exifcleaner/releases/download/v4.5.0/ExifCleaner.4.5.0.portable.exe
  InstallerSha256: 23ABF7223B8DF5F608D340E686A89D32A3A1E81CC6C9B47012B016E5355639DE
  UpgradeBehavior: uninstallPrevious
ManifestType: installer
ManifestVersion: 1.12.0
