# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DuckDuckGo.DesktopBrowser.Preview
PackageVersion: 0.176.0.0
Platform:
- Windows.Universal
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallerType: msix
Protocols:
- http
- https
FileExtensions:
- htm
- html
- pdf
PackageFamilyName: DuckDuckGo.DesktopBrowserPreview_ya2fgkz3nks94
Capabilities:
- internetClient
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://windows-cdn.duck.com/d5c04536-5379-4709-8d19-d13fdd456ff6/preview/0.176.0.0/DuckDuckGo%20Preview_0.176.0.0.msixbundle
  InstallerSha256: D8E5A973FB06A5B1688870B819E0386C08DEF9EC719DDC5C8C977181D42DA769
  SignatureSha256: AF883F510CEB4DE6BDAB4AC7F9DB91A2299D6613B3C7C8000008845D104DADD2
- Architecture: arm64
  InstallerUrl: https://windows-cdn.duck.com/d5c04536-5379-4709-8d19-d13fdd456ff6/preview/0.176.0.0/DuckDuckGo%20Preview_0.176.0.0.msixbundle
  InstallerSha256: D8E5A973FB06A5B1688870B819E0386C08DEF9EC719DDC5C8C977181D42DA769
  SignatureSha256: AF883F510CEB4DE6BDAB4AC7F9DB91A2299D6613B3C7C8000008845D104DADD2
ManifestType: installer
ManifestVersion: 1.12.0
