# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: CircleCI.CLI
PackageVersion: 1.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: circleci.exe
  PortableCommandAlias: circleci
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.1.0/circleci-cli_1.1.0_windows_amd64.zip
  InstallerSha256: ADF1930FCC2A4C88F681539D2FFE6F1C4AB6EA315B89EC2100E71221805B920F
- Architecture: arm64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.1.0/circleci-cli_1.1.0_windows_arm64.zip
  InstallerSha256: 7C4C1B92EE747AC403532EB2F57651C982A37A243A7F9DE4B9EEE10D08989D5B
ManifestType: installer
ManifestVersion: 1.28.0
