# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: CircleCI.CLI
PackageVersion: 1.0.52172
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: circleci.exe
  PortableCommandAlias: circleci
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.52172/circleci-cli_1.0.52172_windows_amd64.zip
  InstallerSha256: 549DBD399AB8E2C2E5AEC265BF204E1F9A121B25228489484D2D955F9A652C03
- Architecture: arm64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.52172/circleci-cli_1.0.52172_windows_arm64.zip
  InstallerSha256: A5AD424A58BBCA60375AAE4DA866D6079E82E8D6743921D0E89B94781566A98A
ManifestType: installer
ManifestVersion: 1.28.0
