# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Ccache.Ccache
PackageVersion: 4.14.1
PackageLocale: en-US
Publisher: Joel Rosdahl
PublisherUrl: https://ccache.dev/
PublisherSupportUrl: https://github.com/ccache/ccache/discussions
Author: Joel Rosdahl, Andrew “Tridge” Tridgell, and Ccache Contributors
PackageName: Ccache
PackageUrl: https://github.com/ccache/ccache
License: GPL-3.0
LicenseUrl: https://github.com/ccache/ccache/blob/HEAD/LICENSE.adoc
ShortDescription: Ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again.
Description: Ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Ccache is free software, released under the GNU General Public License version 3 or later.
Moniker: ccache
Tags:
- c
- c++
- ccache
- compilation
- cross-platform
- open-source
- optimization
- speedup
ReleaseNotes: |-
  New deliverables
  - Added musl static binary release for Linux s390x.
    [contributed by Ludovic Henry]

  Bug fixes
  - Restored storage helper lock compatibility with ccache versions earlier than 4.14.
    [contributed by Joel Rosdahl]
  - Fixed lookup of GCC 9+ profile data for object files in subdirectories and added support for GCC’s -fprofile-partial-training option.
    [contributed by Yichen Yan]
  - Fixed the output location of files produced by GCC’s -fdump-ipa-clones option.
    [contributed by Jiri Slaby]
  - Fixed hashing of C++20 module files found via Clang’s -fprebuilt-module-path option, preventing false cache hits when a module changes.
    [contributed by Gareth Andrew Lloyd]
  - Made ccache reject clang-cl’s /clang: option and MSVC’s /FA and /Fa options instead of potentially caching compilations incorrectly.
    [contributed by Joel Rosdahl]
  - Fixed cleanup of temporary response files on Windows.
    [contributed by Joel Rosdahl]

  Build improvements
  - Avoided passing a superfluous -include option when building with MSVC.
    [contributed by Joel Rosdahl]

  Test improvements
  - Made the remote_file and remote_only test suites work on Windows.
    [contributed by Joel Rosdahl]
  - Improved MSVC test failure diagnostics.
    [contributed by Joel Rosdahl]
  - Improved skip messages for test suites known to fail on Windows.
    [contributed by Joel Rosdahl]
ReleaseNotesUrl: https://ccache.dev/releasenotes.html#_ccache_4_14_1
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://ccache.dev/documentation.html
ManifestType: defaultLocale
ManifestVersion: 1.12.0
