PackageIdentifier: ProtagonistLabs.FileLabs
PackageVersion: 1.0.30
InstallerType: inno
Scope: user
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/limburatorul/file-labs/releases/download/v1.0.30/FileLabs-1.0.30-setup.exe
  InstallerSha256: 4B651FF21111BD9F68448FF3E5419443DAA1F547928C3EF8FB2B7F1FE51B96C9
ManifestType: installer
ManifestVersion: 1.6.0
