# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 155.1.99.2
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.2/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 80A9C8510AF9DAAE7E13A04628E4DB5B27B989306CA75321E389D24175D67997
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.2/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 83EBC391B6D9E664F50E2C0D19392A2D3A26615AFA05D0AAEDC59EAC76378200
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.2/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 23CC2A2D216A2B1C3A9870D72501FCDE7352E6353B8B8621E7F628D61FF44EAC
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.2/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: D428FBDBFAFF5DA576530E0C347E201A1998E2EB03B695ABE7F07111D22F56A5
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.2/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 06A6B1E3B1A330AC31DFCADBFD6443084C317B6D3E33CC47B560E3D08293D3D7
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.99.2/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: 97044CB20E50C09AFE1163F29CCD6B5B419F7B5A57982E26D0C88F8CDC9AC9C5
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
