# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Kesomannen.Gale
PackageVersion: 1.23.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- gale
Protocols:
- gale
- ror2mm
FileExtensions:
- r2z
ProductCode: '{DFBC0062-0947-4584-8A3A-2078306A421D}'
ReleaseDate: 2026-10-02
AppsAndFeaturesEntries:
- Publisher: kesomannen
  ProductCode: '{DFBC0062-0947-4584-8A3A-2078306A421D}'
  UpgradeCode: '{23AC549F-AF10-5914-9BE0-4E436D5FE9AA}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/Gale'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Kesomannen/gale/releases/download/1.23.0/Gale_1.23.0_x64_en-US.msi
  InstallerSha256: 9C0CF6AD31556406088673D014ED9AABCD84B430884B006327B5ADD77047C458
ManifestType: installer
ManifestVersion: 1.12.0
