# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ru
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win32/ru/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: E5371D61CE8A7859278AE909DA3FD1ACB8928B507AEA05A3A5D08C253E49553D
  ProductCode: Mozilla Thunderbird 157.0.1 (x86 ru)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0.1/win64/ru/Thunderbird%20Setup%20157.0.1.exe
  InstallerSha256: 4129B9D822D4AF9FC53E404A746D9EA88208028222CE950B2D6695138D0CAFB0
  ProductCode: Mozilla Thunderbird 157.0.1 (x64 ru)
ManifestType: installer
ManifestVersion: 1.12.0
