# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: idrassi.HashCheckShellExtension
PackageVersion: 2.6.3.0
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: uninstallPrevious
FileExtensions:
- md5
- sfv
- sha1
- sha256
- sha512
ProductCode: idrassi.HashCheckShellExtension
AppsAndFeaturesEntries:
- DisplayName: HashCheck Shell Extension
  Publisher: idrassi
  ProductCode: idrassi.HashCheckShellExtension
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/idrassi/HashCheck/releases/download/v2.6.3/HashCheckSetup-v2.6.3.0.exe
  InstallerSha256: CD890774839177B234A1165FD459DDEB830274EF7D81B289DDB70D43AE5983FA
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-07
