# Automatically updated by the winget bot at 2026/Oct/02
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.28.0.schema.json

PackageIdentifier: AirMyPC.AirMyPC
PackageVersion: "8.1.0"
PackageLocale: en-US
Publisher: AirMyPC
PublisherUrl: https://www.airmypc.com/
PublisherSupportUrl: https://www.airmypc.com/support.htm
PackageName: AirMyPC
License: propriatary
Copyright: Copyright © AirMyPC.
ShortDescription: Apple TV / Chromecast / Miracast universal sender for windows
PurchaseUrl: https://www.airmypc.com/purchase.htm
ManifestType: defaultLocale
ManifestVersion: 1.28.0
