# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: j178.Prek
PackageVersion: 0.5.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: prek.exe
  PortableCommandAlias: prek
InstallModes:
- silent
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/j178/prek/releases/download/v0.5.4/prek-x86_64-pc-windows-msvc.zip
  InstallerSha256: 244BC3EEADE60A0EE586DFE9F5C90BD1C1D790514009AAD2C7055DCB731A3E50
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/j178/prek/releases/download/v0.5.4/prek-aarch64-pc-windows-msvc.zip
  InstallerSha256: BB82DD1039F602E6B1E57B8B113B5C0000EEA35AE2931BF0C1AE7E61CE3DF697
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
