# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Atlassian.ServiceManagementLTS
PackageVersion: 11.3.12
InstallerType: exe
InstallerSwitches:
  Silent: -q
  SilentWithProgress: -q -console
Installers:
- Architecture: x64
  InstallerUrl: https://www.atlassian.com/software/jira/downloads/binary/atlassian-servicedesk-11.3.12-x64.exe
  InstallerSha256: CF51DF6978C6D91BAD197BBC0B45EDA4D0BBC82FC8102B9F7B930E42FE8938B4
ManifestType: installer
ManifestVersion: 1.12.0
