# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KangLin.SerialPortAssistant
PackageVersion: 0.5.35
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: SerialPortAssistant
ReleaseDate: 2026-10-01
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\SerialPortAssistant'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/KangLin/SerialPortAssistant/releases/download/v0.5.35/SerialPortAssistant_v0.5.35_win32_msvc2019_qt5.15.2_Setup.exe
  InstallerSha256: 5BE5D1F078441239DA09B17A5A1F3D0B0D518F942A81CF2113CF44AC5FBD91EA
- Architecture: x64
  InstallerUrl: https://github.com/KangLin/SerialPortAssistant/releases/download/v0.5.35/SerialPortAssistant_v0.5.35_win64_msvc2022_64_qt6.10.3_Setup.exe
  InstallerSha256: 12A05A94FE9A2ECEC57379AC80D5F42860AAF34FB9A8ECA5833B4A78DDF21BF6
- Architecture: arm64
  InstallerUrl: https://github.com/KangLin/SerialPortAssistant/releases/download/v0.5.35/SerialPortAssistant_v0.5.35_win64_msvc2022_arm64_qt6.10.3_Setup.exe
  InstallerSha256: 7B21A29CD1A7AFEB07662B73A6596C7E2CC959289EBE9DBBC2AD81C06EE610C4
ManifestType: installer
ManifestVersion: 1.12.0
