# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JDEProjects.SimpleFirearmLogbook
PackageVersion: 1.8.2
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: Simple Firearm Logbook
  Publisher: JDE Projects
  DisplayVersion: 1.8.2
  InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JDE-Projects/Simple-Firearm-Logbook/releases/download/v1.8.2/SimpleFirearmLogbook-v1.8.2-setup.exe
  InstallerSha256: C7C7121CC7CA1D8A196840510BCD6ADBD93C126C31166B6EB9AB90FB0074F827
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-06
