# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SteveTheKiller.KillerNotes
PackageVersion: 1.4.3
InstallerType: portable
InstallModes:
- silent
UpgradeBehavior: install
FileExtensions:
- kndb
- knote
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SteveTheKiller/KillerNotes/releases/download/v1.4.3/KillerNotes.exe
  InstallerSha256: 67CADACF516E65C1CF90C3B9E1DDCDC949E160051CB1C7E9F819AD9DFEE76E38
ManifestType: installer
ManifestVersion: 1.12.0
