# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: coolcoala.KoalaClash
PackageVersion: 1.5.0
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
Protocols:
- clash
- koala-clash
ProductCode: 25235723-1264-5519-9df5-efe4433792a8
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/coolcoala/koala-clash/releases/download/1.5.0/Koala.Clash_x64-setup.exe
  InstallerSha256: ABBBF72A9111BAF4993D6FDE6D3F6CE970B2D43FA33AB992A59AB2A2E9EF3FBA
- Architecture: arm64
  InstallerUrl: https://github.com/coolcoala/koala-clash/releases/download/1.5.0/Koala.Clash_arm64-setup.exe
  InstallerSha256: 1A6B34C996921CEE3B0B8CCDAC21DB57B7861D7C63FE271E5496D5E4658209FD
ManifestType: installer
ManifestVersion: 1.12.0
