# Created with WinGet Updater using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: pbek.QOwnNotes
PackageVersion: 26.10.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: QOwnNotes.exe
  PortableCommandAlias: qownnotes.exe
ReleaseDate: 2026-10-01
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/pbek/QOwnNotes/releases/download/v26.10.0/QOwnNotes.zip
  InstallerSha256: A988142EFF1E370DCB25E625DED9089434F8919413C90B42B81F8A29E0E7C591
ManifestType: installer
ManifestVersion: 1.12.0
