# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SureshJanakiReddy.GeminiDesktop
PackageVersion: 0.2.30
InstallerType: wix
Commands:
- gemini-desktop
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/sureshjsreddy/gemini-desktop/releases/download/v0.2.30/Gemini.Desktop_0.2.30_x64_en-US.msi
  InstallerSha256: F5F710AF7E7527BA46B9791E98ED0FDE41537A5BE18549D4BB7DF67703C93168
  ProductCode: '{07F2418A-086B-454B-9A84-E78924683B64}'
  AppsAndFeaturesEntries:
  - ProductCode: '{07F2418A-086B-454B-9A84-E78924683B64}'
    UpgradeCode: '{985AFC27-7B36-5C34-AD21-7F9C5862BA55}'
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/sureshjsreddy/gemini-desktop/releases/download/v0.2.30/GeminiDesktop-Portable.exe
  InstallerSha256: B315FF513661001A5AC26DA51BB0E6F34A0C541FD3677E25ED4676F4CB5D709C
  Commands:
  - gemini-desktop
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05