# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: CircleCI.CLI
PackageVersion: 1.0.52041
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: circleci.exe
  PortableCommandAlias: circleci
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.52041/circleci-cli_1.0.52041_windows_amd64.zip
  InstallerSha256: 88DB8CF4219FB5AA929110EACB256CFE34B2551922B13CEAF3A20831EF5B93E0
- Architecture: arm64
  InstallerUrl: https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.52041/circleci-cli_1.0.52041_windows_arm64.zip
  InstallerSha256: 0F2017638FB7D2F2AA7AC4FEEDDDBEA677C269013613F64B01A49543C02F4C4C
ManifestType: installer
ManifestVersion: 1.28.0
