# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: InstaZDLL.WaveFlow
PackageVersion: 1.8.3
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/InstaZDLL/WaveFlow/releases/download/v1.8.3/WaveFlow_1.8.3_windows-x86_64-setup.exe
  InstallerSha256: 3161E007EA1C61D2D7B39C8DD64FC577754EE9D87B64CDE21521CE485D98CDDE
  ProductCode: WaveFlow
  AppsAndFeaturesEntries:
  - ProductCode: WaveFlow
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\WaveFlow'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/InstaZDLL/WaveFlow/releases/download/v1.8.3/WaveFlow_1.8.3_windows-x86_64.msi
  InstallerSha256: 2EDBD717DCEBD08CD30A18CE7DAF1FF7103E0EA9CFE1AB4109BDE7610254164D
  ProductCode: '{512C4314-6A55-48A7-8A3A-9F33BE646F30}'
  AppsAndFeaturesEntries:
  - ProductCode: '{512C4314-6A55-48A7-8A3A-9F33BE646F30}'
    UpgradeCode: '{2CEDC898-5DE1-5FBD-8FF9-889784A3E123}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WaveFlow'
ManifestType: installer
ManifestVersion: 1.12.0
