# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenTubeX.OpenTubeX
PackageVersion: 0.35.2
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Protocols:
- opentubex
ProductCode: a38f022d-fec2-5f80-a7fe-620ccf1a2767
ReleaseDate: 2026-09-30
AppsAndFeaturesEntries:
- DisplayName: OpenTubeX 0.35.2
  ProductCode: a38f022d-fec2-5f80-a7fe-620ccf1a2767
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/OpenTubeX/OpenTubeX/releases/download/v0.35.2-beta/opentubex-0.35.2-beta-setup-x64.exe
  InstallerSha256: 81C546E3A87F954A8B7B4C5E9E77D0A7C56742FEF5E2EE68396BA886D4C6ADE6
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/OpenTubeX/OpenTubeX/releases/download/v0.35.2-beta/opentubex-0.35.2-beta-setup-x64.exe
  InstallerSha256: 81C546E3A87F954A8B7B4C5E9E77D0A7C56742FEF5E2EE68396BA886D4C6ADE6
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/OpenTubeX/OpenTubeX/releases/download/v0.35.2-beta/opentubex-0.35.2-beta-setup-arm64.exe
  InstallerSha256: B0A00D9B57470B0FD03068614DF2FB3B21E8B68D29A6F0045136F473B5C07282
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/OpenTubeX/OpenTubeX/releases/download/v0.35.2-beta/opentubex-0.35.2-beta-setup-arm64.exe
  InstallerSha256: B0A00D9B57470B0FD03068614DF2FB3B21E8B68D29A6F0045136F473B5C07282
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
