# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: QuinGillespie.Paperback
PackageVersion: 1.0.0
InstallerType: inno
Scope: machine
InstallerSwitches:
  Custom: /MERGETASKS=addtopath,startmenuicon
UpgradeBehavior: install
Commands:
- paperback
- pb
ProductCode: Paperback_is1
ReleaseDate: 2026-10-03
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Paperback'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/trypsynth/paperback/releases/download/1.0.0/paperback_setup-x64.exe
  InstallerSha256: 31FB8A4A04215B7F73F56640F5BF34808E631A0B3B9BD2F59A778F2198252679
- Architecture: arm64
  InstallerUrl: https://github.com/trypsynth/paperback/releases/download/1.0.0/paperback_setup-arm64.exe
  InstallerSha256: 1DA11F03A90C21E0F43B33C956C801DF6F364AD79BDEB3321B8BCE4FC15DD6D0
ManifestType: installer
ManifestVersion: 1.12.0
