# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Softland.doPDF.11
PackageVersion: 11.9.530
InstallerType: burn
Scope: machine
InstallerSwitches:
  InstallLocation: -pInstallFolder="<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: '{51dd8753-7a82-4a95-bbb0-7722c0b598d4}'
ReleaseDate: 2026-10-08
AppsAndFeaturesEntries:
- UpgradeCode: '{02F33464-D3EC-41A9-B832-377320C9A6E5}'
Installers:
- Architecture: x86
  InstallerUrl: https://download.dopdf.com/download/setup/dopdf-11.exe
  InstallerSha256: 265642E87A145CC43E040C3DE305216F8C9E2320D61D8CFD473578D36ED05B9B
ManifestType: installer
ManifestVersion: 1.12.0
