# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Signum.Signum
PackageVersion: 1.1.7
InstallerType: nullsoft
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Commands:
- signum
Installers:
- Architecture: x64
  InstallerUrl: https://appbank.pw/signum/downloads/windows/Signum-setup.exe
  InstallerSha256: 81d55442a0dbadbc6c58a5dbef3e0a8aaa2e24513981e8e234b4496d2ed0e898
ManifestType: installer
ManifestVersion: 1.12.0
