# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: ScryerMedia.Weaver
PackageVersion: 0.14.7
InstallerType: msi
InstallModes:
- silent
UpgradeBehavior: install
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/scryer-media/weaver/releases/download/weaver-v0.14.7/weaver-windows-x86_64.msi
  InstallerSha256: 841D2031C2D7CB689AB12D473E2FA225E392CBC1A2D4F3DD09DAA36FC6A5B3B2
  ProductCode: '{78A55849-752D-4482-AD77-DB3750F914E4}'
- Architecture: arm64
  InstallerUrl: https://github.com/scryer-media/weaver/releases/download/weaver-v0.14.7/weaver-windows-arm64.msi
  InstallerSha256: B8E76F6AEF782C0A0CBAC887A72151C7400ED695B49F544366227E0A493E5E5D
  ProductCode: '{014B48A6-44D1-4FED-9DBA-C339FA1C1946}'
ManifestType: installer
ManifestVersion: 1.10.0
