# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Postman.Postman.arm64
PackageVersion: 12.31.1
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- postman
ProductCode: Postman
ReleaseDate: 2026-10-05
Installers:
- Architecture: arm64
  InstallerUrl: https://dl.pstmn.io/download/version/12.31.1/windows_arm64
  InstallerSha256: BA834D36715E72428E774E6BBB4638ED9EDAA89EC541653B3B5252E34118700A
ManifestType: installer
ManifestVersion: 1.12.0
