# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: facebook.pyrefly
PackageVersion: 1.3.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pyrefly.exe
InstallModes:
- silent
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/facebook/pyrefly/releases/download/1.3.2/pyrefly-windows-x86_64.zip
  InstallerSha256: 3F23B1807033AFF34C96F65EAD4958D1493FBCBB087CC5BA3AB3CE9EBBD95911
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/facebook/pyrefly/releases/download/1.3.2/pyrefly-windows-arm64.zip
  InstallerSha256: 46E7A5EEEF2EB4A11E88AEBFF2A49F5D45F31250221BCEF1EF1B9CBA08513BB1
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
