# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.247
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.247/anchors_0.1.247_windows_amd64.zip
  InstallerSha256: 3FDD2E831CA3870EC706F564507BD1D2C685E47665427B41C392E065A3A53C70
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.247/anchors_0.1.247_windows_arm64.zip
  InstallerSha256: D694C83BDCB46FDA1B59D86A20281148EE36FD04EF898E3E111C3D5DAB42C375
ManifestType: installer
ManifestVersion: 1.12.0
