# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MartinBresson.Executor
PackageVersion: 2.4.2
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: Executor_is1
ReleaseDate: 2026-10-10
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Executor'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/executordk/executor-community/releases/download/v2.4.2/ExecutorSetup_v2.4.2.exe
  InstallerSha256: 46230B0AAF8F22B491678D3E8CA76F255FF29FCF248CE0B401B343D3D0BFB6C1
ManifestType: installer
ManifestVersion: 1.12.0
