# Automatically updated by the winget bot at 2026/Oct/06
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: CCPGames.EVEOnline
PackageVersion: 1.17.1
InstallerType: exe
Scope: user
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://launcher.ccpgames.com/eve-online/release/win32/x64/eve-online-latest+Setup.exe
  InstallerSha256: B4BC3CDC60D98B83E83BB1A997759FCAA575035BCD6D430D26C3AE5EEF9FD301
  ProductCode: "eve-online"
ManifestType: installer
ManifestVersion: 1.28.0
