# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GeoGebra.Geometry
PackageVersion: 6.0.931
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
FileExtensions:
- ggb
ProductCode: GeoGebra_Geometry
ReleaseDate: 2026-10-05
Installers:
- Architecture: x86
  InstallerUrl: https://download.geogebra.org/installers/6.0/geometry/GeoGebraGeometry-Windows-Installer-6-0-931-2.exe
  InstallerSha256: 36344E58A76CF7FEBBDC21ADA5F8083E61B06A2D2AE28086177D2D6394E3C9C1
ManifestType: installer
ManifestVersion: 1.12.0
