# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.VFSforGit
PackageVersion: 2.0.26259.1
InstallerType: inno
Scope: machine
ProductCode: '{489CA581-F131-4C28-BE04-4FB178933E6D}_is1'
ReleaseDate: 2026-09-17
AppsAndFeaturesEntries:
- DisplayName: VFS for Git version 2.0.26259.1
  Publisher: Microsoft
  ProductCode: '{489CA581-F131-4C28-BE04-4FB178933E6D}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\VFS for Git'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/VFSForGit/releases/download/v2.0.26259.1/SetupGVFS.2.0.26259.1.exe
  InstallerSha256: 845EBAD5DE04FF52000DD14DEEECE4AFDBE8EB22A062E6C8CD5E839D35C0E0D9
ManifestType: installer
ManifestVersion: 1.28.0
