# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.530.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-10-03
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.530.0&arch=x86
  InstallerSha256: B2CE421DBFECE73A4F4C225F9A64E2D0AC27AD49F6504094E1AF4218589B4C4D
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.530.0&arch=amd64
  InstallerSha256: D4398900A46CD2EF337CAB71DEE05BDE82968C9FB826BC8C681E99A05DB661B6
ManifestType: installer
ManifestVersion: 1.28.0
