# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.fr
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/fr/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 393951D6C8658CAC26CF802CF272CB440C3EBA7493E03D3C4194F7505CBF2537
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/fr/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 4C4B3DB83D94906A5E121C6EE1B6439DB5B9267CB31C2C4E27FE99F02C9E80F4
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/fr/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 6920D1C78B92BC592D2A29F36217BA93BD17049900D8A88F3AD5AA51F43D08D2
ManifestType: installer
ManifestVersion: 1.12.0
