# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: JinweiZhiguang.MasterGo
PackageVersion: 1.12.1
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: MasterGo
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://static-nc.mastergo.com/plugins/desktop/windows/MasterGo-1.12.1.exe
  InstallerSha256: 55C0D5FA0E0EFB2698CB58193342880E08725AE56DBCCA1C9D8F26075B7739B1
ManifestType: installer
ManifestVersion: 1.12.0
