# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Argente.SystemManager
PackageVersion: 1.0.5.1
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART --hidden
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART --hidden
UpgradeBehavior: install
ProductCode: Argente System Manager 3.0
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerx86
  InstallerSha256: CA1F3885891E2180B15F0BC18B1C5C0F2515784FB12741CFD8C0950D60979004
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerx64
  InstallerSha256: 3152D73268C48CD82A34F1B9CD263CB981C7FD0630BDA40392565F74951564A1
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/systemmanagerarm64
  InstallerSha256: 03D8F16F182501893EDA950E28AAD9473654B2F641B460351D8CB5C93BD78211
ManifestType: installer
ManifestVersion: 1.12.0
