# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Recol.DLSSUpdater
PackageVersion: 5.1.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/Recol/DLSS-Updater/releases/download/V5.1.1/DLSS.Updater.5.1.1.msi
  InstallerSha256: 5A620FFA12FA77AA705C729B5B71050C328FEDB8FA7D592F094B125D7D9A2790
  InstallerSwitches:
    Custom: /norestart
  UpgradeBehavior: install
  ProductCode: '{5F2D1773-29A8-43D5-B7F8-B373D34F11D6}'
ManifestType: installer
ManifestVersion: 1.6.0
