# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.sv-SE
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/sv-SE/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 6046A6B360CC86164280C7849C52BAA75F13B97266E3EB59F6CE567641C6D5D5
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/sv-SE/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: F3EEB02E5465D57E3A47121D2AD53E99922A9F2044BC42D96A7AC9BC5A47A231
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/sv-SE/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 3707FB219B3CCD1EE86EAE195036DEA2DC7E84F8391354DA0322D2F7B9896ED5
ManifestType: installer
ManifestVersion: 1.12.0
