# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Zoho.Ulaa
PackageVersion: 155.0.8059.40
InstallerType: exe
InstallModes:
- silent
InstallerSwitches:
  Log: --verbose-logging --log-file="<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 4
  ReturnResponse: downgrade
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Zoho Ulaa
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://ulaa.zoho.com/release/win/Ulaa-Browser-v2.50.0.exe
  InstallerSha256: B29002A11C00A568CA10278FCFC64DE9EC18061ADB62153C1FD0A6572716DF6D
  InstallerSwitches:
    Custom: --do-not-launch-chrome
- Architecture: x64
  Scope: machine
  InstallerUrl: https://ulaa.zoho.com/release/win/Ulaa-Browser-v2.50.0.exe
  InstallerSha256: B29002A11C00A568CA10278FCFC64DE9EC18061ADB62153C1FD0A6572716DF6D
  InstallerSwitches:
    Custom: --do-not-launch-chrome --system-level
ManifestType: installer
ManifestVersion: 1.12.0
