# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: ppy.osu
PackageVersion: 2026.1005.0-lazer
InstallerType: exe # Velopack
Scope: user
InstallModes:
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --installto "<INSTALLPATH>"
  Log: --log "<LOGPATH>"
Protocols:
- osu
- osump
FileExtensions:
- olz
- osk
- osr
- osz
ProductCode: osulazer
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- ProductCode: osulazer
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\osulazer'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ppy/osu/releases/download/2026.1005.0-lazer/install.exe
  InstallerSha256: 6E8EDD56E9B7AA394AA6E62B618559C30E49E81A10AA7E9C98045815006F0582
ManifestType: installer
ManifestVersion: 1.28.0
