# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.rm
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/rm/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 111FA883E0252C3F1D03B2780D77694F0E580F2721906BCC1F732023FDD3EBB3
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/rm/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 10750E0997DAA9D4F4B6653D967BEECCC0A4E4427D570E82AFB7972A6AC529F1
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/rm/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: AA04007AAB0DBC8D3BD7AB93367684B136BB979895DB359EA2CDDF1299A4583C
ManifestType: installer
ManifestVersion: 1.12.0
