# Automatically updated by the winget bot at 2026/Oct/02
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: Raise3D.ideaMaker
PackageVersion: 5.5.0.8810
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.28.0
