# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.28.0.schema.json

PackageIdentifier: HypixelStudios.Hytale
PackageVersion: 2026.09.30-326a0c2
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.28.0
