# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.EdgeWebView2Runtime
PackageVersion: 155.0.4283.45
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /silent /install
  SilentWithProgress: /silent /install
InstallerSuccessCodes:
- -2147219416
- -2147219187
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
ProductCode: Microsoft EdgeWebView
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/1c7aac1d-ac1f-45e5-895d-a116e7a450ed/MicrosoftEdgeWebView2RuntimeInstallerX86.exe
  InstallerSha256: 48C16A41B92533B0258D689589693DB9F586DF3AC58B5C0E4AF5358962397642
- Architecture: x86
  Scope: machine
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/1c7aac1d-ac1f-45e5-895d-a116e7a450ed/MicrosoftEdgeWebView2RuntimeInstallerX86.exe
  InstallerSha256: 48C16A41B92533B0258D689589693DB9F586DF3AC58B5C0E4AF5358962397642
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/7c7c0e6f-8cb5-406a-8e51-df0c62011e55/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  InstallerSha256: 2A6ADD76C37BFA872EB8C2B22D45B3216B8E2A1F193E0774006340FF62AC5FA0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/7c7c0e6f-8cb5-406a-8e51-df0c62011e55/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  InstallerSha256: 2A6ADD76C37BFA872EB8C2B22D45B3216B8E2A1F193E0774006340FF62AC5FA0
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/e421c427-1bfa-44ea-9164-528c2d300e1e/MicrosoftEdgeWebView2RuntimeInstallerARM64.exe
  InstallerSha256: DEBF3E179D6F8C4CAE75AFE9359361E6D43C96ACAA5971E990FB81AB34703BA9
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/e421c427-1bfa-44ea-9164-528c2d300e1e/MicrosoftEdgeWebView2RuntimeInstallerARM64.exe
  InstallerSha256: DEBF3E179D6F8C4CAE75AFE9359361E6D43C96ACAA5971E990FB81AB34703BA9
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
