# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: DevProxy.DevProxy.Beta
PackageVersion: 4.0.0-beta.8
InstallerType: inno
Installers:
 - InstallerUrl: https://github.com/dotnet/dev-proxy/releases/download/v4.0.0-beta.8/dev-proxy-installer-win-x64-v4.0.0-beta.8.exe
   Architecture: x64
   InstallerSha256: 6cf781f294fd95e4cabdc5778c3e40d37938b2ee8c24560e47045814bbe59afe
ManifestType: installer
ManifestVersion: 1.28.0