# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: evilmartians.lefthook
PackageVersion: 2.2.0
InstallerType: portable
UpgradeBehavior: install
Commands:
- lefthook
ReleaseDate: 2026-10-07
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.2.0/lefthook_2.2.0_Windows_i386.exe
  InstallerSha256: C34DD24DA0068B5CCFE127A405D436876AD409CE84DB6FF9D0B2AC39CAD9C277
- Architecture: x64
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.2.0/lefthook_2.2.0_Windows_x86_64.exe
  InstallerSha256: 833D495222EA59E8B57570CD621A6562408C393043A957A441FCA62ACF27247C
- Architecture: arm64
  InstallerUrl: https://github.com/evilmartians/lefthook/releases/download/v2.2.0/lefthook_2.2.0_Windows_arm64.exe
  InstallerSha256: 59C7371B3CCD8D07C9D8D96583DABE03401250F4E949CD3B0FE8327E198B160E
ManifestType: installer
ManifestVersion: 1.12.0
