# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.Nightly.MSIX
PackageVersion: 159.2610.609.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
PackageFamilyName: Mozilla.MozillaFirefoxNightly_jag0gd4e3s9p2
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- DisplayName: Firefox Nightly
  Publisher: Mozilla Corporation
Installers:
- Architecture: x86
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-06-09-04-24-mozilla-central/firefox-159.0a1.multi.win32.installer.msix
  InstallerSha256: 85CB1CCBEF9A87E65D6DE0844F94E8ACF4B1765660FECCF5075EEDD5A4736457
  SignatureSha256: B8B248DFAE1C7C6A09E816B9C5AD973398171EFCDAEB8BC6F4ED31D1971ED3B7
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2610.609.0_x86__jag0gd4e3s9p2'
- Architecture: x64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-06-09-04-24-mozilla-central/firefox-159.0a1.multi.win64.installer.msix
  InstallerSha256: 232EC7083C8541D17E1B89DDE3A0971A2DBCB832F0F6101ACE4D580B1D60A873
  SignatureSha256: 88FCB13DFA85B6BFC141A231CBAB3C4091F129121655B798CE4E9FA93CC2F37E
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2610.609.0_x64__jag0gd4e3s9p2'
- Architecture: arm64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-06-09-04-24-mozilla-central/firefox-159.0a1.multi.win64-aarch64.installer.msix
  InstallerSha256: A41C03434B9A4D2352F0117A6BD702A4A4B6AD8E8C32A66CB1EF916A90D0BCAF
  SignatureSha256: F80E0221D1B659F67E282FD5F904C1E1AD6F65160FA9BDD470265E38B338D12A
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2610.609.0_arm64__jag0gd4e3s9p2'
ManifestType: installer
ManifestVersion: 1.12.0
