# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: AndrewNg.OpenWorker
PackageVersion: 0.3.0
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/andrewyng/openworker/releases/download/v0.3.0/OpenWorker-windows-setup.exe
  InstallerSha256: DD30BD766CA734F412CE988F33E996871E05DBB047C803E57F0AB872B7A07AAD
  ProductCode: OpenWorker
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\OpenWorker'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/andrewyng/openworker/releases/download/v0.3.0/OpenWorker-windows.msi
  InstallerSha256: 414A21E70F19194E00B41DE47D4884ABCDE85B9F55FC07B37F0313A5E6C9E95A
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{31E07331-9BCC-4376-9FAA-0D435D1EE95E}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{EE9E0539-FB13-5B97-9B6E-0C18C65E04BC}'
ManifestType: installer
ManifestVersion: 1.12.0
