# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.uz
PackageVersion: "157.0"
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0/win32/uz/Thunderbird%20Setup%20157.0.exe
  InstallerSha256: FD9B16FE2BF338574ED6CCE5B7A7AB6F6FAAFF6396C880144287523DDB94A44A
  ProductCode: Mozilla Thunderbird 157.0 (x86 uz)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/157.0/win64/uz/Thunderbird%20Setup%20157.0.exe
  InstallerSha256: 42CCA87E70FA6462F3DEB464D5B55AFCD38C2A4B593CAB85232A3A022606A15C
  ProductCode: Mozilla Thunderbird 157.0 (x64 uz)
ManifestType: installer
ManifestVersion: 1.12.0
