# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ptweezy.cronstable
PackageVersion: 1.2.61
InstallerType: burn
Scope: machine
UpgradeBehavior: install
Commands:
- cronstable
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ptweezy/cronstable/releases/download/1.2.61/cronstable-windows-amd64-setup.exe
  InstallerSha256: 5268F77273FDA823AA888D18985437BD5D95D68268BEC55BF538D37DF1875CB1
  ProductCode: '{5D472486-B897-4019-BF42-75AA5CA66031}'
  AppsAndFeaturesEntries:
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.61
    ProductCode: '{5D472486-B897-4019-BF42-75AA5CA66031}'
    UpgradeCode: '{E8D4C05B-5ED5-4850-826D-8BA6163E4F8A}'
    InstallerType: burn
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.61
    ProductCode: '{EF9B05A1-A9B4-4AF5-BAD4-D4BEDC120586}'
    UpgradeCode: '{B995CBA8-16CD-48F1-A13B-C4C4B927E7BE}'
    InstallerType: msi
- Architecture: arm64
  InstallerUrl: https://github.com/ptweezy/cronstable/releases/download/1.2.61/cronstable-windows-arm64-setup.exe
  InstallerSha256: DF59D87BA9EE30464B28BE3C3CA8A6BFF0209AA0CD2A9FD5235BA341D9FDD724
  ProductCode: '{7DD5EC82-6D32-4DA9-BF0E-4CBE7A19DC69}'
  AppsAndFeaturesEntries:
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.61
    ProductCode: '{7DD5EC82-6D32-4DA9-BF0E-4CBE7A19DC69}'
    UpgradeCode: '{E8D4C05B-5ED5-4850-826D-8BA6163E4F8A}'
    InstallerType: burn
  - DisplayName: cronstable
    Publisher: cronstable
    DisplayVersion: 1.2.61
    ProductCode: '{F4B34DFC-42B3-4A60-9404-A7D8E40A049C}'
    UpgradeCode: '{B995CBA8-16CD-48F1-A13B-C4C4B927E7BE}'
    InstallerType: msi
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
