# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Citadel5-JP.GS-Base
PackageVersion: "22.5"
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: exe
InstallerSwitches:
  Silent: /silent /no-start
  SilentWithProgress: /silent /no-start
  Interactive: /interactive
UpgradeBehavior: install
FileExtensions:
- csv
- dbf
- dbt
- ftp
- gsb
- html
- mp3
- pdf
- sql
- sqlite
- txt
- xls
- xlsx
- zip
ProductCode: GS-Base
AppsAndFeaturesEntries:
- DisplayVersion: 22.5 - Limited Trial Version
  ProductCode: GS-Base
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Citadel5-JP/GS-Base/releases/download/22.5/gsbase22.5_x64.exe
  InstallerSha256: E82955CFD80CCBB42C7272B231466280BCE10FDCBB914DC6EE433A375A39AA19
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-08
