# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: derekwisong.datui
PackageVersion: 0.4.5
Platform:
- Windows.Desktop
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: datui.exe
Scope: user
InstallModes:
- silent
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/derekwisong/datui/releases/download/v0.4.5/datui-v0.4.5-x86_64-pc-windows-msvc.zip
  InstallerSha256: 4AE0933EF91E502EFD505498BD171E0DADF28087D939ADBC7CE2C4543B0B109B
ManifestType: installer
ManifestVersion: 1.12.0
