# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.Nightly.MSIX
PackageVersion: 159.2610.709.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
PackageFamilyName: Mozilla.MozillaFirefoxNightly_jag0gd4e3s9p2
RestrictedCapabilities:
- runFullTrust
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- DisplayName: Firefox Nightly
  Publisher: Mozilla Corporation
Installers:
- Architecture: x86
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-07-09-54-43-mozilla-central/firefox-159.0a1.multi.win32.installer.msix
  InstallerSha256: 123641FF2A7D09559ACC75D9DE025692A2843E194575ED1BB5BFE04FDB62B27B
  SignatureSha256: 47E2FA26F9D577B91FEA57CB6274B14A0DA57E515AECB228828CA942E4DF477F
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2610.709.0_x86__jag0gd4e3s9p2'
- Architecture: x64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-07-09-54-43-mozilla-central/firefox-159.0a1.multi.win64.installer.msix
  InstallerSha256: 4DCEFACBAC754ADE6F56C1CE39BC0E50F75C0E27A30B347CD8B6CA98210711CB
  SignatureSha256: 82413F532DD1F9F65940BA51520DB1B1EDBE973820A3E1DEA8EFA00353D4DE2D
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2610.709.0_x64__jag0gd4e3s9p2'
- Architecture: arm64
  InstallerUrl: https://ftp.mozilla.org/pub/firefox/nightly/2026/10/2026-10-07-09-54-43-mozilla-central/firefox-159.0a1.multi.win64-aarch64.installer.msix
  InstallerSha256: 0B86C6EF42534B666BFE8B3660FD602C5EED2FBA9CAC223DA45B00F99A929D57
  SignatureSha256: 2FC7DC84A9962C0CF64430F2D3AC35FCC5CAE6D8EE0816F78BC8635120D8F389
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/WindowsApps/Mozilla.MozillaFirefoxNightly_159.2610.709.0_arm64__jag0gd4e3s9p2'
ManifestType: installer
ManifestVersion: 1.12.0
