# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ChilliBits.Spice
PackageVersion: 0.28.2
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- silent
UpgradeBehavior: install
ProductCode: '{F3FA4498-344A-4FF8-9C37-2A12082739DA}'
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- ProductCode: '{F3FA4498-344A-4FF8-9C37-2A12082739DA}'
  UpgradeCode: '{AC909E1C-ED5A-4930-8A10-3110EB3201D0}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\Spice'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/spicelang/spice/releases/download/0.28.2/spice_x64_setup.msi
  InstallerSha256: 4CCD8B92A924BE826D1698D960784805EA0C149C9A385BDCBFD72F71362F630D
ManifestType: installer
ManifestVersion: 1.12.0
