# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: h3poteto.fedistar
PackageVersion: 1.13.3
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: "{009F47D7-A9E6-46C7-8B45-D37EC11BACFF}"
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- Publisher: fedistar
  ProductCode: "{009F47D7-A9E6-46C7-8B45-D37EC11BACFF}"
  UpgradeCode: "{41840B3C-ADCE-5123-A0C8-344F6C799161}"
InstallationMetadata:
  DefaultInstallLocation: "%ProgramFiles%\\fedistar"
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/h3poteto/fedistar/releases/download/v1.13.3/fedistar_1.13.3_x64_en-US.msi
  InstallerSha256: 3EFD445C4FB631A2F7B94ABA2FD6F917DE62B129594479AFBC0F95620644F28C
ManifestType: installer
ManifestVersion: 1.12.0
