# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TeamViewer.TeamViewer.Host
PackageVersion: 15.82.6
Scope: machine
UpgradeBehavior: install
Protocols:
- teamviewer8
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: update.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/update/Update_msi_Host_15.82.6.zip
  InstallerSha256: E401E1FC7ED926D71C5B99049AA85C5AD4A598855FF904AA5E96D0973A7FF637
  InstallerSwitches:
    InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  ProductCode: '{E9F1D904-EC64-4048-9B0D-4E284030218F}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{150798A5-21DE-431E-BDC7-A822769BE9A2}'
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_Host_Setup.exe
  InstallerSha256: 304306A923C27EA3C1A45F0C79E9457D8E79DD7B60E19575179719D4578B1CDF
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: update.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/update/Update_msi_Host_15.82.6_x64.zip
  InstallerSha256: 7CD48027E76D98D38F3FE0E0BACE8B913CAFF71985DC4A3FF2BAA6EEB75A36B8
  InstallerSwitches:
    InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  ProductCode: '{EDEC60C1-026C-481F-B3F0-75242104C825}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{82861EC3-25E9-4152-AAA0-BFB2467B60B7}'
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_Host_Setup_x64.exe
  InstallerSha256: CCD6F0AC018CF75A86DAE1EC24C4B2C2725245B454E8D216CF9A70BAF9497BD8
ManifestType: installer
ManifestVersion: 1.12.0
