# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.es-MX
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win32/es-MX/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: E28AB4911DF5E7A1E85BA73B76FCE3F378FA09C3CAEE7DCC464DD8BFD526AD57
  ProductCode: Mozilla Thunderbird 153.4.0 (x86 es-MX)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 es-MX)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win64/es-MX/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: CA2F7AA4B319210162C11B8971DC07DC241E27B26331BD1E0A5D6A964588F9D8
  ProductCode: Mozilla Thunderbird 153.4.0 (x64 es-MX)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 es-MX)
ManifestType: installer
ManifestVersion: 1.12.0
