# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: XinTaoFei.Codeg
PackageVersion: 0.34.0
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: codeg
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/spacering-net/codeg/releases/download/v0.34.0/codeg_0.34.0_x64-setup.exe
  InstallerSha256: 3A977900D096BDB68A881D8C3CEFD187C680EFFB828B5F240B6E7546F0B51138
- Architecture: arm64
  InstallerUrl: https://github.com/spacering-net/codeg/releases/download/v0.34.0/codeg_0.34.0_arm64-setup.exe
  InstallerSha256: 5DA0B27B778AEF2AC492E671ED784CDED4C553B1EB009A2FFE30AECEF45D8C41
ManifestType: installer
ManifestVersion: 1.12.0
