# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ransh2014.TRACE
PackageVersion: 0.5.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: TRACE.exe
  PortableCommandAlias: TRACE
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ransh2014/gt7telemtrace/releases/download/v0.5.2/gt7telem-windows.zip
  InstallerSha256: 3DEFA33100E8A4CD1D4CEFD7B0625CF4F2984E1C465855ACAD2731CB55990DF0
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-01
