# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Ollama.Ollama.Portable
PackageVersion: 0.35.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ollama.exe
Commands:
- ollama
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ollama/ollama/releases/download/v0.35.1/ollama-windows-amd64.zip
  InstallerSha256: DC50B9CA7F9023C86525012632CD1615B093D0407987444A7F62ECAB617E8E93
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/ollama/ollama/releases/download/v0.35.1/ollama-windows-arm64.zip
  InstallerSha256: 1ACED40F0654EAE8EF1BA07FA101BE4B48225308288B0F54C5681CCF1E4199DB
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
