# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Google.Chrome.Canary
PackageVersion: 157.0.8091.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Log: --verbose-logging --log-file="<LOGPATH>"
  Custom: --chrome-sxs --do-not-launch-chrome
ExpectedReturnCodes:
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 4
  ReturnResponse: downgrade
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Google Chrome
ReleaseDate: 2026-10-07
Installers:
- Architecture: x86
  InstallerUrl: https://dl.google.com/release2/chrome/bbge3n76t5rucosxpruku2mzzu_157.0.8091.0/157.0.8091.0_chrome_installer_uncompressed.exe
  InstallerSha256: 4DA2A7FC590E00367CF98DB840A8F2469618A4C0B2575BC38C4D252F9DAB1D34
- Architecture: x64
  InstallerUrl: https://dl.google.com/release2/chrome/ad2ih5ykaob3smgovngk3rpm4kqa_157.0.8091.0/157.0.8091.0_chrome_installer_uncompressed.exe
  InstallerSha256: 28467962A27B25A447D052E1AF7752C5FC5BDACEBD30FA70EA08C35F4C952CD9
- Architecture: arm64
  InstallerUrl: https://dl.google.com/release2/chrome/acnmmf2wp6uagzhzdrwv24r3hhaa_157.0.8091.0/157.0.8091.0_chrome_installer_uncompressed.exe
  InstallerSha256: B306099640F5139C42D1D655AD1EFABBA9CAC84CC4E3F5A71B5A8D2616E26098
ManifestType: installer
ManifestVersion: 1.12.0
