# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: BrowserOS.BrowserClawServer
PackageVersion: 0.0.68
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: resources\bin\browseros-claw-server.exe
Commands:
- browseros-claw-server
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/browseros-ai/BrowserOS/releases/download/claw-server/v0.0.68/browseros-claw-server-rust-resources-windows-x64.zip
  InstallerSha256: 22A948AE293B8F150CCF1A87701CAF262D24F01E1A1D9F790B4BDAB4167778B7
ManifestType: installer
ManifestVersion: 1.12.0
