# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ESEngine.ReasonixCLI
PackageVersion: 1.39.6
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: reasonix.exe
Commands:
- reasonix
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v1.39.6/reasonix-windows-amd64.zip
  InstallerSha256: 8F480D755C14D67E2B17DBEB268F6B2D52FD76EEDBA9C06600A17150F191AFE5
- Architecture: arm64
  InstallerUrl: https://github.com/esengine/DeepSeek-Reasonix/releases/download/v1.39.6/reasonix-windows-arm64.zip
  InstallerSha256: 3F6CF6455E646FCBBFCA5AAD073C9CF35A939B1A5B2D6AAA9B95B0B79006D232
ManifestType: installer
ManifestVersion: 1.12.0
