# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: GAM-Team.gam.Portable
PackageVersion: 7.48.24
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: gam7/gam.exe
  PortableCommandAlias: gam
ReleaseDate: 2026-10-08
Installers:
- Architecture: arm64
  InstallerUrl: https://github.com/GAM-team/GAM/releases/download/v7.48.24/gam-7.48.24-windows-arm64.zip
  InstallerSha256: D70E15D106668A15736BD24AAF11EA480D41E84271DF056AFC6FDD47056CCD43
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
- Architecture: x64
  InstallerUrl: https://github.com/GAM-team/GAM/releases/download/v7.48.24/gam-7.48.24-windows-x86_64.zip
  InstallerSha256: 73F0F637BEA3A1EB62ED04116ACEFDFD50939BC20C2D7E2156C78F56130A70A4
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.12.0
