# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Brave.Brave.Nightly
PackageVersion: 155.1.98.44
InstallerType: exe
ExpectedReturnCodes:
- InstallerReturnCode: -2147219440
  ReturnResponse: cancelledByUser
- InstallerReturnCode: -2147219416
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: -2147218431
  ReturnResponse: invalidParameter
- InstallerReturnCode: -2147024809
  ReturnResponse: invalidParameter
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: BraveSoftware Brave-Browser
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.44/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 99924B6E2B24F7F93672DDBA2DBC680440A9EAEB07A72638C127FFA54613F388
  InstallModes:
  - silent
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.44/BraveBrowserStandaloneNightlySetup32.exe
  InstallerSha256: 2339385A3AF57D3F008587331A62169142A2C378C78D9E5D2C1A97A7E5F85E2C
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.44/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: D67C18D052E3CD655FC393EDAD21E945880251C33AAE5AEDFA46BEB9269CF040
  InstallModes:
  - silent
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.44/BraveBrowserStandaloneNightlySetup.exe
  InstallerSha256: 102F34297D2650F03C823FED9E91A1DEDC828E9FAF9B9955137AE4081F1F1478
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.44/BraveBrowserStandaloneSilentNightlySetupArm64.exe
  InstallerSha256: 5CFD073B7967D39B086399943E9050FDA38BF30ACE42EB7C696572157811B6DF
  InstallModes:
  - silent
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.98.44/BraveBrowserStandaloneNightlySetupArm64.exe
  InstallerSha256: 5314449AC4EC94E9A1956A18BED6C51D46F2B24E43391EBFC7ABF6E1F4C3780F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent /install
    SilentWithProgress: /silent /install
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.12.0
