# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: hrzlgnm.zux
PackageVersion: 1.21.0
PackageLocale: en-US
Publisher: hrzlgnm
PublisherUrl: https://github.com/hrzlgnm
PublisherSupportUrl: https://github.com/hrzlgnm/zux/issues
Author: hrzlgnm
PackageName: zux
PackageUrl: https://github.com/hrzlgnm/zux
License: MIT
LicenseUrl: https://github.com/hrzlgnm/zux/blob/HEAD/LICENSE
Copyright: Copyright (c) hrzlgnm
ShortDescription: zux
Description: mDNS-SD visualizer with force-directed graph visualization
Tags:
- mdns-sd
- sveltejs
- tauri-app
- tauri-v2
- vis-network
ReleaseNotes: |-
  1.21.0 (2026-10-06)
  Features
  - publish partial release as pre-release on build failure (#489) (360340a)
  - use custom dropdowns for theme and solver selects (#490) (fcacceb)
  Dependencies
  - update archlinux:base-devel docker digest to 996c3a1 (#485) (01c8ff6)
  - update ghcr.io/hrzlgnm/zux-arch-aur-builder:v1 docker digest to 8d99c3e (#487) (9f59da2)
  - update pnpm to v12.9.0 (#488) (feaee81)
ReleaseNotesUrl: https://github.com/hrzlgnm/zux/releases/tag/v1.21.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
