# Automatically updated by the winget bot at 2024/Oct/12
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Neovim.Neovim.Nightly
PackageVersion: 0.11.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
AppsAndFeaturesEntries:
- DisplayName: Neovim
  UpgradeCode: '{207A1A70-7B0C-418A-A153-CA6883E38F4D}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.msi
  InstallerSha256: 5C79FB13FB4793AE35A2E3AC8252C224335442220B3AA92CC9CBB3C29DDDE64B
  ProductCode: '{49FBEB74-0BC0-4B18-A454-A1042DC34EE6}'
ManifestType: installer
ManifestVersion: 1.5.0
