# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Oven-sh.Bun
PackageVersion: 1.4.3
InstallerType: zip
NestedInstallerType: portable
Commands:
- bun
- bunx
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: ./bun-windows-x64/bun.exe
    PortableCommandAlias: bunx
  - RelativeFilePath: bun-windows-x64/bun.exe
    PortableCommandAlias: bun
  InstallerUrl: https://github.com/oven-sh/bun/releases/download/bun-v1.4.3/bun-windows-x64.zip
  InstallerSha256: 0BF84E808552BEEA67BF1202A287A35C6C825D837B287B3F8E9DD513DBA35D3D
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: ./bun-windows-aarch64/bun.exe
    PortableCommandAlias: bunx
  - RelativeFilePath: bun-windows-aarch64/bun.exe
    PortableCommandAlias: bun
  InstallerUrl: https://github.com/oven-sh/bun/releases/download/bun-v1.4.3/bun-windows-aarch64.zip
  InstallerSha256: 5E8F142EF722CBC9F67DC068A166E46EE72BE8307B38CAC7186589D2FACE668F
ManifestType: installer
ManifestVersion: 1.28.0
