# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Termaxa.Termaxa
PackageVersion: 0.21.0
InstallerType: portable
Commands:
- termaxa
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/termaxa/termaxa/releases/download/v0.21.0/termaxa-windows-x86_64.exe
  InstallerSha256: 529E2C58D022858E5691962C2A5FF0D0B7368237AF0CFB577691FE4838E8F2F4
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-07
