# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: uu201.CharacterArc
PackageVersion: 1.21.1
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: 49938137-299e-5c61-8d81-5dc02724dce8
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/uu201/character-arc/releases/download/v1.21.1/CharacterArc-1.21.1-x64-setup.exe
  InstallerSha256: AA511DDA974132D64AA963F37BD7FA208258919A89E63CB1409E671246848907
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/uu201/character-arc/releases/download/v1.21.1/CharacterArc-1.21.1-x64-setup.exe
  InstallerSha256: AA511DDA974132D64AA963F37BD7FA208258919A89E63CB1409E671246848907
  InstallerSwitches:
    Custom: /allusers
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/uu201/character-arc/releases/download/v1.21.1/CharacterArc-1.21.1-arm64-setup.exe
  InstallerSha256: F1C1864FDF7C95E9D871FF8C6703B841E5ECE5739C798757482E03ED23B372AF
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/uu201/character-arc/releases/download/v1.21.1/CharacterArc-1.21.1-arm64-setup.exe
  InstallerSha256: F1C1864FDF7C95E9D871FF8C6703B841E5ECE5739C798757482E03ED23B372AF
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
