# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Firefox.is
PackageVersion: 157.0.1
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ProductCode: Mozilla Firefox
ReleaseDate: 2026-10-06
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win32/is/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 9416C6000680DECDDF4A8DC7AC7FDCF01037F1CF6B35D8043EFD44C0ECC367B5
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64/is/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 981DE2BDDADF2EECE5A7876F371EBC0F1FC78802FA9EFBF687870377AA8566CC
- Architecture: arm64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/157.0.1/win64-aarch64/is/Firefox%20Setup%20157.0.1.exe
  InstallerSha256: 507C2F1E95BE69E21FF70E1C49401351471D1F1141571A740336E0BE799A10DD
ManifestType: installer
ManifestVersion: 1.12.0
