# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Buildkite.Agent
PackageVersion: 4.3.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: buildkite-agent.exe
  PortableCommandAlias: buildkite-agent
Commands:
- buildkite-agent
ReleaseDate: 2026-10-08
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/buildkite/agent/releases/download/v4.3.0/buildkite-agent-windows-386-4.3.0.zip
  InstallerSha256: 5B2D4A8687D04B8E690DAD59BA707140499CBE255D824B2CB36EC75CCA0DAAC3
- Architecture: x64
  InstallerUrl: https://github.com/buildkite/agent/releases/download/v4.3.0/buildkite-agent-windows-amd64-4.3.0.zip
  InstallerSha256: 688D66FD437BC3E1679DF4DA2B9B274959620BE4233867CF8F629B8C3099123E
- Architecture: arm64
  InstallerUrl: https://github.com/buildkite/agent/releases/download/v4.3.0/buildkite-agent-windows-arm64-4.3.0.zip
  InstallerSha256: E1FC5D836DF63201B3DB5F3A4914A1E3D53EF55C3DF0AFA4AE447EA5FAE2CCCA
ManifestType: installer
ManifestVersion: 1.28.0
