# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Kiwix.KiwixJS
PackageVersion: 3.9.3.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.14316.0
InstallerType: appx
PackageFamilyName: Kiwix.KiwixJS_5t57d9aw10jep
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kiwix/kiwix-js-pwa/releases/download/v3.9.3/Kiwix-JS-Electron-3.9.3-E.appx
  InstallerSha256: 45066C62478EA0B3BB04C214670D1EBF187BD4C4D7D6CD92A73C8B06F5B9555B
  SignatureSha256: F9A8008414741569A479C220A90DD970D8479136C621AB9CAEB5FD10A8F94119
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
