# Created with WinGet Tracker using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: t8y2.DBX
PackageVersion: 0.6.34
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: DBX
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- Publisher: dbx
  ProductCode: DBX
InstallationMetadata:
  DefaultInstallLocation: placeholder\DBX
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/t8y2/dbx/releases/download/v0.6.34/DBX_0.6.34_x64-setup.exe
  InstallerSha256: 13362F73ED81B5988EBC6D7E6EC63AEB4A197647C706121AB9F1CF45EFEE0B7C
ManifestType: installer
ManifestVersion: 1.12.0
