# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tonec.InternetDownloadManager
PackageVersion: 6.43.14
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silentWithProgress
InstallerSwitches:
  Silent: /skipdlgs
  SilentWithProgress: /skipdlgs
UpgradeBehavior: install
ProductCode: Internet Download Manager
ReleaseDate: 2026-10-07
Installers:
- Architecture: x86
  InstallerUrl: https://download.internetdownloadmanager.com/idman643build14.exe
  InstallerSha256: 5FBB5126EF5E7625D233F5C1C3BD664B6310C028FDFD1F0BC7EE81D15FC5983B
ManifestType: installer
ManifestVersion: 1.12.0
