# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WJZ_P.BiliMaku
PackageVersion: 1.0.4
ReleaseDate: 2026-08-24
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/WJZ-P/BiliMaku/releases/download/v1.0.4/BiliMaku-v1.0.4-windows-x64-setup.exe
  InstallerSha256: 931A7B3C7BD5A80E83A458C10C41C25CAAE78B91F04216153AA0C12FAF3EA6D8
  ProductCode: BiliMaku
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\BiliMaku'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/WJZ-P/BiliMaku/releases/download/v1.0.4/BiliMaku-v1.0.4-windows-x64.msi
  InstallerSha256: BD7F5E568E4FDB3D8798E45E463175D7CEB6E0CDAD412028943C34D66771B23B
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{5AA3C0D9-29AF-4912-ACBC-F4A5E730EA28}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{47335D3B-6191-54BD-B179-F9FB5155F86C}'
ManifestType: installer
ManifestVersion: 1.12.0
