# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: FrankZhu.ZManagerCLI
PackageVersion: 2.1.7
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: zm.exe
  PortableCommandAlias: zm
Commands:
- zm
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tzap-org/zmanager/releases/download/v2.1.7/zm-x86_64-pc-windows-msvc.zip
  InstallerSha256: 988387DB40B1B3A3B0801BDA0D012F02E69930A3F8CD10B962FDC6223301587D
- Architecture: arm64
  InstallerUrl: https://github.com/tzap-org/zmanager/releases/download/v2.1.7/zm-aarch64-pc-windows-msvc.zip
  InstallerSha256: D9FECF7DD498B4A66891EB683C154CD2A5D52020946A5A252825F30343F7D18D
ManifestType: installer
ManifestVersion: 1.12.0
