# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Formagrid.Airtable
PackageVersion: 1.7.1
PackageLocale: zh-CN
License: 专有软件
ShortDescription: Airtable 桌面应用——用于构建协作式应用的低代码平台。
Description: Airtable 是一个用于构建协作式应用的低代码平台。Windows 应用让您可以在 PC 上使用 Airtable，自定义工作流、实时协作、自动执行重复性任务并简化业务流程。
Tags:
- 低代码
- 自动化
ManifestType: locale
ManifestVersion: 1.12.0
