# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: jdx.mise
PackageVersion: 2026.9.17
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: mise/bin/mise-shim.exe
  PortableCommandAlias: mise-shim
- RelativeFilePath: mise/bin/mise.exe
  PortableCommandAlias: mise
UpgradeBehavior: install
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.9.17/mise-v2026.9.17-windows-x64.zip
  InstallerSha256: EFE776B69B231A0C917AD590E8CC873D1D86DB4ED3162204EBE030EB712F77FE
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/jdx/mise/releases/download/v2026.9.17/mise-v2026.9.17-windows-arm64.zip
  InstallerSha256: E3B949FD3C1C13A52E4DC5D85C69DAEBDD9868A6E9E4957A2816114DD5FFD80E
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.28.0
