# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: DBMobile.Resonance
PackageVersion: 3.3.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: Resonance
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- Publisher: github
  ProductCode: Resonance
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Resonance'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/db-mobile/resonance/releases/download/v3.3.1/Resonance_3.3.1_x64-setup.exe
  InstallerSha256: C347C3954BE29290B56CB29F48033DCD59F10DD8650E24610871803EFC816AE6
- Architecture: arm64
  InstallerUrl: https://github.com/db-mobile/resonance/releases/download/v3.3.1/Resonance_3.3.1_arm64-setup.exe
  InstallerSha256: 90EBCB285CCCFB0A3780D0783DEDDB6802CF948AD2D95AC024A27B0E8B48EC6B
ManifestType: installer
ManifestVersion: 1.12.0
