# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VovSoft.PDFReader
PackageVersion: 6.0.0.0
InstallerLocale: en-US
Installers:
- Architecture: x86
  InstallerType: inno
  Scope: machine
  InstallerUrl: https://files.vovsoft.com/pdf-reader.exe
  InstallerSha256: 40DF4624674D4F250B836CFDF2A904406790175722CED339BD23AE72DA8FB229
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  FileExtensions:
  - PDF
  ProductCode: PDF Reader_is1
  AppsAndFeaturesEntries:
  - ProductCode: PDF Reader_is1
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\VOVSOFT\PDF Reader'
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: pdfreader.exe
    PortableCommandAlias: pdfreader
  InstallerUrl: https://files.vovsoft.com/pdf-reader-portable.zip
  InstallerSha256: B582DF38C2A971330ED3BBE94D2434E27E840829CA873DBE1F3C16DDF04CBCE3
  ArchiveBinariesDependOnPath: true
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-02
