# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NimbusAgent.Nimbus
PackageVersion: 7.35.0
InstallerType: wix
ProductCode: '{A9F1A28E-32AE-487A-B838-3257CA880C93}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nimbus-agent/Nimbus/releases/download/v7.35.0/nimbus-headless-windows-x64.msi
  InstallerSha256: 305A657BA4A6DBD6C65C4EAB4F81415057DA223E29B00A1DA94881640D38D8D4
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
