# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: IndependentPhotoSupplies.PhotoLabQc
PackageVersion: 3.0.207
InstallerLocale: en-US
InstallerType: msi
Scope: machine
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
ProductCode: '{46BF982A-1CAD-45EA-91C7-79B9886B884E}'
Installers:
- Architecture: x64
  InstallerUrl: https://PhotoLabQc.com/download/PhotolabQcInstaller207.msi
  InstallerSha256: 2E210671D77A115EAC1A4E321ED84C7BE3787E093DAAC098470899F588695CC8
ManifestType: installer
ManifestVersion: 1.12.0
