# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PostgreSQL.PostgreSQL.17
PackageVersion: 17.11-5
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --mode unattended --unattendedmodeui none
  SilentWithProgress: --mode unattended --unattendedmodeui minimal
  InstallLocation: --prefix "<INSTALLPATH>"
UpgradeBehavior: install
ProductCode: PostgreSQL 17
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://get.enterprisedb.com/postgresql/postgresql-17.11-5-windows-x64.exe
  InstallerSha256: 612C7F5400A003AAFFA0372CB273EED52278F93C680AB911EB9CB2229E329072
ManifestType: installer
ManifestVersion: 1.12.0
