# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ChrisKlimas.Twine
PackageVersion: 2.12.1
PackageLocale: en-US
Publisher: Chris Klimas
PublisherSupportUrl: https://github.com/klembot/twinejs/issues
Author: Chris Klimas
PackageName: Twine
PackageUrl: https://twinery.org/
License: GPL-3.0
LicenseUrl: https://github.com/klembot/twinejs/blob/HEAD/LICENSE
Copyright: Copyright © 2026 Chris Klimas
ShortDescription: An open-source tool for telling interactive, nonlinear stories with variables, conditional logic, images, CSS, and JavaScript
Description: |-
  Twine is an open-source tool for telling interactive, nonlinear stories.
  You don't need to write any code to create a simple story with Twine, but you can extend your stories with variables, conditional logic, images, CSS, and JavaScript when you're ready.
  Twine publishes directly to HTML, so you can post your work nearly anywhere. Anything you create with it is completely free to use any way you like, including for commercial purposes.
Tags:
- stoeytelling
- story
ReleaseNotes: |-
  New Features Added
  - Twine' Polish translation has been updated.
  - The Electron version used by app Twine has been updated to version 43.
  Bugs Fixed
  - A security problem where a maliciously-crafted story could run commands locally in App Twine has been fixed. There have been no reports of this occurring to users to this point.
  - Pending changes in the passage editor are immediately saved when the editor loses focus, so that if the app is closed immediately afterwards, what was entered is saved.
  - App Twine no longer creates extraneous directories in the temporary directory when saving story files.
  - A bug where, in some localizations, the story list would mistakenly say there was 1 story, when in fact there were 0, was fixed.
  Story Format Updates
  - Snowman has been updated to version 2.1.3.
ReleaseNotesUrl: https://github.com/klembot/twinejs/blob/HEAD/docs/en/src/release-notes/2-12.md#2121
Documentations:
- DocumentLabel: Reference
  DocumentUrl: https://twinery.org/reference/en/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
