# Automatically updated by the winget bot at 2026/Oct/05
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: ImplicitInc.ImplicitDesktopApp
PackageVersion: 4.2.3
InstallerLocale: en-US
InstallerType: msi
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://s3.us-west-1.amazonaws.com/downloads.outlook-integration.com/software/ImplicitForOutlookIOSetup(x86).msi
  InstallerSha256: 5660CDAB4D8F861306E618833B0C67FBC03517FD008E03171AE72D4A80FC4B52
  ProductCode: '{53733D2D-8061-403D-85FA-A38906CC2A07}'
  AppsAndFeaturesEntries:
  - DisplayName: Implicit for Outlook
    ProductCode: '{835DF3A0-E808-41D3-88F3-8F3409ABDCB9}'
    UpgradeCode: '{F3FFA32D-4809-43A6-B069-B8E45E447D71}'
- Architecture: x64
  InstallerUrl: https://s3.us-west-1.amazonaws.com/downloads.outlook-integration.com/software/ImplicitForOutlookIOSetup(x64).msi
  InstallerSha256: F9387DDE1BF3B27ECCA3E64F0A0616FCA183AB021014E53EB0115759E4E777F4
  ProductCode: '{0C07B415-EB44-4C4A-B0E2-C9CD67C634A1}'
  AppsAndFeaturesEntries:
  - DisplayName: Implicit for Outlook
    ProductCode: '{059D2166-4FD6-486F-BAF3-364E5BE8DDA4}'
    UpgradeCode: '{F3FFA32D-4809-43A6-B069-B8E45E447D71}'
ManifestType: installer
ManifestVersion: 1.28.0
