# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Wallnode.Wallnode
PackageVersion: 1.2.1
MinimumOSVersion: 10.0.17763.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
AppsAndFeaturesEntries:
- DisplayName: WALLNODE
  Publisher: WALLNODE
  ProductCode: '{F78BCAC1-7B75-4B4C-84C1-9EFF1EB64557}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bogdanspn/wallnode-releases/releases/download/v1.2.1/WallnodeSetup-1.2.1.exe
  InstallerSha256: 749148FE5BC65BEA312F14C93594D04A663AFA29163D9E3D80EA185DC164F1F7
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-09
