# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Amazon.AWSVPNClient
PackageVersion: 6.1.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-09-25
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Amazon\AWS VPN Client'
Installers:
- Architecture: x64
  InstallerUrl: https://d3c4iklh14o4hj.cloudfront.net/WPF/6.1.1/AWS_VPN_Client.msi
  InstallerSha256: 8F57525C843EA94CBD835B45298F2CE3CBDB62FC331B40139C4785AF4E8BA51B
  ProductCode: '{70B0C42E-2B99-43C0-90E4-2A3C7C42B373}'
  AppsAndFeaturesEntries:
  - ProductCode: '{70B0C42E-2B99-43C0-90E4-2A3C7C42B373}'
    UpgradeCode: '{8D1975AA-4987-4668-ACD2-66EC556E5608}'
- Architecture: arm64
  InstallerUrl: https://d3c4iklh14o4hj.cloudfront.net/WPF_ARM64/6.1.1/AWS_VPN_Client_ARM64.msi
  InstallerSha256: 1FA1E6D2B5F9914D93BD0898B32C3B36692772DD4C65A52A49D231C8D4CE05B6
  ProductCode: '{612FC541-361D-4CCF-9961-048469D0B5E6}'
  AppsAndFeaturesEntries:
  - ProductCode: '{612FC541-361D-4CCF-9961-048469D0B5E6}'
    UpgradeCode: '{8D1975AA-4987-4668-ACD2-66EC556E5608}'
ManifestType: installer
ManifestVersion: 1.12.0
