# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Postman.Postman
PackageVersion: 12.31.3
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- postman
ProductCode: Postman
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://dl.pstmn.io/download/version/12.31.3/windows_64
  InstallerSha256: 1EE4667152B9BD21506B11B78E19E61F89BA320B7FDBE24311D2CD6C609259C9
ManifestType: installer
ManifestVersion: 1.12.0
