# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MediaHuman.YouTubeDownloader
PackageVersion: 3.9.24
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Protocols:
- ytd
ProductCode: MediaHuman YouTube Downloader_is1
ReleaseDate: 2026-10-01
Installers:
- Architecture: x86
  InstallerUrl: https://www.mediahuman.com/files/YouTubeDownloader.exe
  InstallerSha256: C286D67FA3220AC5EEA1642E09E214E8929D9EC6C9DAF8C5B0E2075255C602AB
- Architecture: x64
  InstallerUrl: https://www.mediahuman.com/files/YouTubeDownloader-x64.exe
  InstallerSha256: 1864BF257EE3E756CD812A392B750A1FFDEEB20D9B9B4AA6B76B806DA9EC43CF
ManifestType: installer
ManifestVersion: 1.12.0
