# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ByteDance.Feishu.MSI
PackageVersion: 8.0.0.0
InstallerType: wix
InstallerSwitches:
  InstallLocation: INSTALL_DIR="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- feishu
- feishu-open
- lark
- x-feishu
ReleaseDate: 2026-10-09
AppsAndFeaturesEntries:
- UpgradeCode: '{8377F56B-909B-49B2-8C05-7B06D608D95D}'
Installers:
- Architecture: x86
  InstallerUrl: https://sf3-cn.feishucdn.com/obj/hera-cn/download/Feishu-win32_ia32-8.0.3-signed.msi
  InstallerSha256: CDE9D75B6D04A625B28981D4306318265FB54F273CC9801A28DB53F1E50B6415
  ProductCode: '{380164C2-0574-4537-9DF2-0C12F8A6099E}'
- Architecture: x64
  InstallerUrl: https://sf3-cn.feishucdn.com/obj/hera-cn/download/Feishu-win32_x64-8.0.3-signed.msi
  InstallerSha256: 5A511A5D1BC9126B22A14BC0A475EB1DD47E5D007BC393BE8BB615F63AC8EACC
  ProductCode: '{325757C6-8F8C-48A5-8B80-D4E757C3F621}'
ManifestType: installer
ManifestVersion: 1.12.0
