# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Comfy.ComfyUI-Desktop
PackageVersion: 1.1.6
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
ProductCode: f0c0feae-2b28-5d68-8c25-d93f41e47df2
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://download.todesktop.com/241130tqe9q3y/Comfy%20Desktop%20Setup%201.1.6%20-%20Build%20261003uci82pdkd-x64.exe
  InstallerSha256: F81CCFC89189664982EF6F96DDCE23FBA15F472C5E8F878931D37FAC957C108E
ManifestType: installer
ManifestVersion: 1.12.0
