# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Slidict.Wip
PackageVersion: 2.9.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wip.exe
  PortableCommandAlias: wip
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/slidict/wip/releases/download/v2.9.1/wip-2.9.1-win-x64.zip
  InstallerSha256: A8EE80141F00101B306EF798234D07E650DD89032262A80A353A5F771BDB7FC0
ManifestType: installer
ManifestVersion: 1.12.0
