# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: qingchencloud.ClawPanel
PackageVersion: 0.22.0
UpgradeBehavior: install
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/qingchencloud/clawpanel/releases/download/v0.22.0/ClawPanel_0.22.0_x64-setup-full.exe
  InstallerSha256: B65949451F4E391BB6B597239B085F494BD47B3CE62FE0350CFBBB03CB5C1AA2
  ProductCode: ClawPanel
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/qingchencloud/clawpanel/releases/download/v0.22.0/ClawPanel_0.22.0_x64-full_en-US.msi
  InstallerSha256: 6D842C42FDB12FF0312BFC4B4A0CB480F321EABEB03C429C6C439BB48AA20629
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  ProductCode: '{4726136B-404D-4C90-BBD0-520FA7F92BE3}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{AA908EA1-FFA0-5A0E-B2C5-14A7B8C64033}'
ManifestType: installer
ManifestVersion: 1.12.0
