# Created with WinGet Tracker using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: zerx-lab.FluxDown
PackageVersion: 0.5.1
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /CURRENTUSER
UpgradeBehavior: install
ProductCode: '{B7E3F2A1-5C4D-4E8F-9A6B-1D2E3F4A5B6C}_is1'
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- ProductCode: '{B7E3F2A1-5C4D-4E8F-9A6B-1D2E3F4A5B6C}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\FluxDown'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zerx-lab/FluxDown/releases/download/v0.5.1/FluxDown-0.5.1-windows-x64-setup.exe
  InstallerSha256: D65D1602C93AA251325EFC46BE4106DF2D003DAFCA7EA21EAA11745D4D241B63
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/zerx-lab/FluxDown/releases/download/v0.5.1/FluxDown-0.5.1-windows-arm64-setup.exe
  InstallerSha256: 2CA0FDE0D0014AD28C0EE1ED3CC965994AD5215F05C945DC389091512C431975
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
