# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: VoSoft.VicDiary
PackageVersion: 2.2.0
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- vic-diary
ProductCode: e709069e-9356-5406-ac2a-2269093c54ed
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://gitee.com/vo-soft/vic-diary-release/releases/download/latest/vic-diary-2.2.0-setup.exe
  InstallerSha256: 532A843031E781A0CDD3F29EF7443316725D3DA26F4C138238C81945E192BE05
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://gitee.com/vo-soft/vic-diary-release/releases/download/latest/vic-diary-2.2.0-setup.exe
  InstallerSha256: 532A843031E781A0CDD3F29EF7443316725D3DA26F4C138238C81945E192BE05
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.12.0
