# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mozilla.Thunderbird.ESR.ko
PackageVersion: 153.4.0
InstallerType: nullsoft
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win32/ko/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: 887EF056FBFE1C3ADB40553696A77602684BE9F0AB00F83A906EC2DF69B68228
  ProductCode: Mozilla Thunderbird 153.4.0 (x86 ko)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x86 ko)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/153.4.0esr/win64/ko/Thunderbird%20Setup%20153.4.0esr.exe
  InstallerSha256: F0F438B89648E0E00A3989F8BFF9AB7F11A6926EA24CFA29F1D83A59B1384BD0
  ProductCode: Mozilla Thunderbird 153.4.0 (x64 ko)
  AppsAndFeaturesEntries:
  - DisplayName: Mozilla Thunderbird (x64 ko)
ManifestType: installer
ManifestVersion: 1.12.0
