# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: hatayama.uloop
PackageVersion: 3.7.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: uloop.exe
    PortableCommandAlias: uloop
Commands:
  - uloop
ReleaseDate: 2026-10-06
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hatayama/unity-cli-loop/releases/download/dispatcher-v3.7.0/uloop-dispatcher-windows-amd64.zip
    InstallerSha256: F2F3949EFAB8BD1D2AB5DCDD4B4A558B73965603DFFDB5C133A39B904C519F68
ManifestType: installer
ManifestVersion: 1.10.0
