# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: legowerewolf.AO3Fetch
PackageVersion: 2.1.7
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: release\AO3fetch.exe
  PortableCommandAlias: ao3fetch
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/legowerewolf/AO3fetch/releases/download/v2.1.7/ao3fetch-v2.1.7-windows-amd64.zip
  InstallerSha256: DF39D51300C9468E44B962DC69204A66665576B00BDD15B1C083A6CF40E1C29E
- Architecture: x86
  InstallerUrl: https://github.com/legowerewolf/AO3fetch/releases/download/v2.1.7/ao3fetch-v2.1.7-windows-386.zip
  InstallerSha256: B4E50201C0E9CCD4BBE307A1F8566BEC732E8D94C40AE46583811A94B9203FF7
- Architecture: arm64
  InstallerUrl: https://github.com/legowerewolf/AO3fetch/releases/download/v2.1.7/ao3fetch-v2.1.7-windows-arm64.zip
  InstallerSha256: 938F59D362B104EF8BCF9D443780AFD02C11B4BAFB0898754B9A517707539E62
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-09
