# Created with App-Store-Connect-CLI/scripts/generate_winget_manifests.py
PackageIdentifier: Rorkai.ASC
PackageVersion: 5.9.0
InstallerType: portable
Commands:
  - asc
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/rorkai/App-Store-Connect-CLI/releases/download/5.9.0/asc_5.9.0_windows_amd64.exe
    InstallerSha256: 109852EB3D5B2AF92999707A9A0A44DD2054949BA7196B4B07B747306E06A5AA
ManifestType: installer
ManifestVersion: 1.6.0
