# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Victor141516.Voolime
PackageVersion: 0.7.0
PackageLocale: en-US
Publisher: Voolime
PublisherUrl: https://github.com/victor141516/voolime
PublisherSupportUrl: https://github.com/victor141516/voolime/issues
Author: victor141516
PackageName: Voolime
PackageUrl: https://github.com/victor141516/voolime
License: Freeware
ShortDescription: Tiny per-app volume control for Windows.
Description: Voolime extends the native Windows volume key experience with per-app volume control. Hold a modifier and press your keyboard volume keys to adjust the app you are currently using instead of the global system volume.
Moniker: voolime
Tags:
- audio
- hotkeys
- keyboard
- productivity
- utility
- volume
- windows
ReleaseNotes: |-
  ## What's Changed
  • Ship self-contained releases and support WinKit management by @victor141516 in https://github.com/victor141516/voolime/pull/1

  ## New Contributors
  • @victor141516 made their first contribution in https://github.com/victor141516/voolime/pull/1

  **Full Changelog**：https://github.com/victor141516/voolime/compare/v0.6.0...v0.7.0
ReleaseNotesUrl: https://github.com/victor141516/voolime/releases/tag/v0.7.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
