# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: snapetech.iptvtunerr
PackageVersion: 0.1.88
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: iptv-tunerr-v0.1.88-windows-amd64/iptv-tunerr.exe
  PortableCommandAlias: iptv-tunerr
Commands:
- iptv-tunerr
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/snapetech/iptvtunerr/releases/download/v0.1.88/iptv-tunerr-v0.1.88-windows-amd64.zip
  InstallerSha256: 225110d5490544e859cdb600b376cc794ccb2768484d476aae887721044bb96b
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-01
