# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Corsinvest.cv4pve.nodeprotect
PackageVersion: 2.2.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: cv4pve-node-protect.exe
  PortableCommandAlias: cv4pve-node-protect
ReleaseDate: 2026-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Corsinvest/cv4pve-node-protect/releases/download/v2.2.0/cv4pve-node-protect.exe-win-x86.zip
  InstallerSha256: A7B4C6A31659D381E97463688202376323FDCA15C2AAE2B6DA6E65A64ABABF4A
- Architecture: x64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-node-protect/releases/download/v2.2.0/cv4pve-node-protect.exe-win-x64.zip
  InstallerSha256: CE55B94AAA947F800AF58EE960842D8B366B036769B4A1A6C52078640981A045
- Architecture: arm64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-node-protect/releases/download/v2.2.0/cv4pve-node-protect.exe-win-arm64.zip
  InstallerSha256: A74669418F262C9B73A27476A6BD3566BE53F710AB7FB1EB70BE64178E56D1E2
ManifestType: installer
ManifestVersion: 1.12.0
